/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ApiType
 * @generated
 */
export const ApiType = {
  PROVIDER: 'PROVIDER',
  CONSUMER: 'CONSUMER',
  NONE: 'NONE'
} as const;

export type ApiType = typeof ApiType[keyof typeof ApiType];

/**
 * Get enum value by name
 */
export function getApiType(name: string): ApiType | undefined {
  return (ApiType as Record<string, string>)[name] as ApiType | undefined;
}

/**
 * Get enum value by literal
 */
export function getApiTypeByLiteral(literal: string): ApiType | undefined {
  if (literal === 'PROVIDER') return ApiType.PROVIDER;
  if (literal === 'CONSUMER') return ApiType.CONSUMER;
  if (literal === 'NONE') return ApiType.NONE;
  return undefined;
}
