/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Parameter } from './Parameter.js';
import type { Property } from './Property.js';

/**
 * Argument
 * @generated
 */
export interface Argument extends EObject {
  parameter: Parameter;
  value?: Property;

}
