/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Property } from './Property.js';

/**
 * Capability
 * @generated
 */
export interface Capability extends EObject {
  namespace: string;
  attributes: EList<Property>;

}
