/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Property } from './Property';

/**
 * Capability
 * @generated
 */
export interface Capability extends EObject {
  namespace: string;
  attributes: Property[];

}
