/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { Property } from './Property.js';
import type { Capability } from './Capability.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of Capability
 * @generated
 */
export class CapabilityImpl extends BasicEObject implements Capability {
  // Feature ID Constants (eLiterals)
  static readonly NAMESPACE: number = 0;
  static readonly ATTRIBUTES: number = 1;

  // Private fields
  private _namespace: string = "";
  private _attributes!: EList<Property>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.CAPABILITY;
  }

  // Getters and Setters
  get namespace(): string {
    return this._namespace!;
  }

  set namespace(value: string) {
    const oldValue = this._namespace;
    this._namespace = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(CapabilityImpl.NAMESPACE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => CapabilityImpl.NAMESPACE,
        merge: () => false
      });
    }
  }

  get attributes(): EList<Property> {
    if (!this._attributes) {
      this._attributes = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('attributes') as EReference);
    }
    return this._attributes;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case CapabilityImpl.NAMESPACE:
        return this.namespace;
      case CapabilityImpl.ATTRIBUTES:
        return this.attributes;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case CapabilityImpl.NAMESPACE:
        this.namespace = newValue as string;
        super.eSet(feature, newValue);
        break;
      case CapabilityImpl.ATTRIBUTES:
        this.attributes.clear();
        this.attributes.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case CapabilityImpl.NAMESPACE:
        return this._namespace !== "";
      case CapabilityImpl.ATTRIBUTES:
        return this._attributes !== undefined && !this._attributes.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case CapabilityImpl.NAMESPACE:
        this._namespace = "";
        return;
      case CapabilityImpl.ATTRIBUTES:
        if (this._attributes) this._attributes.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

}
