/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * CatalogStatus
 * @generated
 */
export const CatalogStatus = {
  ACTIVE: 'ACTIVE',
  DEPRECATED: 'DEPRECATED'
} as const;

export type CatalogStatus = typeof CatalogStatus[keyof typeof CatalogStatus];

/**
 * Get enum value by name
 */
export function getCatalogStatus(name: string): CatalogStatus | undefined {
  return (CatalogStatus as Record<string, string>)[name] as CatalogStatus | undefined;
}

/**
 * Get enum value by literal
 */
export function getCatalogStatusByLiteral(literal: string): CatalogStatus | undefined {
  if (literal === 'ACTIVE') return CatalogStatus.ACTIVE;
  if (literal === 'DEPRECATED') return CatalogStatus.DEPRECATED;
  return undefined;
}
