/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * CollectionType
 * @generated
 */
export const CollectionType = {
  SERVICE: 'SERVICE',
  REFERENCE: 'REFERENCE',
  SERVICEOBJECTS: 'SERVICEOBJECTS',
  PROPERTIES: 'PROPERTIES',
  TUPLE: 'TUPLE'
} as const;

export type CollectionType = typeof CollectionType[keyof typeof CollectionType];

/**
 * Get enum value by name
 */
export function getCollectionType(name: string): CollectionType | undefined {
  return (CollectionType as Record<string, string>)[name] as CollectionType | undefined;
}

/**
 * Get enum value by literal
 */
export function getCollectionTypeByLiteral(literal: string): CollectionType | undefined {
  if (literal === 'SERVICE') return CollectionType.SERVICE;
  if (literal === 'REFERENCE') return CollectionType.REFERENCE;
  if (literal === 'SERVICEOBJECTS') return CollectionType.SERVICEOBJECTS;
  if (literal === 'PROPERTIES') return CollectionType.PROPERTIES;
  if (literal === 'TUPLE') return CollectionType.TUPLE;
  return undefined;
}
