/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { ComponentDescription } from './ComponentDescription.js';
import type { ComponentState } from './ComponentState.js';
import type { Property } from './Property.js';
import type { SatisfiedReference } from './SatisfiedReference.js';
import type { UnsatisfiedReference } from './UnsatisfiedReference.js';
import type { Diagnostic } from './Diagnostic.js';
import type { ServiceReference } from './ServiceReference.js';

/**
 * ComponentConfiguration
 * @generated
 */
export interface ComponentConfiguration extends NamedElement {
  id: string;
  description: ComponentDescription;
  state: ComponentState;
  properties: EList<Property>;
  satisfiedReferences: EList<SatisfiedReference>;
  unsatisfiedReferences: EList<UnsatisfiedReference>;
  failure?: Diagnostic;
  service?: ServiceReference;

}
