/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { ComponentDescription } from './ComponentDescription';
import type { ComponentState } from './ComponentState';
import type { Property } from './Property';
import type { SatisfiedReference } from './SatisfiedReference';
import type { UnsatisfiedReference } from './UnsatisfiedReference';
import type { Diagnostic } from './Diagnostic';
import type { ServiceReference } from './ServiceReference';

/**
 * ComponentConfiguration
 * @generated
 */
export interface ComponentConfiguration extends NamedElement {
  id: string;
  description: ComponentDescription;
  state: ComponentState;
  properties: Property[];
  satisfiedReferences: SatisfiedReference[];
  unsatisfiedReferences: UnsatisfiedReference[];
  failure?: Diagnostic;
  service?: ServiceReference;

}
