/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { CollectionType } from './CollectionType';
import type { ReferenceBinding } from './ReferenceBinding';
import { ReferenceCardinality } from './ReferenceCardinality';
import { ReferencePolicy } from './ReferencePolicy';
import { ReferencePolicyOption } from './ReferencePolicyOption';
import { ServiceScope } from './ServiceScope';
import type { ComponentReference } from './ComponentReference';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ComponentReference
 * @generated
 */
export class ComponentReferenceImpl extends BasicEObject implements ComponentReference {
  // Feature ID Constants (eLiterals)
  static readonly INTERFACE_NAME: number = 1;
  static readonly CARDINALITY: number = 2;
  static readonly POLICY: number = 3;
  static readonly POLICY_OPTION: number = 4;
  static readonly TARGET: number = 5;
  static readonly SCOPE: number = 6;
  static readonly COLLECTION_TYPE: number = 7;
  static readonly PARAMETER: number = 8;
  static readonly BINDINGS: number = 9;
  static readonly NAME: number = 0;

  // Private fields
  private _interfaceName: string = "";
  private _cardinality: ReferenceCardinality = ReferenceCardinality.ONE;
  private _policy: ReferencePolicy = ReferencePolicy.STATIC;
  private _policyOption: ReferencePolicyOption = ReferencePolicyOption.RELUCTANT;
  private _target?: string;
  private _scope: ServiceScope = ServiceScope.BUNDLE;
  private _collectionType?: CollectionType;
  private _parameter?: number;
  private _bindings: ReferenceBinding[] = [];
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.COMPONENT_REFERENCE;
  }

  // Getters and Setters
  get interfaceName(): string {
    return this._interfaceName!;
  }

  set interfaceName(value: string) {
    const oldValue = this._interfaceName;
    this._interfaceName = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentReferenceImpl.INTERFACE_NAME),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentReferenceImpl.INTERFACE_NAME,
        merge: () => false
      });
    }
  }

  get cardinality(): ReferenceCardinality {
    return this._cardinality!;
  }

  set cardinality(value: ReferenceCardinality) {
    const oldValue = this._cardinality;
    this._cardinality = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentReferenceImpl.CARDINALITY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentReferenceImpl.CARDINALITY,
        merge: () => false
      });
    }
  }

  get policy(): ReferencePolicy {
    return this._policy!;
  }

  set policy(value: ReferencePolicy) {
    const oldValue = this._policy;
    this._policy = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentReferenceImpl.POLICY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentReferenceImpl.POLICY,
        merge: () => false
      });
    }
  }

  get policyOption(): ReferencePolicyOption {
    return this._policyOption!;
  }

  set policyOption(value: ReferencePolicyOption) {
    const oldValue = this._policyOption;
    this._policyOption = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentReferenceImpl.POLICY_OPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentReferenceImpl.POLICY_OPTION,
        merge: () => false
      });
    }
  }

  get target(): string {
    return this._target!;
  }

  set target(value: string) {
    const oldValue = this._target;
    this._target = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentReferenceImpl.TARGET),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentReferenceImpl.TARGET,
        merge: () => false
      });
    }
  }

  get scope(): ServiceScope {
    return this._scope!;
  }

  set scope(value: ServiceScope) {
    const oldValue = this._scope;
    this._scope = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentReferenceImpl.SCOPE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentReferenceImpl.SCOPE,
        merge: () => false
      });
    }
  }

  get collectionType(): CollectionType {
    return this._collectionType!;
  }

  set collectionType(value: CollectionType) {
    const oldValue = this._collectionType;
    this._collectionType = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentReferenceImpl.COLLECTION_TYPE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentReferenceImpl.COLLECTION_TYPE,
        merge: () => false
      });
    }
  }

  get parameter(): number {
    return this._parameter!;
  }

  set parameter(value: number) {
    const oldValue = this._parameter;
    this._parameter = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentReferenceImpl.PARAMETER),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentReferenceImpl.PARAMETER,
        merge: () => false
      });
    }
  }

  get bindings(): ReferenceBinding[] {
    return this._bindings;
  }

  set bindings(value: ReferenceBinding[]) {
    const oldValue = this._bindings;
    this._bindings = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentReferenceImpl.BINDINGS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentReferenceImpl.BINDINGS,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentReferenceImpl.INTERFACE_NAME:
        return this.interfaceName;
      case ComponentReferenceImpl.CARDINALITY:
        return this.cardinality;
      case ComponentReferenceImpl.POLICY:
        return this.policy;
      case ComponentReferenceImpl.POLICY_OPTION:
        return this.policyOption;
      case ComponentReferenceImpl.TARGET:
        return this.target;
      case ComponentReferenceImpl.SCOPE:
        return this.scope;
      case ComponentReferenceImpl.COLLECTION_TYPE:
        return this.collectionType;
      case ComponentReferenceImpl.PARAMETER:
        return this.parameter;
      case ComponentReferenceImpl.BINDINGS:
        return this.bindings;
      case ComponentReferenceImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentReferenceImpl.INTERFACE_NAME:
        this.interfaceName = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ComponentReferenceImpl.CARDINALITY:
        this.cardinality = newValue as ReferenceCardinality;
        super.eSet(feature, newValue);
        break;
      case ComponentReferenceImpl.POLICY:
        this.policy = newValue as ReferencePolicy;
        super.eSet(feature, newValue);
        break;
      case ComponentReferenceImpl.POLICY_OPTION:
        this.policyOption = newValue as ReferencePolicyOption;
        super.eSet(feature, newValue);
        break;
      case ComponentReferenceImpl.TARGET:
        this.target = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ComponentReferenceImpl.SCOPE:
        this.scope = newValue as ServiceScope;
        super.eSet(feature, newValue);
        break;
      case ComponentReferenceImpl.COLLECTION_TYPE:
        this.collectionType = newValue as CollectionType;
        super.eSet(feature, newValue);
        break;
      case ComponentReferenceImpl.PARAMETER:
        this.parameter = newValue as number;
        super.eSet(feature, newValue);
        break;
      case ComponentReferenceImpl.BINDINGS:
        this.bindings = newValue as ReferenceBinding[];
        super.eSet(feature, newValue);
        break;
      case ComponentReferenceImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentReferenceImpl.INTERFACE_NAME:
        return this._interfaceName !== "";
      case ComponentReferenceImpl.CARDINALITY:
        return this._cardinality !== ReferenceCardinality.ONE;
      case ComponentReferenceImpl.POLICY:
        return this._policy !== ReferencePolicy.STATIC;
      case ComponentReferenceImpl.POLICY_OPTION:
        return this._policyOption !== ReferencePolicyOption.RELUCTANT;
      case ComponentReferenceImpl.TARGET:
        return this._target !== undefined;
      case ComponentReferenceImpl.SCOPE:
        return this._scope !== ServiceScope.BUNDLE;
      case ComponentReferenceImpl.COLLECTION_TYPE:
        return this._collectionType !== undefined;
      case ComponentReferenceImpl.PARAMETER:
        return this._parameter !== undefined;
      case ComponentReferenceImpl.BINDINGS:
        return this._bindings !== undefined && this._bindings.length > 0;
      case ComponentReferenceImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentReferenceImpl.INTERFACE_NAME:
        this._interfaceName = "";
        return;
      case ComponentReferenceImpl.CARDINALITY:
        this._cardinality = ReferenceCardinality.ONE;
        return;
      case ComponentReferenceImpl.POLICY:
        this._policy = ReferencePolicy.STATIC;
        return;
      case ComponentReferenceImpl.POLICY_OPTION:
        this._policyOption = ReferencePolicyOption.RELUCTANT;
        return;
      case ComponentReferenceImpl.TARGET:
        this._target = undefined;
        return;
      case ComponentReferenceImpl.SCOPE:
        this._scope = ServiceScope.BUNDLE;
        return;
      case ComponentReferenceImpl.COLLECTION_TYPE:
        this._collectionType = undefined;
        return;
      case ComponentReferenceImpl.PARAMETER:
        this._parameter = undefined;
        return;
      case ComponentReferenceImpl.BINDINGS:
        this._bindings = [];
        return;
      case ComponentReferenceImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
