/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { ComponentDescription } from './ComponentDescription.js';
import type { Property } from './Property.js';
import type { SatisfiedReference } from './SatisfiedReference.js';
import type { UnsatisfiedReference } from './UnsatisfiedReference.js';
import type { Diagnostic } from './Diagnostic.js';
import type { ServiceReference } from './ServiceReference.js';
import { ComponentState } from './ComponentState.js';
import type { ComponentConfiguration } from './ComponentConfiguration.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ComponentConfiguration
 * @generated
 */
export class ComponentConfigurationImpl extends BasicEObject implements ComponentConfiguration {
  // Feature ID Constants (eLiterals)
  static readonly ID: number = 1;
  static readonly DESCRIPTION: number = 2;
  static readonly STATE: number = 3;
  static readonly PROPERTIES: number = 4;
  static readonly SATISFIED_REFERENCES: number = 5;
  static readonly UNSATISFIED_REFERENCES: number = 6;
  static readonly FAILURE: number = 7;
  static readonly SERVICE: number = 8;
  static readonly NAME: number = 0;

  // Private fields
  private _id: string = "";
  private _description?: ComponentDescription;
  private _state: ComponentState = ComponentState.UNSATISFIED_CONFIGURATION;
  private _properties!: EList<Property>;
  private _satisfiedReferences!: EList<SatisfiedReference>;
  private _unsatisfiedReferences!: EList<UnsatisfiedReference>;
  private _failure?: Diagnostic;
  private _service?: ServiceReference;
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.COMPONENT_CONFIGURATION;
  }

  // Getters and Setters
  get id(): string {
    return this._id!;
  }

  set id(value: string) {
    const oldValue = this._id;
    this._id = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentConfigurationImpl.ID),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentConfigurationImpl.ID,
        merge: () => false
      });
    }
  }

  get description(): ComponentDescription {
    return this._description!;
  }

  set description(value: ComponentDescription) {
    const oldValue = this._description;
    this._description = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentConfigurationImpl.DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentConfigurationImpl.DESCRIPTION,
        merge: () => false
      });
    }
  }

  get state(): ComponentState {
    return this._state!;
  }

  set state(value: ComponentState) {
    const oldValue = this._state;
    this._state = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentConfigurationImpl.STATE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentConfigurationImpl.STATE,
        merge: () => false
      });
    }
  }

  get properties(): EList<Property> {
    if (!this._properties) {
      this._properties = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('properties') as EReference);
    }
    return this._properties;
  }

  get satisfiedReferences(): EList<SatisfiedReference> {
    if (!this._satisfiedReferences) {
      this._satisfiedReferences = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('satisfiedReferences') as EReference);
    }
    return this._satisfiedReferences;
  }

  get unsatisfiedReferences(): EList<UnsatisfiedReference> {
    if (!this._unsatisfiedReferences) {
      this._unsatisfiedReferences = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('unsatisfiedReferences') as EReference);
    }
    return this._unsatisfiedReferences;
  }

  get failure(): Diagnostic {
    return this._failure!;
  }

  set failure(value: Diagnostic) {
    const oldValue = this._failure;
    this._failure = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentConfigurationImpl.FAILURE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentConfigurationImpl.FAILURE,
        merge: () => false
      });
    }
  }

  get service(): ServiceReference {
    return this._service!;
  }

  set service(value: ServiceReference) {
    const oldValue = this._service;
    this._service = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentConfigurationImpl.SERVICE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentConfigurationImpl.SERVICE,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentConfigurationImpl.ID:
        return this.id;
      case ComponentConfigurationImpl.DESCRIPTION:
        return this.description;
      case ComponentConfigurationImpl.STATE:
        return this.state;
      case ComponentConfigurationImpl.PROPERTIES:
        return this.properties;
      case ComponentConfigurationImpl.SATISFIED_REFERENCES:
        return this.satisfiedReferences;
      case ComponentConfigurationImpl.UNSATISFIED_REFERENCES:
        return this.unsatisfiedReferences;
      case ComponentConfigurationImpl.FAILURE:
        return this.failure;
      case ComponentConfigurationImpl.SERVICE:
        return this.service;
      case ComponentConfigurationImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentConfigurationImpl.ID:
        this.id = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ComponentConfigurationImpl.DESCRIPTION:
        this.description = newValue as ComponentDescription;
        super.eSet(feature, newValue);
        break;
      case ComponentConfigurationImpl.STATE:
        this.state = newValue as ComponentState;
        super.eSet(feature, newValue);
        break;
      case ComponentConfigurationImpl.PROPERTIES:
        this.properties.clear();
        this.properties.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ComponentConfigurationImpl.SATISFIED_REFERENCES:
        this.satisfiedReferences.clear();
        this.satisfiedReferences.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ComponentConfigurationImpl.UNSATISFIED_REFERENCES:
        this.unsatisfiedReferences.clear();
        this.unsatisfiedReferences.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ComponentConfigurationImpl.FAILURE:
        this.failure = newValue as Diagnostic;
        super.eSet(feature, newValue);
        break;
      case ComponentConfigurationImpl.SERVICE:
        this.service = newValue as ServiceReference;
        super.eSet(feature, newValue);
        break;
      case ComponentConfigurationImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentConfigurationImpl.ID:
        return this._id !== "";
      case ComponentConfigurationImpl.DESCRIPTION:
        return this._description !== undefined;
      case ComponentConfigurationImpl.STATE:
        return this._state !== ComponentState.UNSATISFIED_CONFIGURATION;
      case ComponentConfigurationImpl.PROPERTIES:
        return this._properties !== undefined && !this._properties.isEmpty();
      case ComponentConfigurationImpl.SATISFIED_REFERENCES:
        return this._satisfiedReferences !== undefined && !this._satisfiedReferences.isEmpty();
      case ComponentConfigurationImpl.UNSATISFIED_REFERENCES:
        return this._unsatisfiedReferences !== undefined && !this._unsatisfiedReferences.isEmpty();
      case ComponentConfigurationImpl.FAILURE:
        return this._failure !== undefined;
      case ComponentConfigurationImpl.SERVICE:
        return this._service !== undefined;
      case ComponentConfigurationImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentConfigurationImpl.ID:
        this._id = "";
        return;
      case ComponentConfigurationImpl.DESCRIPTION:
        this._description = undefined;
        return;
      case ComponentConfigurationImpl.STATE:
        this._state = ComponentState.UNSATISFIED_CONFIGURATION;
        return;
      case ComponentConfigurationImpl.PROPERTIES:
        if (this._properties) this._properties.clear();
        return;
      case ComponentConfigurationImpl.SATISFIED_REFERENCES:
        if (this._satisfiedReferences) this._satisfiedReferences.clear();
        return;
      case ComponentConfigurationImpl.UNSATISFIED_REFERENCES:
        if (this._unsatisfiedReferences) this._unsatisfiedReferences.clear();
        return;
      case ComponentConfigurationImpl.FAILURE:
        this._failure = undefined;
        return;
      case ComponentConfigurationImpl.SERVICE:
        this._service = undefined;
        return;
      case ComponentConfigurationImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
