/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList, createEObjectEList, createBasicEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { ServiceInterface } from './ServiceInterface.js';
import type { Property } from './Property.js';
import type { ComponentReference } from './ComponentReference.js';
import type { LifecycleHook } from './LifecycleHook.js';
import type { ServiceProvider } from './ServiceProvider.js';
import { ServiceScope } from './ServiceScope.js';
import { ConfigurationPolicy } from './ConfigurationPolicy.js';
import type { ComponentDescription } from './ComponentDescription.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ComponentDescription
 * @generated
 */
export class ComponentDescriptionImpl extends BasicEObject implements ComponentDescription {
  // Feature ID Constants (eLiterals)
  static readonly FACTORY: number = 1;
  static readonly SCOPE: number = 2;
  static readonly IMPLEMENTATION_ID: number = 3;
  static readonly DEFAULT_ENABLED: number = 4;
  static readonly IMMEDIATE: number = 5;
  static readonly CONFIGURATION_POLICY: number = 6;
  static readonly CONFIGURATION_PID: number = 7;
  static readonly SERVICE_INTERFACES: number = 8;
  static readonly PROPERTIES: number = 9;
  static readonly FACTORY_PROPERTIES: number = 10;
  static readonly REFERENCES: number = 11;
  static readonly LIFECYCLE_HOOKS: number = 12;
  static readonly PROVIDER: number = 13;
  static readonly NAME: number = 0;

  // Private fields
  private _factory?: string;
  private _scope: ServiceScope = ServiceScope.SINGLETON;
  private _implementationId: string = "";
  private _defaultEnabled: boolean = true;
  private _immediate: boolean = false;
  private _configurationPolicy: ConfigurationPolicy = ConfigurationPolicy.OPTIONAL;
  private _configurationPid!: EList<string>;
  private _serviceInterfaces!: EList<ServiceInterface>;
  private _properties!: EList<Property>;
  private _factoryProperties!: EList<Property>;
  private _references!: EList<ComponentReference>;
  private _lifecycleHooks!: EList<LifecycleHook>;
  private _provider?: ServiceProvider;
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.COMPONENT_DESCRIPTION;
  }

  // Getters and Setters
  get factory(): string {
    return this._factory!;
  }

  set factory(value: string) {
    const oldValue = this._factory;
    this._factory = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentDescriptionImpl.FACTORY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentDescriptionImpl.FACTORY,
        merge: () => false
      });
    }
  }

  get scope(): ServiceScope {
    return this._scope!;
  }

  set scope(value: ServiceScope) {
    const oldValue = this._scope;
    this._scope = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentDescriptionImpl.SCOPE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentDescriptionImpl.SCOPE,
        merge: () => false
      });
    }
  }

  get implementationId(): string {
    return this._implementationId!;
  }

  set implementationId(value: string) {
    const oldValue = this._implementationId;
    this._implementationId = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentDescriptionImpl.IMPLEMENTATION_ID),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentDescriptionImpl.IMPLEMENTATION_ID,
        merge: () => false
      });
    }
  }

  get defaultEnabled(): boolean {
    return this._defaultEnabled!;
  }

  set defaultEnabled(value: boolean) {
    const oldValue = this._defaultEnabled;
    this._defaultEnabled = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentDescriptionImpl.DEFAULT_ENABLED),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentDescriptionImpl.DEFAULT_ENABLED,
        merge: () => false
      });
    }
  }

  get immediate(): boolean {
    return this._immediate!;
  }

  set immediate(value: boolean) {
    const oldValue = this._immediate;
    this._immediate = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentDescriptionImpl.IMMEDIATE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentDescriptionImpl.IMMEDIATE,
        merge: () => false
      });
    }
  }

  get configurationPolicy(): ConfigurationPolicy {
    return this._configurationPolicy!;
  }

  set configurationPolicy(value: ConfigurationPolicy) {
    const oldValue = this._configurationPolicy;
    this._configurationPolicy = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentDescriptionImpl.CONFIGURATION_POLICY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentDescriptionImpl.CONFIGURATION_POLICY,
        merge: () => false
      });
    }
  }

  get configurationPid(): EList<string> {
    if (!this._configurationPid) {
      this._configurationPid = createBasicEList<any>(this, this.eClass().getEStructuralFeature('configurationPid')!);
    }
    return this._configurationPid;
  }

  get serviceInterfaces(): EList<ServiceInterface> {
    if (!this._serviceInterfaces) {
      this._serviceInterfaces = createEObjectEList(this, this.eClass().getEStructuralFeature('serviceInterfaces') as EReference) as unknown as EList<ServiceInterface>;
    }
    return this._serviceInterfaces;
  }

  get properties(): EList<Property> {
    if (!this._properties) {
      this._properties = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('properties') as EReference);
    }
    return this._properties;
  }

  get factoryProperties(): EList<Property> {
    if (!this._factoryProperties) {
      this._factoryProperties = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('factoryProperties') as EReference);
    }
    return this._factoryProperties;
  }

  get references(): EList<ComponentReference> {
    if (!this._references) {
      this._references = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('references') as EReference);
    }
    return this._references;
  }

  get lifecycleHooks(): EList<LifecycleHook> {
    if (!this._lifecycleHooks) {
      this._lifecycleHooks = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('lifecycleHooks') as EReference);
    }
    return this._lifecycleHooks;
  }

  get provider(): ServiceProvider {
    return this._provider!;
  }

  set provider(value: ServiceProvider) {
    const oldValue = this._provider;
    this._provider = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ComponentDescriptionImpl.PROVIDER),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ComponentDescriptionImpl.PROVIDER,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentDescriptionImpl.FACTORY:
        return this.factory;
      case ComponentDescriptionImpl.SCOPE:
        return this.scope;
      case ComponentDescriptionImpl.IMPLEMENTATION_ID:
        return this.implementationId;
      case ComponentDescriptionImpl.DEFAULT_ENABLED:
        return this.defaultEnabled;
      case ComponentDescriptionImpl.IMMEDIATE:
        return this.immediate;
      case ComponentDescriptionImpl.CONFIGURATION_POLICY:
        return this.configurationPolicy;
      case ComponentDescriptionImpl.CONFIGURATION_PID:
        return this.configurationPid;
      case ComponentDescriptionImpl.SERVICE_INTERFACES:
        return this.serviceInterfaces;
      case ComponentDescriptionImpl.PROPERTIES:
        return this.properties;
      case ComponentDescriptionImpl.FACTORY_PROPERTIES:
        return this.factoryProperties;
      case ComponentDescriptionImpl.REFERENCES:
        return this.references;
      case ComponentDescriptionImpl.LIFECYCLE_HOOKS:
        return this.lifecycleHooks;
      case ComponentDescriptionImpl.PROVIDER:
        return this.provider;
      case ComponentDescriptionImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentDescriptionImpl.FACTORY:
        this.factory = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.SCOPE:
        this.scope = newValue as ServiceScope;
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.IMPLEMENTATION_ID:
        this.implementationId = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.DEFAULT_ENABLED:
        this.defaultEnabled = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.IMMEDIATE:
        this.immediate = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.CONFIGURATION_POLICY:
        this.configurationPolicy = newValue as ConfigurationPolicy;
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.CONFIGURATION_PID:
        this.configurationPid.clear();
        this.configurationPid.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.SERVICE_INTERFACES:
        this.serviceInterfaces.clear();
        this.serviceInterfaces.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.PROPERTIES:
        this.properties.clear();
        this.properties.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.FACTORY_PROPERTIES:
        this.factoryProperties.clear();
        this.factoryProperties.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.REFERENCES:
        this.references.clear();
        this.references.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.LIFECYCLE_HOOKS:
        this.lifecycleHooks.clear();
        this.lifecycleHooks.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.PROVIDER:
        this.provider = newValue as ServiceProvider;
        super.eSet(feature, newValue);
        break;
      case ComponentDescriptionImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentDescriptionImpl.FACTORY:
        return this._factory !== undefined;
      case ComponentDescriptionImpl.SCOPE:
        return this._scope !== ServiceScope.SINGLETON;
      case ComponentDescriptionImpl.IMPLEMENTATION_ID:
        return this._implementationId !== "";
      case ComponentDescriptionImpl.DEFAULT_ENABLED:
        return this._defaultEnabled !== true;
      case ComponentDescriptionImpl.IMMEDIATE:
        return this._immediate !== false;
      case ComponentDescriptionImpl.CONFIGURATION_POLICY:
        return this._configurationPolicy !== ConfigurationPolicy.OPTIONAL;
      case ComponentDescriptionImpl.CONFIGURATION_PID:
        return this._configurationPid !== undefined && !this._configurationPid.isEmpty();
      case ComponentDescriptionImpl.SERVICE_INTERFACES:
        return this._serviceInterfaces !== undefined && !this._serviceInterfaces.isEmpty();
      case ComponentDescriptionImpl.PROPERTIES:
        return this._properties !== undefined && !this._properties.isEmpty();
      case ComponentDescriptionImpl.FACTORY_PROPERTIES:
        return this._factoryProperties !== undefined && !this._factoryProperties.isEmpty();
      case ComponentDescriptionImpl.REFERENCES:
        return this._references !== undefined && !this._references.isEmpty();
      case ComponentDescriptionImpl.LIFECYCLE_HOOKS:
        return this._lifecycleHooks !== undefined && !this._lifecycleHooks.isEmpty();
      case ComponentDescriptionImpl.PROVIDER:
        return this._provider !== undefined;
      case ComponentDescriptionImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ComponentDescriptionImpl.FACTORY:
        this._factory = undefined;
        return;
      case ComponentDescriptionImpl.SCOPE:
        this._scope = ServiceScope.SINGLETON;
        return;
      case ComponentDescriptionImpl.IMPLEMENTATION_ID:
        this._implementationId = "";
        return;
      case ComponentDescriptionImpl.DEFAULT_ENABLED:
        this._defaultEnabled = true;
        return;
      case ComponentDescriptionImpl.IMMEDIATE:
        this._immediate = false;
        return;
      case ComponentDescriptionImpl.CONFIGURATION_POLICY:
        this._configurationPolicy = ConfigurationPolicy.OPTIONAL;
        return;
      case ComponentDescriptionImpl.CONFIGURATION_PID:
        if (this._configurationPid) this._configurationPid.clear();
        return;
      case ComponentDescriptionImpl.SERVICE_INTERFACES:
        if (this._serviceInterfaces) this._serviceInterfaces.clear();
        return;
      case ComponentDescriptionImpl.PROPERTIES:
        if (this._properties) this._properties.clear();
        return;
      case ComponentDescriptionImpl.FACTORY_PROPERTIES:
        if (this._factoryProperties) this._factoryProperties.clear();
        return;
      case ComponentDescriptionImpl.REFERENCES:
        if (this._references) this._references.clear();
        return;
      case ComponentDescriptionImpl.LIFECYCLE_HOOKS:
        if (this._lifecycleHooks) this._lifecycleHooks.clear();
        return;
      case ComponentDescriptionImpl.PROVIDER:
        this._provider = undefined;
        return;
      case ComponentDescriptionImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
