/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { ReferenceCardinality } from './ReferenceCardinality';
import type { ReferencePolicy } from './ReferencePolicy';
import type { ReferencePolicyOption } from './ReferencePolicyOption';
import type { ServiceScope } from './ServiceScope';
import type { CollectionType } from './CollectionType';
import type { ReferenceBinding } from './ReferenceBinding';

/**
 * ComponentReference
 * @generated
 */
export interface ComponentReference extends NamedElement {
  interfaceName: string;
  cardinality: ReferenceCardinality;
  policy: ReferencePolicy;
  policyOption: ReferencePolicyOption;
  target?: string;
  scope: ServiceScope;
  collectionType?: CollectionType;
  parameter?: number;
  bindings: ReferenceBinding[];

}
