/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { ServiceScope } from './ServiceScope';
import type { ConfigurationPolicy } from './ConfigurationPolicy';
import type { ServiceInterface } from './ServiceInterface';
import type { Property } from './Property';
import type { ComponentReference } from './ComponentReference';
import type { LifecycleHook } from './LifecycleHook';
import type { ServiceProvider } from './ServiceProvider';

/**
 * ComponentDescription
 * @generated
 */
export interface ComponentDescription extends NamedElement {
  factory?: string;
  scope: ServiceScope;
  implementationId: string;
  defaultEnabled: boolean;
  immediate: boolean;
  configurationPolicy: ConfigurationPolicy;
  configurationPid: string[];
  serviceInterfaces: ServiceInterface[];
  properties: Property[];
  factoryProperties: Property[];
  references: ComponentReference[];
  lifecycleHooks: LifecycleHook[];
  provider?: ServiceProvider;

}
