/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ConfigurationPolicy
 * @generated
 */
export const ConfigurationPolicy = {
  OPTIONAL: 'OPTIONAL',
  REQUIRE: 'REQUIRE',
  IGNORE: 'IGNORE'
} as const;

export type ConfigurationPolicy = typeof ConfigurationPolicy[keyof typeof ConfigurationPolicy];

/**
 * Get enum value by name
 */
export function getConfigurationPolicy(name: string): ConfigurationPolicy | undefined {
  return (ConfigurationPolicy as Record<string, string>)[name] as ConfigurationPolicy | undefined;
}

/**
 * Get enum value by literal
 */
export function getConfigurationPolicyByLiteral(literal: string): ConfigurationPolicy | undefined {
  if (literal === 'OPTIONAL') return ConfigurationPolicy.OPTIONAL;
  if (literal === 'REQUIRE') return ConfigurationPolicy.REQUIRE;
  if (literal === 'IGNORE') return ConfigurationPolicy.IGNORE;
  return undefined;
}
