/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ConnectionState
 * @generated
 */
export const ConnectionState = {
  CONNECTED: 'CONNECTED',
  DEGRADED: 'DEGRADED',
  OFFLINE: 'OFFLINE'
} as const;

export type ConnectionState = typeof ConnectionState[keyof typeof ConnectionState];

/**
 * Get enum value by name
 */
export function getConnectionState(name: string): ConnectionState | undefined {
  return (ConnectionState as Record<string, string>)[name] as ConnectionState | undefined;
}

/**
 * Get enum value by literal
 */
export function getConnectionStateByLiteral(literal: string): ConnectionState | undefined {
  if (literal === 'CONNECTED') return ConnectionState.CONNECTED;
  if (literal === 'DEGRADED') return ConnectionState.DEGRADED;
  if (literal === 'OFFLINE') return ConnectionState.OFFLINE;
  return undefined;
}
