/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList, createBasicEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { FlavorKind } from './FlavorKind.js';
import type { Property } from './Property.js';
import type { Requirement } from './Requirement.js';
import type { ConsumerCapability } from './ConsumerCapability.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ConsumerCapability
 * @generated
 */
export class ConsumerCapabilityImpl extends BasicEObject implements ConsumerCapability {
  // Feature ID Constants (eLiterals)
  static readonly CONSUMER_ID: number = 0;
  static readonly SUPPORTED_FLAVORS: number = 1;
  static readonly PROPERTIES: number = 2;
  static readonly REQUIREMENTS: number = 3;

  // Private fields
  private _consumerId?: string;
  private _supportedFlavors!: EList<FlavorKind>;
  private _properties!: EList<Property>;
  private _requirements!: EList<Requirement>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.CONSUMER_CAPABILITY;
  }

  // Getters and Setters
  get consumerId(): string {
    return this._consumerId!;
  }

  set consumerId(value: string) {
    const oldValue = this._consumerId;
    this._consumerId = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ConsumerCapabilityImpl.CONSUMER_ID),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ConsumerCapabilityImpl.CONSUMER_ID,
        merge: () => false
      });
    }
  }

  get supportedFlavors(): EList<FlavorKind> {
    if (!this._supportedFlavors) {
      this._supportedFlavors = createBasicEList<any>(this, this.eClass().getEStructuralFeature('supportedFlavors')!);
    }
    return this._supportedFlavors;
  }

  get properties(): EList<Property> {
    if (!this._properties) {
      this._properties = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('properties') as EReference);
    }
    return this._properties;
  }

  get requirements(): EList<Requirement> {
    if (!this._requirements) {
      this._requirements = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('requirements') as EReference);
    }
    return this._requirements;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ConsumerCapabilityImpl.CONSUMER_ID:
        return this.consumerId;
      case ConsumerCapabilityImpl.SUPPORTED_FLAVORS:
        return this.supportedFlavors;
      case ConsumerCapabilityImpl.PROPERTIES:
        return this.properties;
      case ConsumerCapabilityImpl.REQUIREMENTS:
        return this.requirements;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ConsumerCapabilityImpl.CONSUMER_ID:
        this.consumerId = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ConsumerCapabilityImpl.SUPPORTED_FLAVORS:
        this.supportedFlavors.clear();
        this.supportedFlavors.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ConsumerCapabilityImpl.PROPERTIES:
        this.properties.clear();
        this.properties.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ConsumerCapabilityImpl.REQUIREMENTS:
        this.requirements.clear();
        this.requirements.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ConsumerCapabilityImpl.CONSUMER_ID:
        return this._consumerId !== undefined;
      case ConsumerCapabilityImpl.SUPPORTED_FLAVORS:
        return this._supportedFlavors !== undefined && !this._supportedFlavors.isEmpty();
      case ConsumerCapabilityImpl.PROPERTIES:
        return this._properties !== undefined && !this._properties.isEmpty();
      case ConsumerCapabilityImpl.REQUIREMENTS:
        return this._requirements !== undefined && !this._requirements.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ConsumerCapabilityImpl.CONSUMER_ID:
        this._consumerId = undefined;
        return;
      case ConsumerCapabilityImpl.SUPPORTED_FLAVORS:
        if (this._supportedFlavors) this._supportedFlavors.clear();
        return;
      case ConsumerCapabilityImpl.PROPERTIES:
        if (this._properties) this._properties.clear();
        return;
      case ConsumerCapabilityImpl.REQUIREMENTS:
        if (this._requirements) this._requirements.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

}
