/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ConsumerCapability } from './ConsumerCapability';
import type { ServiceRegistration } from './ServiceRegistration';

/**
 * ConsumerSession
 * @generated
 */
export interface ConsumerSession extends EObject {
  consumerId: string;
  lastRenewal?: Date;
  capabilities?: ConsumerCapability;
  acquisitions: ServiceRegistration[];

}
