/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { FlavorKind } from './FlavorKind';
import type { Property } from './Property';

/**
 * ConsumerCapability
 * @generated
 */
export interface ConsumerCapability extends EObject {
  consumerId?: string;
  supportedFlavors: FlavorKind[];
  properties: Property[];

}
