/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { FlavorKind } from './FlavorKind';
import type { Property } from './Property';
import type { ConsumerCapability } from './ConsumerCapability';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ConsumerCapability
 * @generated
 */
export class ConsumerCapabilityImpl extends BasicEObject implements ConsumerCapability {
  // Feature ID Constants (eLiterals)
  static readonly CONSUMER_ID: number = 0;
  static readonly SUPPORTED_FLAVORS: number = 1;
  static readonly PROPERTIES: number = 2;

  // Private fields
  private _consumerId?: string;
  private _supportedFlavors: FlavorKind[] = [];
  private _properties: Property[] = [];

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.CONSUMER_CAPABILITY;
  }

  // Getters and Setters
  get consumerId(): string {
    return this._consumerId!;
  }

  set consumerId(value: string) {
    const oldValue = this._consumerId;
    this._consumerId = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ConsumerCapabilityImpl.CONSUMER_ID),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ConsumerCapabilityImpl.CONSUMER_ID,
        merge: () => false
      });
    }
  }

  get supportedFlavors(): FlavorKind[] {
    return this._supportedFlavors;
  }

  set supportedFlavors(value: FlavorKind[]) {
    const oldValue = this._supportedFlavors;
    this._supportedFlavors = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ConsumerCapabilityImpl.SUPPORTED_FLAVORS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ConsumerCapabilityImpl.SUPPORTED_FLAVORS,
        merge: () => false
      });
    }
  }

  get properties(): Property[] {
    return this._properties;
  }

  set properties(value: Property[]) {
    const oldValue = this._properties;
    this._properties = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ConsumerCapabilityImpl.PROPERTIES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ConsumerCapabilityImpl.PROPERTIES,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ConsumerCapabilityImpl.CONSUMER_ID:
        return this.consumerId;
      case ConsumerCapabilityImpl.SUPPORTED_FLAVORS:
        return this.supportedFlavors;
      case ConsumerCapabilityImpl.PROPERTIES:
        return this.properties;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ConsumerCapabilityImpl.CONSUMER_ID:
        this.consumerId = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ConsumerCapabilityImpl.SUPPORTED_FLAVORS:
        this.supportedFlavors = newValue as FlavorKind[];
        super.eSet(feature, newValue);
        break;
      case ConsumerCapabilityImpl.PROPERTIES:
        this.properties = newValue as Property[];
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ConsumerCapabilityImpl.CONSUMER_ID:
        return this._consumerId !== undefined;
      case ConsumerCapabilityImpl.SUPPORTED_FLAVORS:
        return this._supportedFlavors !== undefined && this._supportedFlavors.length > 0;
      case ConsumerCapabilityImpl.PROPERTIES:
        return this._properties !== undefined && this._properties.length > 0;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ConsumerCapabilityImpl.CONSUMER_ID:
        this._consumerId = undefined;
        return;
      case ConsumerCapabilityImpl.SUPPORTED_FLAVORS:
        this._supportedFlavors = [];
        return;
      case ConsumerCapabilityImpl.PROPERTIES:
        this._properties = [];
        return;
      default:
        super.eUnset(feature);
    }
  }

}
