/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEFactory } from '@emfts/core';
import type { EClass, EObject } from '@emfts/core';
import { DDSRPackage } from './DDSRPackage.js';
import type { StringProperty } from './StringProperty.js';
import { StringPropertyImpl } from './StringPropertyImpl.js';
import type { IntProperty } from './IntProperty.js';
import { IntPropertyImpl } from './IntPropertyImpl.js';
import type { LongProperty } from './LongProperty.js';
import { LongPropertyImpl } from './LongPropertyImpl.js';
import type { DoubleProperty } from './DoubleProperty.js';
import { DoublePropertyImpl } from './DoublePropertyImpl.js';
import type { FloatProperty } from './FloatProperty.js';
import { FloatPropertyImpl } from './FloatPropertyImpl.js';
import type { ShortProperty } from './ShortProperty.js';
import { ShortPropertyImpl } from './ShortPropertyImpl.js';
import type { BoolProperty } from './BoolProperty.js';
import { BoolPropertyImpl } from './BoolPropertyImpl.js';
import type { StringListProperty } from './StringListProperty.js';
import { StringListPropertyImpl } from './StringListPropertyImpl.js';
import type { EObjectProperty } from './EObjectProperty.js';
import { EObjectPropertyImpl } from './EObjectPropertyImpl.js';
import type { ServiceOperation } from './ServiceOperation.js';
import { ServiceOperationImpl } from './ServiceOperationImpl.js';
import type { Parameter } from './Parameter.js';
import { ParameterImpl } from './ParameterImpl.js';
import type { RequiredConstraint } from './RequiredConstraint.js';
import { RequiredConstraintImpl } from './RequiredConstraintImpl.js';
import type { NumericRangeConstraint } from './NumericRangeConstraint.js';
import { NumericRangeConstraintImpl } from './NumericRangeConstraintImpl.js';
import type { StringPatternConstraint } from './StringPatternConstraint.js';
import { StringPatternConstraintImpl } from './StringPatternConstraintImpl.js';
import type { EnumerationConstraint } from './EnumerationConstraint.js';
import { EnumerationConstraintImpl } from './EnumerationConstraintImpl.js';
import type { ExpressionConstraint } from './ExpressionConstraint.js';
import { ExpressionConstraintImpl } from './ExpressionConstraintImpl.js';
import type { Invariant } from './Invariant.js';
import { InvariantImpl } from './InvariantImpl.js';
import type { CollectionSizeConstraint } from './CollectionSizeConstraint.js';
import { CollectionSizeConstraintImpl } from './CollectionSizeConstraintImpl.js';
import type { ServiceException } from './ServiceException.js';
import { ServiceExceptionImpl } from './ServiceExceptionImpl.js';
import type { ServiceInterface } from './ServiceInterface.js';
import { ServiceInterfaceImpl } from './ServiceInterfaceImpl.js';
import type { LifecycleHook } from './LifecycleHook.js';
import { LifecycleHookImpl } from './LifecycleHookImpl.js';
import type { ReferenceBinding } from './ReferenceBinding.js';
import { ReferenceBindingImpl } from './ReferenceBindingImpl.js';
import type { ComponentReference } from './ComponentReference.js';
import { ComponentReferenceImpl } from './ComponentReferenceImpl.js';
import type { ComponentDescription } from './ComponentDescription.js';
import { ComponentDescriptionImpl } from './ComponentDescriptionImpl.js';
import type { ServiceProvider } from './ServiceProvider.js';
import { ServiceProviderImpl } from './ServiceProviderImpl.js';
import type { ServiceImplementation } from './ServiceImplementation.js';
import { ServiceImplementationImpl } from './ServiceImplementationImpl.js';
import type { RestFlavor } from './RestFlavor.js';
import { RestFlavorImpl } from './RestFlavorImpl.js';
import type { MqttFlavor } from './MqttFlavor.js';
import { MqttFlavorImpl } from './MqttFlavorImpl.js';
import type { RestOperationFlavor } from './RestOperationFlavor.js';
import { RestOperationFlavorImpl } from './RestOperationFlavorImpl.js';
import type { RestParameterBinding } from './RestParameterBinding.js';
import { RestParameterBindingImpl } from './RestParameterBindingImpl.js';
import type { RestExceptionBinding } from './RestExceptionBinding.js';
import { RestExceptionBindingImpl } from './RestExceptionBindingImpl.js';
import type { MqttOperationFlavor } from './MqttOperationFlavor.js';
import { MqttOperationFlavorImpl } from './MqttOperationFlavorImpl.js';
import type { ServiceReference } from './ServiceReference.js';
import { ServiceReferenceImpl } from './ServiceReferenceImpl.js';
import type { ServiceRegistration } from './ServiceRegistration.js';
import { ServiceRegistrationImpl } from './ServiceRegistrationImpl.js';
import type { ConsumerSession } from './ConsumerSession.js';
import { ConsumerSessionImpl } from './ConsumerSessionImpl.js';
import type { ComponentConfiguration } from './ComponentConfiguration.js';
import { ComponentConfigurationImpl } from './ComponentConfigurationImpl.js';
import type { SatisfiedReference } from './SatisfiedReference.js';
import { SatisfiedReferenceImpl } from './SatisfiedReferenceImpl.js';
import type { UnsatisfiedReference } from './UnsatisfiedReference.js';
import { UnsatisfiedReferenceImpl } from './UnsatisfiedReferenceImpl.js';
import type { Diagnostic } from './Diagnostic.js';
import { DiagnosticImpl } from './DiagnosticImpl.js';
import type { ServiceEvent } from './ServiceEvent.js';
import { ServiceEventImpl } from './ServiceEventImpl.js';
import type { LocalServiceRegistry } from './LocalServiceRegistry.js';
import { LocalServiceRegistryImpl } from './LocalServiceRegistryImpl.js';
import type { RemoteServiceRegistry } from './RemoteServiceRegistry.js';
import { RemoteServiceRegistryImpl } from './RemoteServiceRegistryImpl.js';
import type { Capability } from './Capability.js';
import { CapabilityImpl } from './CapabilityImpl.js';
import type { Requirement } from './Requirement.js';
import { RequirementImpl } from './RequirementImpl.js';
import type { ConsumerCapability } from './ConsumerCapability.js';
import { ConsumerCapabilityImpl } from './ConsumerCapabilityImpl.js';
import type { TypeMapping } from './TypeMapping.js';
import { TypeMappingImpl } from './TypeMappingImpl.js';
import type { PackageMapping } from './PackageMapping.js';
import { PackageMappingImpl } from './PackageMappingImpl.js';
import type { JavaBinding } from './JavaBinding.js';
import { JavaBindingImpl } from './JavaBindingImpl.js';
import type { TypeScriptBinding } from './TypeScriptBinding.js';
import { TypeScriptBindingImpl } from './TypeScriptBindingImpl.js';
import type { PythonBinding } from './PythonBinding.js';
import { PythonBindingImpl } from './PythonBindingImpl.js';
import type { Argument } from './Argument.js';
import { ArgumentImpl } from './ArgumentImpl.js';
import type { ServiceInvocation } from './ServiceInvocation.js';
import { ServiceInvocationImpl } from './ServiceInvocationImpl.js';
import type { ServiceInvocationResult } from './ServiceInvocationResult.js';
import { ServiceInvocationResultImpl } from './ServiceInvocationResultImpl.js';

/**
 * Factory for creating DDSR model objects
 * @generated
 */
export class DDSRFactory extends BasicEFactory {
  // Lazy singleton instance
  private static _instance: DDSRFactory;

  static get eINSTANCE(): DDSRFactory {
    if (!this._instance) {
      this._instance = new DDSRFactory();
    }
    return this._instance;
  }

  private constructor() {
    super();
    this.setEPackage(DDSRPackage.eINSTANCE);
  }

  /**
   * Create a new StringProperty instance
   */
  createStringProperty(): StringProperty {
    return new StringPropertyImpl();
  }

  /**
   * Create a new IntProperty instance
   */
  createIntProperty(): IntProperty {
    return new IntPropertyImpl();
  }

  /**
   * Create a new LongProperty instance
   */
  createLongProperty(): LongProperty {
    return new LongPropertyImpl();
  }

  /**
   * Create a new DoubleProperty instance
   */
  createDoubleProperty(): DoubleProperty {
    return new DoublePropertyImpl();
  }

  /**
   * Create a new FloatProperty instance
   */
  createFloatProperty(): FloatProperty {
    return new FloatPropertyImpl();
  }

  /**
   * Create a new ShortProperty instance
   */
  createShortProperty(): ShortProperty {
    return new ShortPropertyImpl();
  }

  /**
   * Create a new BoolProperty instance
   */
  createBoolProperty(): BoolProperty {
    return new BoolPropertyImpl();
  }

  /**
   * Create a new StringListProperty instance
   */
  createStringListProperty(): StringListProperty {
    return new StringListPropertyImpl();
  }

  /**
   * Create a new EObjectProperty instance
   */
  createEObjectProperty(): EObjectProperty {
    return new EObjectPropertyImpl();
  }

  /**
   * Create a new ServiceOperation instance
   */
  createServiceOperation(): ServiceOperation {
    return new ServiceOperationImpl();
  }

  /**
   * Create a new Parameter instance
   */
  createParameter(): Parameter {
    return new ParameterImpl();
  }

  /**
   * Create a new RequiredConstraint instance
   */
  createRequiredConstraint(): RequiredConstraint {
    return new RequiredConstraintImpl();
  }

  /**
   * Create a new NumericRangeConstraint instance
   */
  createNumericRangeConstraint(): NumericRangeConstraint {
    return new NumericRangeConstraintImpl();
  }

  /**
   * Create a new StringPatternConstraint instance
   */
  createStringPatternConstraint(): StringPatternConstraint {
    return new StringPatternConstraintImpl();
  }

  /**
   * Create a new EnumerationConstraint instance
   */
  createEnumerationConstraint(): EnumerationConstraint {
    return new EnumerationConstraintImpl();
  }

  /**
   * Create a new ExpressionConstraint instance
   */
  createExpressionConstraint(): ExpressionConstraint {
    return new ExpressionConstraintImpl();
  }

  /**
   * Create a new Invariant instance
   */
  createInvariant(): Invariant {
    return new InvariantImpl();
  }

  /**
   * Create a new CollectionSizeConstraint instance
   */
  createCollectionSizeConstraint(): CollectionSizeConstraint {
    return new CollectionSizeConstraintImpl();
  }

  /**
   * Create a new ServiceException instance
   */
  createServiceException(): ServiceException {
    return new ServiceExceptionImpl();
  }

  /**
   * Create a new ServiceInterface instance
   */
  createServiceInterface(): ServiceInterface {
    return new ServiceInterfaceImpl();
  }

  /**
   * Create a new LifecycleHook instance
   */
  createLifecycleHook(): LifecycleHook {
    return new LifecycleHookImpl();
  }

  /**
   * Create a new ReferenceBinding instance
   */
  createReferenceBinding(): ReferenceBinding {
    return new ReferenceBindingImpl();
  }

  /**
   * Create a new ComponentReference instance
   */
  createComponentReference(): ComponentReference {
    return new ComponentReferenceImpl();
  }

  /**
   * Create a new ComponentDescription instance
   */
  createComponentDescription(): ComponentDescription {
    return new ComponentDescriptionImpl();
  }

  /**
   * Create a new ServiceProvider instance
   */
  createServiceProvider(): ServiceProvider {
    return new ServiceProviderImpl();
  }

  /**
   * Create a new ServiceImplementation instance
   */
  createServiceImplementation(): ServiceImplementation {
    return new ServiceImplementationImpl();
  }

  /**
   * Create a new RestFlavor instance
   */
  createRestFlavor(): RestFlavor {
    return new RestFlavorImpl();
  }

  /**
   * Create a new MqttFlavor instance
   */
  createMqttFlavor(): MqttFlavor {
    return new MqttFlavorImpl();
  }

  /**
   * Create a new RestOperationFlavor instance
   */
  createRestOperationFlavor(): RestOperationFlavor {
    return new RestOperationFlavorImpl();
  }

  /**
   * Create a new RestParameterBinding instance
   */
  createRestParameterBinding(): RestParameterBinding {
    return new RestParameterBindingImpl();
  }

  /**
   * Create a new RestExceptionBinding instance
   */
  createRestExceptionBinding(): RestExceptionBinding {
    return new RestExceptionBindingImpl();
  }

  /**
   * Create a new MqttOperationFlavor instance
   */
  createMqttOperationFlavor(): MqttOperationFlavor {
    return new MqttOperationFlavorImpl();
  }

  /**
   * Create a new ServiceReference instance
   */
  createServiceReference(): ServiceReference {
    return new ServiceReferenceImpl();
  }

  /**
   * Create a new ServiceRegistration instance
   */
  createServiceRegistration(): ServiceRegistration {
    return new ServiceRegistrationImpl();
  }

  /**
   * Create a new ConsumerSession instance
   */
  createConsumerSession(): ConsumerSession {
    return new ConsumerSessionImpl();
  }

  /**
   * Create a new ComponentConfiguration instance
   */
  createComponentConfiguration(): ComponentConfiguration {
    return new ComponentConfigurationImpl();
  }

  /**
   * Create a new SatisfiedReference instance
   */
  createSatisfiedReference(): SatisfiedReference {
    return new SatisfiedReferenceImpl();
  }

  /**
   * Create a new UnsatisfiedReference instance
   */
  createUnsatisfiedReference(): UnsatisfiedReference {
    return new UnsatisfiedReferenceImpl();
  }

  /**
   * Create a new Diagnostic instance
   */
  createDiagnostic(): Diagnostic {
    return new DiagnosticImpl();
  }

  /**
   * Create a new ServiceEvent instance
   */
  createServiceEvent(): ServiceEvent {
    return new ServiceEventImpl();
  }

  /**
   * Create a new LocalServiceRegistry instance
   */
  createLocalServiceRegistry(): LocalServiceRegistry {
    return new LocalServiceRegistryImpl();
  }

  /**
   * Create a new RemoteServiceRegistry instance
   */
  createRemoteServiceRegistry(): RemoteServiceRegistry {
    return new RemoteServiceRegistryImpl();
  }

  /**
   * Create a new Capability instance
   */
  createCapability(): Capability {
    return new CapabilityImpl();
  }

  /**
   * Create a new Requirement instance
   */
  createRequirement(): Requirement {
    return new RequirementImpl();
  }

  /**
   * Create a new ConsumerCapability instance
   */
  createConsumerCapability(): ConsumerCapability {
    return new ConsumerCapabilityImpl();
  }

  /**
   * Create a new TypeMapping instance
   */
  createTypeMapping(): TypeMapping {
    return new TypeMappingImpl();
  }

  /**
   * Create a new PackageMapping instance
   */
  createPackageMapping(): PackageMapping {
    return new PackageMappingImpl();
  }

  /**
   * Create a new JavaBinding instance
   */
  createJavaBinding(): JavaBinding {
    return new JavaBindingImpl();
  }

  /**
   * Create a new TypeScriptBinding instance
   */
  createTypeScriptBinding(): TypeScriptBinding {
    return new TypeScriptBindingImpl();
  }

  /**
   * Create a new PythonBinding instance
   */
  createPythonBinding(): PythonBinding {
    return new PythonBindingImpl();
  }

  /**
   * Create a new Argument instance
   */
  createArgument(): Argument {
    return new ArgumentImpl();
  }

  /**
   * Create a new ServiceInvocation instance
   */
  createServiceInvocation(): ServiceInvocation {
    return new ServiceInvocationImpl();
  }

  /**
   * Create a new ServiceInvocationResult instance
   */
  createServiceInvocationResult(): ServiceInvocationResult {
    return new ServiceInvocationResultImpl();
  }

  /**
   * Create an instance of the given class
   */
  override create(eClass: EClass): EObject {
    switch (eClass.getName()) {
      case 'StringProperty':
        return this.createStringProperty();
      case 'IntProperty':
        return this.createIntProperty();
      case 'LongProperty':
        return this.createLongProperty();
      case 'DoubleProperty':
        return this.createDoubleProperty();
      case 'FloatProperty':
        return this.createFloatProperty();
      case 'ShortProperty':
        return this.createShortProperty();
      case 'BoolProperty':
        return this.createBoolProperty();
      case 'StringListProperty':
        return this.createStringListProperty();
      case 'EObjectProperty':
        return this.createEObjectProperty();
      case 'ServiceOperation':
        return this.createServiceOperation();
      case 'Parameter':
        return this.createParameter();
      case 'RequiredConstraint':
        return this.createRequiredConstraint();
      case 'NumericRangeConstraint':
        return this.createNumericRangeConstraint();
      case 'StringPatternConstraint':
        return this.createStringPatternConstraint();
      case 'EnumerationConstraint':
        return this.createEnumerationConstraint();
      case 'ExpressionConstraint':
        return this.createExpressionConstraint();
      case 'Invariant':
        return this.createInvariant();
      case 'CollectionSizeConstraint':
        return this.createCollectionSizeConstraint();
      case 'ServiceException':
        return this.createServiceException();
      case 'ServiceInterface':
        return this.createServiceInterface();
      case 'LifecycleHook':
        return this.createLifecycleHook();
      case 'ReferenceBinding':
        return this.createReferenceBinding();
      case 'ComponentReference':
        return this.createComponentReference();
      case 'ComponentDescription':
        return this.createComponentDescription();
      case 'ServiceProvider':
        return this.createServiceProvider();
      case 'ServiceImplementation':
        return this.createServiceImplementation();
      case 'RestFlavor':
        return this.createRestFlavor();
      case 'MqttFlavor':
        return this.createMqttFlavor();
      case 'RestOperationFlavor':
        return this.createRestOperationFlavor();
      case 'RestParameterBinding':
        return this.createRestParameterBinding();
      case 'RestExceptionBinding':
        return this.createRestExceptionBinding();
      case 'MqttOperationFlavor':
        return this.createMqttOperationFlavor();
      case 'ServiceReference':
        return this.createServiceReference();
      case 'ServiceRegistration':
        return this.createServiceRegistration();
      case 'ConsumerSession':
        return this.createConsumerSession();
      case 'ComponentConfiguration':
        return this.createComponentConfiguration();
      case 'SatisfiedReference':
        return this.createSatisfiedReference();
      case 'UnsatisfiedReference':
        return this.createUnsatisfiedReference();
      case 'Diagnostic':
        return this.createDiagnostic();
      case 'ServiceEvent':
        return this.createServiceEvent();
      case 'LocalServiceRegistry':
        return this.createLocalServiceRegistry();
      case 'RemoteServiceRegistry':
        return this.createRemoteServiceRegistry();
      case 'Capability':
        return this.createCapability();
      case 'Requirement':
        return this.createRequirement();
      case 'ConsumerCapability':
        return this.createConsumerCapability();
      case 'TypeMapping':
        return this.createTypeMapping();
      case 'PackageMapping':
        return this.createPackageMapping();
      case 'JavaBinding':
        return this.createJavaBinding();
      case 'TypeScriptBinding':
        return this.createTypeScriptBinding();
      case 'PythonBinding':
        return this.createPythonBinding();
      case 'Argument':
        return this.createArgument();
      case 'ServiceInvocation':
        return this.createServiceInvocation();
      case 'ServiceInvocationResult':
        return this.createServiceInvocationResult();
      default:
        throw new Error(`Unknown class: ${eClass.getName()}`);
    }
  }
}
