/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { DiagnosticSeverity } from './DiagnosticSeverity.js';

/**
 * Diagnostic
 * @generated
 */
export interface Diagnostic extends EObject {
  severity: DiagnosticSeverity;
  message?: string;
  source?: string;
  code: number;
  data: EList<string>;
  children: EList<Diagnostic>;

}
