/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList, createBasicEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import { DiagnosticSeverity } from './DiagnosticSeverity.js';
import type { Diagnostic } from './Diagnostic.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of Diagnostic
 * @generated
 */
export class DiagnosticImpl extends BasicEObject implements Diagnostic {
  // Feature ID Constants (eLiterals)
  static readonly SEVERITY: number = 0;
  static readonly MESSAGE: number = 1;
  static readonly SOURCE: number = 2;
  static readonly CODE: number = 3;
  static readonly DATA: number = 4;
  static readonly CHILDREN: number = 5;

  // Private fields
  private _severity: DiagnosticSeverity = DiagnosticSeverity.OK;
  private _message?: string;
  private _source?: string;
  private _code: number = 0;
  private _data!: EList<string>;
  private _children!: EList<Diagnostic>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.DIAGNOSTIC;
  }

  // Getters and Setters
  get severity(): DiagnosticSeverity {
    return this._severity!;
  }

  set severity(value: DiagnosticSeverity) {
    const oldValue = this._severity;
    this._severity = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(DiagnosticImpl.SEVERITY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => DiagnosticImpl.SEVERITY,
        merge: () => false
      });
    }
  }

  get message(): string {
    return this._message!;
  }

  set message(value: string) {
    const oldValue = this._message;
    this._message = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(DiagnosticImpl.MESSAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => DiagnosticImpl.MESSAGE,
        merge: () => false
      });
    }
  }

  get source(): string {
    return this._source!;
  }

  set source(value: string) {
    const oldValue = this._source;
    this._source = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(DiagnosticImpl.SOURCE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => DiagnosticImpl.SOURCE,
        merge: () => false
      });
    }
  }

  get code(): number {
    return this._code!;
  }

  set code(value: number) {
    const oldValue = this._code;
    this._code = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(DiagnosticImpl.CODE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => DiagnosticImpl.CODE,
        merge: () => false
      });
    }
  }

  get data(): EList<string> {
    if (!this._data) {
      this._data = createBasicEList<any>(this, this.eClass().getEStructuralFeature('data')!);
    }
    return this._data;
  }

  get children(): EList<Diagnostic> {
    if (!this._children) {
      this._children = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('children') as EReference);
    }
    return this._children;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case DiagnosticImpl.SEVERITY:
        return this.severity;
      case DiagnosticImpl.MESSAGE:
        return this.message;
      case DiagnosticImpl.SOURCE:
        return this.source;
      case DiagnosticImpl.CODE:
        return this.code;
      case DiagnosticImpl.DATA:
        return this.data;
      case DiagnosticImpl.CHILDREN:
        return this.children;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case DiagnosticImpl.SEVERITY:
        this.severity = newValue as DiagnosticSeverity;
        super.eSet(feature, newValue);
        break;
      case DiagnosticImpl.MESSAGE:
        this.message = newValue as string;
        super.eSet(feature, newValue);
        break;
      case DiagnosticImpl.SOURCE:
        this.source = newValue as string;
        super.eSet(feature, newValue);
        break;
      case DiagnosticImpl.CODE:
        this.code = newValue as number;
        super.eSet(feature, newValue);
        break;
      case DiagnosticImpl.DATA:
        this.data.clear();
        this.data.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case DiagnosticImpl.CHILDREN:
        this.children.clear();
        this.children.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case DiagnosticImpl.SEVERITY:
        return this._severity !== DiagnosticSeverity.OK;
      case DiagnosticImpl.MESSAGE:
        return this._message !== undefined;
      case DiagnosticImpl.SOURCE:
        return this._source !== undefined;
      case DiagnosticImpl.CODE:
        return this._code !== 0;
      case DiagnosticImpl.DATA:
        return this._data !== undefined && !this._data.isEmpty();
      case DiagnosticImpl.CHILDREN:
        return this._children !== undefined && !this._children.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case DiagnosticImpl.SEVERITY:
        this._severity = DiagnosticSeverity.OK;
        return;
      case DiagnosticImpl.MESSAGE:
        this._message = undefined;
        return;
      case DiagnosticImpl.SOURCE:
        this._source = undefined;
        return;
      case DiagnosticImpl.CODE:
        this._code = 0;
        return;
      case DiagnosticImpl.DATA:
        if (this._data) this._data.clear();
        return;
      case DiagnosticImpl.CHILDREN:
        if (this._children) this._children.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

}
