/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Diagnostic } from './Diagnostic.js';
import type { ConsumerCapability } from './ConsumerCapability.js';
import type { ServiceReference } from './ServiceReference.js';
import type { ServiceListener } from './ServiceListener.js';

/**
 * DiscoveryHook
 * @generated
 */
export interface DiscoveryHook extends EObject {

  onLookup(interfaceName: string, filter: string, capability: ConsumerCapability): Diagnostic;
  filterReferences(capability: ConsumerCapability, references: ServiceReference): ServiceReference;
  onSubscribe(listener: ServiceListener): Diagnostic;
}
