/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ParameterConstraint } from './ParameterConstraint.js';

/**
 * EnumerationConstraint
 * @generated
 */
export interface EnumerationConstraint extends ParameterConstraint {
  allowedValues: EList<string>;

}
