/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { createBasicEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { ParameterConstraint } from './ParameterConstraint.js';
import { ParameterConstraintImpl } from './ParameterConstraintImpl.js';
import type { EnumerationConstraint } from './EnumerationConstraint.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of EnumerationConstraint
 * @generated
 */
export class EnumerationConstraintImpl extends ParameterConstraintImpl implements EnumerationConstraint {
  // Feature ID Constants (eLiterals)
  static readonly ALLOWED_VALUES: number = 0;

  // Private fields
  private _allowedValues!: EList<string>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.ENUMERATION_CONSTRAINT;
  }

  // Getters and Setters
  get allowedValues(): EList<string> {
    if (!this._allowedValues) {
      this._allowedValues = createBasicEList<any>(this, this.eClass().getEStructuralFeature('allowedValues')!);
    }
    return this._allowedValues;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case EnumerationConstraintImpl.ALLOWED_VALUES:
        return this.allowedValues;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case EnumerationConstraintImpl.ALLOWED_VALUES:
        this.allowedValues.clear();
        this.allowedValues.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case EnumerationConstraintImpl.ALLOWED_VALUES:
        return this._allowedValues !== undefined && !this._allowedValues.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case EnumerationConstraintImpl.ALLOWED_VALUES:
        if (this._allowedValues) this._allowedValues.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

}
