/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ParameterConstraint } from './ParameterConstraint';
import { ParameterConstraintImpl } from './ParameterConstraintImpl';
import type { EnumerationConstraint } from './EnumerationConstraint';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of EnumerationConstraint
 * @generated
 */
export class EnumerationConstraintImpl extends ParameterConstraintImpl implements EnumerationConstraint {
  // Feature ID Constants (eLiterals)
  static readonly ALLOWED_VALUES: number = 0;

  // Private fields
  private _allowedValues: string[] = [];

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.ENUMERATION_CONSTRAINT;
  }

  // Getters and Setters
  get allowedValues(): string[] {
    return this._allowedValues;
  }

  set allowedValues(value: string[]) {
    const oldValue = this._allowedValues;
    this._allowedValues = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(EnumerationConstraintImpl.ALLOWED_VALUES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => EnumerationConstraintImpl.ALLOWED_VALUES,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case EnumerationConstraintImpl.ALLOWED_VALUES:
        return this.allowedValues;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case EnumerationConstraintImpl.ALLOWED_VALUES:
        this.allowedValues = newValue as string[];
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case EnumerationConstraintImpl.ALLOWED_VALUES:
        return this._allowedValues !== undefined && this._allowedValues.length > 0;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case EnumerationConstraintImpl.ALLOWED_VALUES:
        this._allowedValues = [];
        return;
      default:
        super.eUnset(feature);
    }
  }

}
