/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ParameterConstraint } from './ParameterConstraint';
import type { NamedElement } from './NamedElement';
import type { ExpressionLanguage } from './ExpressionLanguage';

/**
 * ExpressionConstraint
 * @generated
 */
export interface ExpressionConstraint extends ParameterConstraint, NamedElement {
  language: ExpressionLanguage;
  expression: string;
  message?: string;

}
