/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ExpressionLanguage
 * @generated
 */
export const ExpressionLanguage = {
  OCL: 'OCL'
} as const;

export type ExpressionLanguage = typeof ExpressionLanguage[keyof typeof ExpressionLanguage];

/**
 * Get enum value by name
 */
export function getExpressionLanguage(name: string): ExpressionLanguage | undefined {
  return (ExpressionLanguage as Record<string, string>)[name] as ExpressionLanguage | undefined;
}

/**
 * Get enum value by literal
 */
export function getExpressionLanguageByLiteral(literal: string): ExpressionLanguage | undefined {
  if (literal === 'OCL') return ExpressionLanguage.OCL;
  return undefined;
}
