/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * FieldOption
 * @generated
 */
export const FieldOption = {
  REPLACE: 'REPLACE',
  UPDATE: 'UPDATE'
} as const;

export type FieldOption = typeof FieldOption[keyof typeof FieldOption];

/**
 * Get enum value by name
 */
export function getFieldOption(name: string): FieldOption | undefined {
  return (FieldOption as Record<string, string>)[name] as FieldOption | undefined;
}

/**
 * Get enum value by literal
 */
export function getFieldOptionByLiteral(literal: string): FieldOption | undefined {
  if (literal === 'REPLACE') return FieldOption.REPLACE;
  if (literal === 'UPDATE') return FieldOption.UPDATE;
  return undefined;
}
