/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * FlavorKind
 * @generated
 */
export const FlavorKind = {
  REST: 'REST',
  MQTT: 'MQTT'
} as const;

export type FlavorKind = typeof FlavorKind[keyof typeof FlavorKind];

/**
 * Get enum value by name
 */
export function getFlavorKind(name: string): FlavorKind | undefined {
  return (FlavorKind as Record<string, string>)[name] as FlavorKind | undefined;
}

/**
 * Get enum value by literal
 */
export function getFlavorKindByLiteral(literal: string): FlavorKind | undefined {
  if (literal === 'REST') return FlavorKind.REST;
  if (literal === 'MQTT') return FlavorKind.MQTT;
  return undefined;
}
