/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import { ExpressionLanguage } from './ExpressionLanguage';
import type { Invariant } from './Invariant';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of Invariant
 * @generated
 */
export class InvariantImpl extends BasicEObject implements Invariant {
  // Feature ID Constants (eLiterals)
  static readonly LANGUAGE: number = 1;
  static readonly EXPRESSION: number = 2;
  static readonly MESSAGE: number = 3;
  static readonly NAME: number = 0;

  // Private fields
  private _language: ExpressionLanguage = ExpressionLanguage.OCL;
  private _expression: string = "";
  private _message?: string;
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.INVARIANT;
  }

  // Getters and Setters
  get language(): ExpressionLanguage {
    return this._language!;
  }

  set language(value: ExpressionLanguage) {
    const oldValue = this._language;
    this._language = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(InvariantImpl.LANGUAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => InvariantImpl.LANGUAGE,
        merge: () => false
      });
    }
  }

  get expression(): string {
    return this._expression!;
  }

  set expression(value: string) {
    const oldValue = this._expression;
    this._expression = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(InvariantImpl.EXPRESSION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => InvariantImpl.EXPRESSION,
        merge: () => false
      });
    }
  }

  get message(): string {
    return this._message!;
  }

  set message(value: string) {
    const oldValue = this._message;
    this._message = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(InvariantImpl.MESSAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => InvariantImpl.MESSAGE,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case InvariantImpl.LANGUAGE:
        return this.language;
      case InvariantImpl.EXPRESSION:
        return this.expression;
      case InvariantImpl.MESSAGE:
        return this.message;
      case InvariantImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case InvariantImpl.LANGUAGE:
        this.language = newValue as ExpressionLanguage;
        super.eSet(feature, newValue);
        break;
      case InvariantImpl.EXPRESSION:
        this.expression = newValue as string;
        super.eSet(feature, newValue);
        break;
      case InvariantImpl.MESSAGE:
        this.message = newValue as string;
        super.eSet(feature, newValue);
        break;
      case InvariantImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case InvariantImpl.LANGUAGE:
        return this._language !== ExpressionLanguage.OCL;
      case InvariantImpl.EXPRESSION:
        return this._expression !== "";
      case InvariantImpl.MESSAGE:
        return this._message !== undefined;
      case InvariantImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case InvariantImpl.LANGUAGE:
        this._language = ExpressionLanguage.OCL;
        return;
      case InvariantImpl.EXPRESSION:
        this._expression = "";
        return;
      case InvariantImpl.MESSAGE:
        this._message = undefined;
        return;
      case InvariantImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
