/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { LanguageBinding } from './LanguageBinding.js';
import type { ApiType } from './ApiType.js';

/**
 * JavaBinding
 * @generated
 */
export interface JavaBinding extends LanguageBinding {
  apiType: ApiType;

}
