/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EClass, EStructuralFeature } from '@emfts/core';
import type { LanguageBinding } from './LanguageBinding';
import { ApiType } from './ApiType';
import { LanguageBindingImpl } from './LanguageBindingImpl';
import type { JavaBinding } from './JavaBinding';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of JavaBinding
 * @generated
 */
export class JavaBindingImpl extends LanguageBindingImpl implements JavaBinding {
  // Feature ID Constants (eLiterals)
  static readonly API_TYPE: number = 6;

  // Private fields
  private _apiType: ApiType = ApiType.PROVIDER;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.JAVA_BINDING;
  }

  // Getters and Setters
  get apiType(): ApiType {
    return this._apiType!;
  }

  set apiType(value: ApiType) {
    const oldValue = this._apiType;
    this._apiType = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(JavaBindingImpl.API_TYPE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => JavaBindingImpl.API_TYPE,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case JavaBindingImpl.API_TYPE:
        return this.apiType;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case JavaBindingImpl.API_TYPE:
        this.apiType = newValue as ApiType;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case JavaBindingImpl.API_TYPE:
        return this._apiType !== ApiType.PROVIDER;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case JavaBindingImpl.API_TYPE:
        this._apiType = ApiType.PROVIDER;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
