/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList, createEObjectEList, createBasicEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { ServiceInterface } from './ServiceInterface.js';
import type { TypeMapping } from './TypeMapping.js';
import type { PackageMapping } from './PackageMapping.js';
import type { LanguageBinding } from './LanguageBinding.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of LanguageBinding
 * @generated
 */
export abstract class LanguageBindingImpl extends BasicEObject implements LanguageBinding {
  // Feature ID Constants (eLiterals)
  static readonly SERVICE_INTERFACES: number = 1;
  static readonly TARGET_PACKAGE: number = 2;
  static readonly FILE_HEADER: number = 3;
  static readonly TYPE_MAPPINGS: number = 4;
  static readonly PACKAGE_MAPPINGS: number = 5;
  static readonly NAME: number = 0;

  // Private fields
  private _serviceInterfaces!: EList<ServiceInterface>;
  private _targetPackage: string = "";
  private _fileHeader!: EList<string>;
  private _typeMappings!: EList<TypeMapping>;
  private _packageMappings!: EList<PackageMapping>;
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.LANGUAGE_BINDING;
  }

  // Getters and Setters
  get serviceInterfaces(): EList<ServiceInterface> {
    if (!this._serviceInterfaces) {
      this._serviceInterfaces = createEObjectEList(this, this.eClass().getEStructuralFeature('serviceInterfaces') as EReference) as unknown as EList<ServiceInterface>;
    }
    return this._serviceInterfaces;
  }

  get targetPackage(): string {
    return this._targetPackage!;
  }

  set targetPackage(value: string) {
    const oldValue = this._targetPackage;
    this._targetPackage = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LanguageBindingImpl.TARGET_PACKAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LanguageBindingImpl.TARGET_PACKAGE,
        merge: () => false
      });
    }
  }

  get fileHeader(): EList<string> {
    if (!this._fileHeader) {
      this._fileHeader = createBasicEList<any>(this, this.eClass().getEStructuralFeature('fileHeader')!);
    }
    return this._fileHeader;
  }

  get typeMappings(): EList<TypeMapping> {
    if (!this._typeMappings) {
      this._typeMappings = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('typeMappings') as EReference);
    }
    return this._typeMappings;
  }

  get packageMappings(): EList<PackageMapping> {
    if (!this._packageMappings) {
      this._packageMappings = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('packageMappings') as EReference);
    }
    return this._packageMappings;
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LanguageBindingImpl.SERVICE_INTERFACES:
        return this.serviceInterfaces;
      case LanguageBindingImpl.TARGET_PACKAGE:
        return this.targetPackage;
      case LanguageBindingImpl.FILE_HEADER:
        return this.fileHeader;
      case LanguageBindingImpl.TYPE_MAPPINGS:
        return this.typeMappings;
      case LanguageBindingImpl.PACKAGE_MAPPINGS:
        return this.packageMappings;
      case LanguageBindingImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LanguageBindingImpl.SERVICE_INTERFACES:
        this.serviceInterfaces.clear();
        this.serviceInterfaces.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.TARGET_PACKAGE:
        this.targetPackage = newValue as string;
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.FILE_HEADER:
        this.fileHeader.clear();
        this.fileHeader.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.TYPE_MAPPINGS:
        this.typeMappings.clear();
        this.typeMappings.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.PACKAGE_MAPPINGS:
        this.packageMappings.clear();
        this.packageMappings.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LanguageBindingImpl.SERVICE_INTERFACES:
        return this._serviceInterfaces !== undefined && !this._serviceInterfaces.isEmpty();
      case LanguageBindingImpl.TARGET_PACKAGE:
        return this._targetPackage !== "";
      case LanguageBindingImpl.FILE_HEADER:
        return this._fileHeader !== undefined && !this._fileHeader.isEmpty();
      case LanguageBindingImpl.TYPE_MAPPINGS:
        return this._typeMappings !== undefined && !this._typeMappings.isEmpty();
      case LanguageBindingImpl.PACKAGE_MAPPINGS:
        return this._packageMappings !== undefined && !this._packageMappings.isEmpty();
      case LanguageBindingImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LanguageBindingImpl.SERVICE_INTERFACES:
        if (this._serviceInterfaces) this._serviceInterfaces.clear();
        return;
      case LanguageBindingImpl.TARGET_PACKAGE:
        this._targetPackage = "";
        return;
      case LanguageBindingImpl.FILE_HEADER:
        if (this._fileHeader) this._fileHeader.clear();
        return;
      case LanguageBindingImpl.TYPE_MAPPINGS:
        if (this._typeMappings) this._typeMappings.clear();
        return;
      case LanguageBindingImpl.PACKAGE_MAPPINGS:
        if (this._packageMappings) this._packageMappings.clear();
        return;
      case LanguageBindingImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
