/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { ServiceInterface } from './ServiceInterface';
import type { TypeMapping } from './TypeMapping';
import type { PackageMapping } from './PackageMapping';
import type { LanguageBinding } from './LanguageBinding';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of LanguageBinding
 * @generated
 */
export abstract class LanguageBindingImpl extends BasicEObject implements LanguageBinding {
  // Feature ID Constants (eLiterals)
  static readonly SERVICE_INTERFACES: number = 1;
  static readonly TARGET_PACKAGE: number = 2;
  static readonly FILE_HEADER: number = 3;
  static readonly TYPE_MAPPINGS: number = 4;
  static readonly PACKAGE_MAPPINGS: number = 5;
  static readonly NAME: number = 0;

  // Private fields
  private _serviceInterfaces: ServiceInterface[] = [];
  private _targetPackage: string = "";
  private _fileHeader: string[] = [];
  private _typeMappings: TypeMapping[] = [];
  private _packageMappings: PackageMapping[] = [];
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.LANGUAGE_BINDING;
  }

  // Getters and Setters
  get serviceInterfaces(): ServiceInterface[] {
    return this._serviceInterfaces;
  }

  set serviceInterfaces(value: ServiceInterface[]) {
    const oldValue = this._serviceInterfaces;
    this._serviceInterfaces = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LanguageBindingImpl.SERVICE_INTERFACES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LanguageBindingImpl.SERVICE_INTERFACES,
        merge: () => false
      });
    }
  }

  get targetPackage(): string {
    return this._targetPackage!;
  }

  set targetPackage(value: string) {
    const oldValue = this._targetPackage;
    this._targetPackage = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LanguageBindingImpl.TARGET_PACKAGE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LanguageBindingImpl.TARGET_PACKAGE,
        merge: () => false
      });
    }
  }

  get fileHeader(): string[] {
    return this._fileHeader;
  }

  set fileHeader(value: string[]) {
    const oldValue = this._fileHeader;
    this._fileHeader = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LanguageBindingImpl.FILE_HEADER),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LanguageBindingImpl.FILE_HEADER,
        merge: () => false
      });
    }
  }

  get typeMappings(): TypeMapping[] {
    return this._typeMappings;
  }

  set typeMappings(value: TypeMapping[]) {
    const oldValue = this._typeMappings;
    this._typeMappings = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LanguageBindingImpl.TYPE_MAPPINGS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LanguageBindingImpl.TYPE_MAPPINGS,
        merge: () => false
      });
    }
  }

  get packageMappings(): PackageMapping[] {
    return this._packageMappings;
  }

  set packageMappings(value: PackageMapping[]) {
    const oldValue = this._packageMappings;
    this._packageMappings = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LanguageBindingImpl.PACKAGE_MAPPINGS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LanguageBindingImpl.PACKAGE_MAPPINGS,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LanguageBindingImpl.SERVICE_INTERFACES:
        return this.serviceInterfaces;
      case LanguageBindingImpl.TARGET_PACKAGE:
        return this.targetPackage;
      case LanguageBindingImpl.FILE_HEADER:
        return this.fileHeader;
      case LanguageBindingImpl.TYPE_MAPPINGS:
        return this.typeMappings;
      case LanguageBindingImpl.PACKAGE_MAPPINGS:
        return this.packageMappings;
      case LanguageBindingImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LanguageBindingImpl.SERVICE_INTERFACES:
        this.serviceInterfaces = newValue as ServiceInterface[];
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.TARGET_PACKAGE:
        this.targetPackage = newValue as string;
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.FILE_HEADER:
        this.fileHeader = newValue as string[];
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.TYPE_MAPPINGS:
        this.typeMappings = newValue as TypeMapping[];
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.PACKAGE_MAPPINGS:
        this.packageMappings = newValue as PackageMapping[];
        super.eSet(feature, newValue);
        break;
      case LanguageBindingImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LanguageBindingImpl.SERVICE_INTERFACES:
        return this._serviceInterfaces !== undefined && this._serviceInterfaces.length > 0;
      case LanguageBindingImpl.TARGET_PACKAGE:
        return this._targetPackage !== "";
      case LanguageBindingImpl.FILE_HEADER:
        return this._fileHeader !== undefined && this._fileHeader.length > 0;
      case LanguageBindingImpl.TYPE_MAPPINGS:
        return this._typeMappings !== undefined && this._typeMappings.length > 0;
      case LanguageBindingImpl.PACKAGE_MAPPINGS:
        return this._packageMappings !== undefined && this._packageMappings.length > 0;
      case LanguageBindingImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LanguageBindingImpl.SERVICE_INTERFACES:
        this._serviceInterfaces = [];
        return;
      case LanguageBindingImpl.TARGET_PACKAGE:
        this._targetPackage = "";
        return;
      case LanguageBindingImpl.FILE_HEADER:
        this._fileHeader = [];
        return;
      case LanguageBindingImpl.TYPE_MAPPINGS:
        this._typeMappings = [];
        return;
      case LanguageBindingImpl.PACKAGE_MAPPINGS:
        this._packageMappings = [];
        return;
      case LanguageBindingImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
