/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { LifecycleHookKind } from './LifecycleHookKind';

/**
 * LifecycleHook
 * @generated
 */
export interface LifecycleHook extends NamedElement {
  kind: LifecycleHookKind;
  parameter?: number;

}
