/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { LifecycleHookKind } from './LifecycleHookKind';
import type { LifecycleHook } from './LifecycleHook';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of LifecycleHook
 * @generated
 */
export class LifecycleHookImpl extends BasicEObject implements LifecycleHook {
  // Feature ID Constants (eLiterals)
  static readonly KIND: number = 1;
  static readonly PARAMETER: number = 2;
  static readonly NAME: number = 0;

  // Private fields
  private _kind?: LifecycleHookKind;
  private _parameter?: number;
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.LIFECYCLE_HOOK;
  }

  // Getters and Setters
  get kind(): LifecycleHookKind {
    return this._kind!;
  }

  set kind(value: LifecycleHookKind) {
    const oldValue = this._kind;
    this._kind = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LifecycleHookImpl.KIND),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LifecycleHookImpl.KIND,
        merge: () => false
      });
    }
  }

  get parameter(): number {
    return this._parameter!;
  }

  set parameter(value: number) {
    const oldValue = this._parameter;
    this._parameter = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LifecycleHookImpl.PARAMETER),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LifecycleHookImpl.PARAMETER,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LifecycleHookImpl.KIND:
        return this.kind;
      case LifecycleHookImpl.PARAMETER:
        return this.parameter;
      case LifecycleHookImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LifecycleHookImpl.KIND:
        this.kind = newValue as LifecycleHookKind;
        super.eSet(feature, newValue);
        break;
      case LifecycleHookImpl.PARAMETER:
        this.parameter = newValue as number;
        super.eSet(feature, newValue);
        break;
      case LifecycleHookImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LifecycleHookImpl.KIND:
        return this._kind !== undefined;
      case LifecycleHookImpl.PARAMETER:
        return this._parameter !== undefined;
      case LifecycleHookImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LifecycleHookImpl.KIND:
        this._kind = undefined;
        return;
      case LifecycleHookImpl.PARAMETER:
        this._parameter = undefined;
        return;
      case LifecycleHookImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
