/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceRegistry } from './ServiceRegistry';
import type { ServiceReference } from './ServiceReference';
import type { ServiceRegistration } from './ServiceRegistration';
import type { ConsumerSession } from './ConsumerSession';
import type { ComponentConfiguration } from './ComponentConfiguration';
import type { ServiceProvider } from './ServiceProvider';
import type { ServiceListener } from './ServiceListener';
import type { RemoteServiceRegistry } from './RemoteServiceRegistry';
import type { ConnectionState } from './ConnectionState';
import type { ServiceImplementation } from './ServiceImplementation';
import type { Property } from './Property';
import type { ServiceEvent } from './ServiceEvent';

/**
 * LocalServiceRegistry
 * @generated
 */
export interface LocalServiceRegistry extends ServiceRegistry {
  references: ServiceReference[];
  registrations: ServiceRegistration[];
  sessions: ConsumerSession[];
  configurations: ComponentConfiguration[];
  providers: ServiceProvider[];
  listeners: ServiceListener[];
  remote?: RemoteServiceRegistry;
  connectionState: ConnectionState;

  registerService(provider: ServiceProvider, implementation: ServiceImplementation, props: Property): ServiceRegistration;
  fireServiceEvent(event: ServiceEvent): void;
}
