/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { createContainmentEList, createEObjectEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { ServiceRegistry } from './ServiceRegistry.js';
import type { ServiceReference } from './ServiceReference.js';
import type { ServiceRegistration } from './ServiceRegistration.js';
import type { ConsumerSession } from './ConsumerSession.js';
import type { ComponentConfiguration } from './ComponentConfiguration.js';
import type { ServiceProvider } from './ServiceProvider.js';
import type { ServiceListener } from './ServiceListener.js';
import type { RemoteServiceRegistry } from './RemoteServiceRegistry.js';
import type { ServiceImplementation } from './ServiceImplementation.js';
import type { Property } from './Property.js';
import type { ServiceEvent } from './ServiceEvent.js';
import { ConnectionState } from './ConnectionState.js';
import { ServiceRegistryImpl } from './ServiceRegistryImpl.js';
import type { LocalServiceRegistry } from './LocalServiceRegistry.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of LocalServiceRegistry
 * @generated
 */
export class LocalServiceRegistryImpl extends ServiceRegistryImpl implements LocalServiceRegistry {
  // Feature ID Constants (eLiterals)
  static readonly REFERENCES: number = 5;
  static readonly REGISTRATIONS: number = 6;
  static readonly SESSIONS: number = 7;
  static readonly CONFIGURATIONS: number = 8;
  static readonly PROVIDERS: number = 9;
  static readonly LISTENERS: number = 10;
  static readonly REMOTE: number = 11;
  static readonly CONNECTION_STATE: number = 12;

  // Private fields
  private _references!: EList<ServiceReference>;
  private _registrations!: EList<ServiceRegistration>;
  private _sessions!: EList<ConsumerSession>;
  private _configurations!: EList<ComponentConfiguration>;
  private _providers!: EList<ServiceProvider>;
  private _listeners!: EList<ServiceListener>;
  private _remote?: RemoteServiceRegistry;
  private _connectionState: ConnectionState = ConnectionState.OFFLINE;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.LOCAL_SERVICE_REGISTRY;
  }

  // Getters and Setters
  get references(): EList<ServiceReference> {
    if (!this._references) {
      this._references = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('references') as EReference);
    }
    return this._references;
  }

  get registrations(): EList<ServiceRegistration> {
    if (!this._registrations) {
      this._registrations = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('registrations') as EReference);
    }
    return this._registrations;
  }

  get sessions(): EList<ConsumerSession> {
    if (!this._sessions) {
      this._sessions = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('sessions') as EReference);
    }
    return this._sessions;
  }

  get configurations(): EList<ComponentConfiguration> {
    if (!this._configurations) {
      this._configurations = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('configurations') as EReference);
    }
    return this._configurations;
  }

  get providers(): EList<ServiceProvider> {
    if (!this._providers) {
      this._providers = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('providers') as EReference);
    }
    return this._providers;
  }

  get listeners(): EList<ServiceListener> {
    if (!this._listeners) {
      this._listeners = createEObjectEList(this, this.eClass().getEStructuralFeature('listeners') as EReference) as unknown as EList<ServiceListener>;
    }
    return this._listeners;
  }

  get remote(): RemoteServiceRegistry {
    return this._remote!;
  }

  set remote(value: RemoteServiceRegistry) {
    const oldValue = this._remote;
    this._remote = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.REMOTE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.REMOTE,
        merge: () => false
      });
    }
  }

  get connectionState(): ConnectionState {
    return this._connectionState!;
  }

  set connectionState(value: ConnectionState) {
    const oldValue = this._connectionState;
    this._connectionState = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.CONNECTION_STATE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.CONNECTION_STATE,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LocalServiceRegistryImpl.REFERENCES:
        return this.references;
      case LocalServiceRegistryImpl.REGISTRATIONS:
        return this.registrations;
      case LocalServiceRegistryImpl.SESSIONS:
        return this.sessions;
      case LocalServiceRegistryImpl.CONFIGURATIONS:
        return this.configurations;
      case LocalServiceRegistryImpl.PROVIDERS:
        return this.providers;
      case LocalServiceRegistryImpl.LISTENERS:
        return this.listeners;
      case LocalServiceRegistryImpl.REMOTE:
        return this.remote;
      case LocalServiceRegistryImpl.CONNECTION_STATE:
        return this.connectionState;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LocalServiceRegistryImpl.REFERENCES:
        this.references.clear();
        this.references.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.REGISTRATIONS:
        this.registrations.clear();
        this.registrations.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.SESSIONS:
        this.sessions.clear();
        this.sessions.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.CONFIGURATIONS:
        this.configurations.clear();
        this.configurations.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.PROVIDERS:
        this.providers.clear();
        this.providers.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.LISTENERS:
        this.listeners.clear();
        this.listeners.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.REMOTE:
        this.remote = newValue as RemoteServiceRegistry;
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.CONNECTION_STATE:
        this.connectionState = newValue as ConnectionState;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LocalServiceRegistryImpl.REFERENCES:
        return this._references !== undefined && !this._references.isEmpty();
      case LocalServiceRegistryImpl.REGISTRATIONS:
        return this._registrations !== undefined && !this._registrations.isEmpty();
      case LocalServiceRegistryImpl.SESSIONS:
        return this._sessions !== undefined && !this._sessions.isEmpty();
      case LocalServiceRegistryImpl.CONFIGURATIONS:
        return this._configurations !== undefined && !this._configurations.isEmpty();
      case LocalServiceRegistryImpl.PROVIDERS:
        return this._providers !== undefined && !this._providers.isEmpty();
      case LocalServiceRegistryImpl.LISTENERS:
        return this._listeners !== undefined && !this._listeners.isEmpty();
      case LocalServiceRegistryImpl.REMOTE:
        return this._remote !== undefined;
      case LocalServiceRegistryImpl.CONNECTION_STATE:
        return this._connectionState !== ConnectionState.OFFLINE;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LocalServiceRegistryImpl.REFERENCES:
        if (this._references) this._references.clear();
        return;
      case LocalServiceRegistryImpl.REGISTRATIONS:
        if (this._registrations) this._registrations.clear();
        return;
      case LocalServiceRegistryImpl.SESSIONS:
        if (this._sessions) this._sessions.clear();
        return;
      case LocalServiceRegistryImpl.CONFIGURATIONS:
        if (this._configurations) this._configurations.clear();
        return;
      case LocalServiceRegistryImpl.PROVIDERS:
        if (this._providers) this._providers.clear();
        return;
      case LocalServiceRegistryImpl.LISTENERS:
        if (this._listeners) this._listeners.clear();
        return;
      case LocalServiceRegistryImpl.REMOTE:
        this._remote = undefined;
        return;
      case LocalServiceRegistryImpl.CONNECTION_STATE:
        this._connectionState = ConnectionState.OFFLINE;
        return;
      default:
        super.eUnset(feature);
    }
  }

  registerService(provider: ServiceProvider, implementation: ServiceImplementation, props: Property): ServiceRegistration {
    throw new Error('registerService not implemented');
  }

  fireServiceEvent(event: ServiceEvent): void {
    throw new Error('fireServiceEvent not implemented');
  }

}
