/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceRegistry } from './ServiceRegistry';
import type { ServiceReference } from './ServiceReference';
import type { ServiceRegistration } from './ServiceRegistration';
import type { ConsumerSession } from './ConsumerSession';
import type { ComponentConfiguration } from './ComponentConfiguration';
import type { ServiceProvider } from './ServiceProvider';
import type { ServiceListener } from './ServiceListener';
import type { RemoteServiceRegistry } from './RemoteServiceRegistry';
import type { ServiceImplementation } from './ServiceImplementation';
import type { Property } from './Property';
import type { ServiceEvent } from './ServiceEvent';
import { ConnectionState } from './ConnectionState';
import { ServiceRegistryImpl } from './ServiceRegistryImpl';
import type { LocalServiceRegistry } from './LocalServiceRegistry';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of LocalServiceRegistry
 * @generated
 */
export class LocalServiceRegistryImpl extends ServiceRegistryImpl implements LocalServiceRegistry {
  // Feature ID Constants (eLiterals)
  static readonly REFERENCES: number = 5;
  static readonly REGISTRATIONS: number = 6;
  static readonly SESSIONS: number = 7;
  static readonly CONFIGURATIONS: number = 8;
  static readonly PROVIDERS: number = 9;
  static readonly LISTENERS: number = 10;
  static readonly REMOTE: number = 11;
  static readonly CONNECTION_STATE: number = 12;

  // Private fields
  private _references: ServiceReference[] = [];
  private _registrations: ServiceRegistration[] = [];
  private _sessions: ConsumerSession[] = [];
  private _configurations: ComponentConfiguration[] = [];
  private _providers: ServiceProvider[] = [];
  private _listeners: ServiceListener[] = [];
  private _remote?: RemoteServiceRegistry;
  private _connectionState: ConnectionState = ConnectionState.OFFLINE;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.LOCAL_SERVICE_REGISTRY;
  }

  // Getters and Setters
  get references(): ServiceReference[] {
    return this._references;
  }

  set references(value: ServiceReference[]) {
    const oldValue = this._references;
    this._references = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.REFERENCES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.REFERENCES,
        merge: () => false
      });
    }
  }

  get registrations(): ServiceRegistration[] {
    return this._registrations;
  }

  set registrations(value: ServiceRegistration[]) {
    const oldValue = this._registrations;
    this._registrations = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.REGISTRATIONS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.REGISTRATIONS,
        merge: () => false
      });
    }
  }

  get sessions(): ConsumerSession[] {
    return this._sessions;
  }

  set sessions(value: ConsumerSession[]) {
    const oldValue = this._sessions;
    this._sessions = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.SESSIONS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.SESSIONS,
        merge: () => false
      });
    }
  }

  get configurations(): ComponentConfiguration[] {
    return this._configurations;
  }

  set configurations(value: ComponentConfiguration[]) {
    const oldValue = this._configurations;
    this._configurations = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.CONFIGURATIONS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.CONFIGURATIONS,
        merge: () => false
      });
    }
  }

  get providers(): ServiceProvider[] {
    return this._providers;
  }

  set providers(value: ServiceProvider[]) {
    const oldValue = this._providers;
    this._providers = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.PROVIDERS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.PROVIDERS,
        merge: () => false
      });
    }
  }

  get listeners(): ServiceListener[] {
    return this._listeners;
  }

  set listeners(value: ServiceListener[]) {
    const oldValue = this._listeners;
    this._listeners = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.LISTENERS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.LISTENERS,
        merge: () => false
      });
    }
  }

  get remote(): RemoteServiceRegistry {
    return this._remote!;
  }

  set remote(value: RemoteServiceRegistry) {
    const oldValue = this._remote;
    this._remote = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.REMOTE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.REMOTE,
        merge: () => false
      });
    }
  }

  get connectionState(): ConnectionState {
    return this._connectionState!;
  }

  set connectionState(value: ConnectionState) {
    const oldValue = this._connectionState;
    this._connectionState = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(LocalServiceRegistryImpl.CONNECTION_STATE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => LocalServiceRegistryImpl.CONNECTION_STATE,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LocalServiceRegistryImpl.REFERENCES:
        return this.references;
      case LocalServiceRegistryImpl.REGISTRATIONS:
        return this.registrations;
      case LocalServiceRegistryImpl.SESSIONS:
        return this.sessions;
      case LocalServiceRegistryImpl.CONFIGURATIONS:
        return this.configurations;
      case LocalServiceRegistryImpl.PROVIDERS:
        return this.providers;
      case LocalServiceRegistryImpl.LISTENERS:
        return this.listeners;
      case LocalServiceRegistryImpl.REMOTE:
        return this.remote;
      case LocalServiceRegistryImpl.CONNECTION_STATE:
        return this.connectionState;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LocalServiceRegistryImpl.REFERENCES:
        this.references = newValue as ServiceReference[];
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.REGISTRATIONS:
        this.registrations = newValue as ServiceRegistration[];
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.SESSIONS:
        this.sessions = newValue as ConsumerSession[];
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.CONFIGURATIONS:
        this.configurations = newValue as ComponentConfiguration[];
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.PROVIDERS:
        this.providers = newValue as ServiceProvider[];
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.LISTENERS:
        this.listeners = newValue as ServiceListener[];
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.REMOTE:
        this.remote = newValue as RemoteServiceRegistry;
        super.eSet(feature, newValue);
        break;
      case LocalServiceRegistryImpl.CONNECTION_STATE:
        this.connectionState = newValue as ConnectionState;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LocalServiceRegistryImpl.REFERENCES:
        return this._references !== undefined && this._references.length > 0;
      case LocalServiceRegistryImpl.REGISTRATIONS:
        return this._registrations !== undefined && this._registrations.length > 0;
      case LocalServiceRegistryImpl.SESSIONS:
        return this._sessions !== undefined && this._sessions.length > 0;
      case LocalServiceRegistryImpl.CONFIGURATIONS:
        return this._configurations !== undefined && this._configurations.length > 0;
      case LocalServiceRegistryImpl.PROVIDERS:
        return this._providers !== undefined && this._providers.length > 0;
      case LocalServiceRegistryImpl.LISTENERS:
        return this._listeners !== undefined && this._listeners.length > 0;
      case LocalServiceRegistryImpl.REMOTE:
        return this._remote !== undefined;
      case LocalServiceRegistryImpl.CONNECTION_STATE:
        return this._connectionState !== ConnectionState.OFFLINE;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case LocalServiceRegistryImpl.REFERENCES:
        this._references = [];
        return;
      case LocalServiceRegistryImpl.REGISTRATIONS:
        this._registrations = [];
        return;
      case LocalServiceRegistryImpl.SESSIONS:
        this._sessions = [];
        return;
      case LocalServiceRegistryImpl.CONFIGURATIONS:
        this._configurations = [];
        return;
      case LocalServiceRegistryImpl.PROVIDERS:
        this._providers = [];
        return;
      case LocalServiceRegistryImpl.LISTENERS:
        this._listeners = [];
        return;
      case LocalServiceRegistryImpl.REMOTE:
        this._remote = undefined;
        return;
      case LocalServiceRegistryImpl.CONNECTION_STATE:
        this._connectionState = ConnectionState.OFFLINE;
        return;
      default:
        super.eUnset(feature);
    }
  }

  registerService(provider: ServiceProvider, implementation: ServiceImplementation, props: Property): ServiceRegistration {
    throw new Error('registerService not implemented');
  }

  fireServiceEvent(event: ServiceEvent): void {
    throw new Error('fireServiceEvent not implemented');
  }

}
