/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceOperationFlavor } from './ServiceOperationFlavor';
import type { MqttQos } from './MqttQos';

/**
 * MqttOperationFlavor
 * @generated
 */
export interface MqttOperationFlavor extends ServiceOperationFlavor {
  requestTopic?: string;
  responseTopic?: string;
  qos?: MqttQos;
  retained?: boolean;
  correlation: boolean;
  returnPath?: string;

}
