/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceOperationFlavor } from './ServiceOperationFlavor';
import type { MqttQos } from './MqttQos';
import { ServiceOperationFlavorImpl } from './ServiceOperationFlavorImpl';
import type { MqttOperationFlavor } from './MqttOperationFlavor';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of MqttOperationFlavor
 * @generated
 */
export class MqttOperationFlavorImpl extends ServiceOperationFlavorImpl implements MqttOperationFlavor {
  // Feature ID Constants (eLiterals)
  static readonly REQUEST_TOPIC: number = 4;
  static readonly RESPONSE_TOPIC: number = 5;
  static readonly QOS: number = 6;
  static readonly RETAINED: number = 7;
  static readonly CORRELATION: number = 8;
  static readonly RETURN_PATH: number = 9;

  // Private fields
  private _requestTopic?: string;
  private _responseTopic?: string;
  private _qos?: MqttQos;
  private _retained?: boolean;
  private _correlation: boolean = true;
  private _returnPath?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.MQTT_OPERATION_FLAVOR;
  }

  // Getters and Setters
  get requestTopic(): string {
    return this._requestTopic!;
  }

  set requestTopic(value: string) {
    const oldValue = this._requestTopic;
    this._requestTopic = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttOperationFlavorImpl.REQUEST_TOPIC),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttOperationFlavorImpl.REQUEST_TOPIC,
        merge: () => false
      });
    }
  }

  get responseTopic(): string {
    return this._responseTopic!;
  }

  set responseTopic(value: string) {
    const oldValue = this._responseTopic;
    this._responseTopic = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttOperationFlavorImpl.RESPONSE_TOPIC),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttOperationFlavorImpl.RESPONSE_TOPIC,
        merge: () => false
      });
    }
  }

  get qos(): MqttQos {
    return this._qos!;
  }

  set qos(value: MqttQos) {
    const oldValue = this._qos;
    this._qos = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttOperationFlavorImpl.QOS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttOperationFlavorImpl.QOS,
        merge: () => false
      });
    }
  }

  get retained(): boolean {
    return this._retained!;
  }

  set retained(value: boolean) {
    const oldValue = this._retained;
    this._retained = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttOperationFlavorImpl.RETAINED),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttOperationFlavorImpl.RETAINED,
        merge: () => false
      });
    }
  }

  get correlation(): boolean {
    return this._correlation!;
  }

  set correlation(value: boolean) {
    const oldValue = this._correlation;
    this._correlation = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttOperationFlavorImpl.CORRELATION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttOperationFlavorImpl.CORRELATION,
        merge: () => false
      });
    }
  }

  get returnPath(): string {
    return this._returnPath!;
  }

  set returnPath(value: string) {
    const oldValue = this._returnPath;
    this._returnPath = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttOperationFlavorImpl.RETURN_PATH),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttOperationFlavorImpl.RETURN_PATH,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case MqttOperationFlavorImpl.REQUEST_TOPIC:
        return this.requestTopic;
      case MqttOperationFlavorImpl.RESPONSE_TOPIC:
        return this.responseTopic;
      case MqttOperationFlavorImpl.QOS:
        return this.qos;
      case MqttOperationFlavorImpl.RETAINED:
        return this.retained;
      case MqttOperationFlavorImpl.CORRELATION:
        return this.correlation;
      case MqttOperationFlavorImpl.RETURN_PATH:
        return this.returnPath;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case MqttOperationFlavorImpl.REQUEST_TOPIC:
        this.requestTopic = newValue as string;
        super.eSet(feature, newValue);
        break;
      case MqttOperationFlavorImpl.RESPONSE_TOPIC:
        this.responseTopic = newValue as string;
        super.eSet(feature, newValue);
        break;
      case MqttOperationFlavorImpl.QOS:
        this.qos = newValue as MqttQos;
        super.eSet(feature, newValue);
        break;
      case MqttOperationFlavorImpl.RETAINED:
        this.retained = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case MqttOperationFlavorImpl.CORRELATION:
        this.correlation = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case MqttOperationFlavorImpl.RETURN_PATH:
        this.returnPath = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case MqttOperationFlavorImpl.REQUEST_TOPIC:
        return this._requestTopic !== undefined;
      case MqttOperationFlavorImpl.RESPONSE_TOPIC:
        return this._responseTopic !== undefined;
      case MqttOperationFlavorImpl.QOS:
        return this._qos !== undefined;
      case MqttOperationFlavorImpl.RETAINED:
        return this._retained !== undefined;
      case MqttOperationFlavorImpl.CORRELATION:
        return this._correlation !== true;
      case MqttOperationFlavorImpl.RETURN_PATH:
        return this._returnPath !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case MqttOperationFlavorImpl.REQUEST_TOPIC:
        this._requestTopic = undefined;
        return;
      case MqttOperationFlavorImpl.RESPONSE_TOPIC:
        this._responseTopic = undefined;
        return;
      case MqttOperationFlavorImpl.QOS:
        this._qos = undefined;
        return;
      case MqttOperationFlavorImpl.RETAINED:
        this._retained = undefined;
        return;
      case MqttOperationFlavorImpl.CORRELATION:
        this._correlation = true;
        return;
      case MqttOperationFlavorImpl.RETURN_PATH:
        this._returnPath = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
