/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * MqttQos
 * @generated
 */
export const MqttQos = {
  AT_MOST_ONCE: 'AT_MOST_ONCE',
  AT_LEAST_ONCE: 'AT_LEAST_ONCE',
  EXACTLY_ONCE: 'EXACTLY_ONCE'
} as const;

export type MqttQos = typeof MqttQos[keyof typeof MqttQos];

/**
 * Get enum value by name
 */
export function getMqttQos(name: string): MqttQos | undefined {
  return (MqttQos as Record<string, string>)[name] as MqttQos | undefined;
}

/**
 * Get enum value by literal
 */
export function getMqttQosByLiteral(literal: string): MqttQos | undefined {
  if (literal === 'AT_MOST_ONCE') return MqttQos.AT_MOST_ONCE;
  if (literal === 'AT_LEAST_ONCE') return MqttQos.AT_LEAST_ONCE;
  if (literal === 'EXACTLY_ONCE') return MqttQos.EXACTLY_ONCE;
  return undefined;
}
