/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceFlavor } from './ServiceFlavor';
import { MqttQos } from './MqttQos';
import { ServiceFlavorImpl } from './ServiceFlavorImpl';
import type { MqttFlavor } from './MqttFlavor';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of MqttFlavor
 * @generated
 */
export class MqttFlavorImpl extends ServiceFlavorImpl implements MqttFlavor {
  // Feature ID Constants (eLiterals)
  static readonly BROKERS: number = 3;
  static readonly REQUEST_TOPIC: number = 4;
  static readonly RESPONSE_TOPIC: number = 5;
  static readonly DEFAULT_QOS: number = 6;
  static readonly DEFAULT_RETAINED: number = 7;

  // Private fields
  private _brokers: string[] = [];
  private _requestTopic: string = "";
  private _responseTopic?: string;
  private _defaultQos: MqttQos = MqttQos.AT_LEAST_ONCE;
  private _defaultRetained: boolean = false;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.MQTT_FLAVOR;
  }

  // Getters and Setters
  get brokers(): string[] {
    return this._brokers;
  }

  set brokers(value: string[]) {
    const oldValue = this._brokers;
    this._brokers = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttFlavorImpl.BROKERS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttFlavorImpl.BROKERS,
        merge: () => false
      });
    }
  }

  get requestTopic(): string {
    return this._requestTopic!;
  }

  set requestTopic(value: string) {
    const oldValue = this._requestTopic;
    this._requestTopic = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttFlavorImpl.REQUEST_TOPIC),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttFlavorImpl.REQUEST_TOPIC,
        merge: () => false
      });
    }
  }

  get responseTopic(): string {
    return this._responseTopic!;
  }

  set responseTopic(value: string) {
    const oldValue = this._responseTopic;
    this._responseTopic = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttFlavorImpl.RESPONSE_TOPIC),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttFlavorImpl.RESPONSE_TOPIC,
        merge: () => false
      });
    }
  }

  get defaultQos(): MqttQos {
    return this._defaultQos!;
  }

  set defaultQos(value: MqttQos) {
    const oldValue = this._defaultQos;
    this._defaultQos = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttFlavorImpl.DEFAULT_QOS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttFlavorImpl.DEFAULT_QOS,
        merge: () => false
      });
    }
  }

  get defaultRetained(): boolean {
    return this._defaultRetained!;
  }

  set defaultRetained(value: boolean) {
    const oldValue = this._defaultRetained;
    this._defaultRetained = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(MqttFlavorImpl.DEFAULT_RETAINED),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => MqttFlavorImpl.DEFAULT_RETAINED,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case MqttFlavorImpl.BROKERS:
        return this.brokers;
      case MqttFlavorImpl.REQUEST_TOPIC:
        return this.requestTopic;
      case MqttFlavorImpl.RESPONSE_TOPIC:
        return this.responseTopic;
      case MqttFlavorImpl.DEFAULT_QOS:
        return this.defaultQos;
      case MqttFlavorImpl.DEFAULT_RETAINED:
        return this.defaultRetained;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case MqttFlavorImpl.BROKERS:
        this.brokers = newValue as string[];
        super.eSet(feature, newValue);
        break;
      case MqttFlavorImpl.REQUEST_TOPIC:
        this.requestTopic = newValue as string;
        super.eSet(feature, newValue);
        break;
      case MqttFlavorImpl.RESPONSE_TOPIC:
        this.responseTopic = newValue as string;
        super.eSet(feature, newValue);
        break;
      case MqttFlavorImpl.DEFAULT_QOS:
        this.defaultQos = newValue as MqttQos;
        super.eSet(feature, newValue);
        break;
      case MqttFlavorImpl.DEFAULT_RETAINED:
        this.defaultRetained = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case MqttFlavorImpl.BROKERS:
        return this._brokers !== undefined && this._brokers.length > 0;
      case MqttFlavorImpl.REQUEST_TOPIC:
        return this._requestTopic !== "";
      case MqttFlavorImpl.RESPONSE_TOPIC:
        return this._responseTopic !== undefined;
      case MqttFlavorImpl.DEFAULT_QOS:
        return this._defaultQos !== MqttQos.AT_LEAST_ONCE;
      case MqttFlavorImpl.DEFAULT_RETAINED:
        return this._defaultRetained !== false;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case MqttFlavorImpl.BROKERS:
        this._brokers = [];
        return;
      case MqttFlavorImpl.REQUEST_TOPIC:
        this._requestTopic = "";
        return;
      case MqttFlavorImpl.RESPONSE_TOPIC:
        this._responseTopic = undefined;
        return;
      case MqttFlavorImpl.DEFAULT_QOS:
        this._defaultQos = MqttQos.AT_LEAST_ONCE;
        return;
      case MqttFlavorImpl.DEFAULT_RETAINED:
        this._defaultRetained = false;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
