/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ParameterConstraint } from './ParameterConstraint';
import { ParameterConstraintImpl } from './ParameterConstraintImpl';
import type { NumericRangeConstraint } from './NumericRangeConstraint';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of NumericRangeConstraint
 * @generated
 */
export class NumericRangeConstraintImpl extends ParameterConstraintImpl implements NumericRangeConstraint {
  // Feature ID Constants (eLiterals)
  static readonly MIN: number = 0;
  static readonly MAX: number = 1;
  static readonly INCLUSIVE_MIN: number = 2;
  static readonly INCLUSIVE_MAX: number = 3;

  // Private fields
  private _min?: number;
  private _max?: number;
  private _inclusiveMin: boolean = true;
  private _inclusiveMax: boolean = true;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.NUMERIC_RANGE_CONSTRAINT;
  }

  // Getters and Setters
  get min(): number {
    return this._min!;
  }

  set min(value: number) {
    const oldValue = this._min;
    this._min = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(NumericRangeConstraintImpl.MIN),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => NumericRangeConstraintImpl.MIN,
        merge: () => false
      });
    }
  }

  get max(): number {
    return this._max!;
  }

  set max(value: number) {
    const oldValue = this._max;
    this._max = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(NumericRangeConstraintImpl.MAX),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => NumericRangeConstraintImpl.MAX,
        merge: () => false
      });
    }
  }

  get inclusiveMin(): boolean {
    return this._inclusiveMin!;
  }

  set inclusiveMin(value: boolean) {
    const oldValue = this._inclusiveMin;
    this._inclusiveMin = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(NumericRangeConstraintImpl.INCLUSIVE_MIN),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => NumericRangeConstraintImpl.INCLUSIVE_MIN,
        merge: () => false
      });
    }
  }

  get inclusiveMax(): boolean {
    return this._inclusiveMax!;
  }

  set inclusiveMax(value: boolean) {
    const oldValue = this._inclusiveMax;
    this._inclusiveMax = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(NumericRangeConstraintImpl.INCLUSIVE_MAX),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => NumericRangeConstraintImpl.INCLUSIVE_MAX,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case NumericRangeConstraintImpl.MIN:
        return this.min;
      case NumericRangeConstraintImpl.MAX:
        return this.max;
      case NumericRangeConstraintImpl.INCLUSIVE_MIN:
        return this.inclusiveMin;
      case NumericRangeConstraintImpl.INCLUSIVE_MAX:
        return this.inclusiveMax;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case NumericRangeConstraintImpl.MIN:
        this.min = newValue as number;
        super.eSet(feature, newValue);
        break;
      case NumericRangeConstraintImpl.MAX:
        this.max = newValue as number;
        super.eSet(feature, newValue);
        break;
      case NumericRangeConstraintImpl.INCLUSIVE_MIN:
        this.inclusiveMin = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case NumericRangeConstraintImpl.INCLUSIVE_MAX:
        this.inclusiveMax = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case NumericRangeConstraintImpl.MIN:
        return this._min !== undefined;
      case NumericRangeConstraintImpl.MAX:
        return this._max !== undefined;
      case NumericRangeConstraintImpl.INCLUSIVE_MIN:
        return this._inclusiveMin !== true;
      case NumericRangeConstraintImpl.INCLUSIVE_MAX:
        return this._inclusiveMax !== true;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case NumericRangeConstraintImpl.MIN:
        this._min = undefined;
        return;
      case NumericRangeConstraintImpl.MAX:
        this._max = undefined;
        return;
      case NumericRangeConstraintImpl.INCLUSIVE_MIN:
        this._inclusiveMin = true;
        return;
      case NumericRangeConstraintImpl.INCLUSIVE_MAX:
        this._inclusiveMax = true;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
