/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { PackageMapping } from './PackageMapping.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of PackageMapping
 * @generated
 */
export class PackageMappingImpl extends BasicEObject implements PackageMapping {
  // Feature ID Constants (eLiterals)
  static readonly NS_U_R_I: number = 0;
  static readonly TARGET: number = 1;

  // Private fields
  private _nsURI: string = "";
  private _target: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.PACKAGE_MAPPING;
  }

  // Getters and Setters
  get nsURI(): string {
    return this._nsURI!;
  }

  set nsURI(value: string) {
    const oldValue = this._nsURI;
    this._nsURI = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(PackageMappingImpl.NS_U_R_I),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => PackageMappingImpl.NS_U_R_I,
        merge: () => false
      });
    }
  }

  get target(): string {
    return this._target!;
  }

  set target(value: string) {
    const oldValue = this._target;
    this._target = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(PackageMappingImpl.TARGET),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => PackageMappingImpl.TARGET,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PackageMappingImpl.NS_U_R_I:
        return this.nsURI;
      case PackageMappingImpl.TARGET:
        return this.target;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PackageMappingImpl.NS_U_R_I:
        this.nsURI = newValue as string;
        super.eSet(feature, newValue);
        break;
      case PackageMappingImpl.TARGET:
        this.target = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PackageMappingImpl.NS_U_R_I:
        return this._nsURI !== "";
      case PackageMappingImpl.TARGET:
        return this._target !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PackageMappingImpl.NS_U_R_I:
        this._nsURI = "";
        return;
      case PackageMappingImpl.TARGET:
        this._target = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
