/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EClassifier, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { ParameterConstraint } from './ParameterConstraint';

/**
 * Parameter
 * @generated
 */
export interface Parameter extends NamedElement {
  index: number;
  type?: string;
  eType?: EClassifier;
  lowerBound?: number;
  upperBound?: number;
  optional: boolean;
  defaultValue?: string;
  description?: string;
  constraints: ParameterConstraint[];

}
