/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { ParameterConstraint } from './ParameterConstraint';
import type { Parameter } from './Parameter';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of Parameter
 * @generated
 */
export class ParameterImpl extends BasicEObject implements Parameter {
  // Feature ID Constants (eLiterals)
  static readonly INDEX: number = 1;
  static readonly TYPE: number = 2;
  static readonly OPTIONAL: number = 3;
  static readonly DEFAULT_VALUE: number = 4;
  static readonly DESCRIPTION: number = 5;
  static readonly CONSTRAINTS: number = 6;
  static readonly NAME: number = 0;

  // Private fields
  private _index: number = 0;
  private _type: string = "";
  private _optional: boolean = false;
  private _defaultValue?: string;
  private _description?: string;
  private _constraints: ParameterConstraint[] = [];
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.PARAMETER;
  }

  // Getters and Setters
  get index(): number {
    return this._index!;
  }

  set index(value: number) {
    const oldValue = this._index;
    this._index = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ParameterImpl.INDEX),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ParameterImpl.INDEX,
        merge: () => false
      });
    }
  }

  get type(): string {
    return this._type!;
  }

  set type(value: string) {
    const oldValue = this._type;
    this._type = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ParameterImpl.TYPE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ParameterImpl.TYPE,
        merge: () => false
      });
    }
  }

  get optional(): boolean {
    return this._optional!;
  }

  set optional(value: boolean) {
    const oldValue = this._optional;
    this._optional = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ParameterImpl.OPTIONAL),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ParameterImpl.OPTIONAL,
        merge: () => false
      });
    }
  }

  get defaultValue(): string {
    return this._defaultValue!;
  }

  set defaultValue(value: string) {
    const oldValue = this._defaultValue;
    this._defaultValue = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ParameterImpl.DEFAULT_VALUE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ParameterImpl.DEFAULT_VALUE,
        merge: () => false
      });
    }
  }

  get description(): string {
    return this._description!;
  }

  set description(value: string) {
    const oldValue = this._description;
    this._description = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ParameterImpl.DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ParameterImpl.DESCRIPTION,
        merge: () => false
      });
    }
  }

  get constraints(): ParameterConstraint[] {
    return this._constraints;
  }

  set constraints(value: ParameterConstraint[]) {
    const oldValue = this._constraints;
    this._constraints = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ParameterImpl.CONSTRAINTS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ParameterImpl.CONSTRAINTS,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ParameterImpl.INDEX:
        return this.index;
      case ParameterImpl.TYPE:
        return this.type;
      case ParameterImpl.OPTIONAL:
        return this.optional;
      case ParameterImpl.DEFAULT_VALUE:
        return this.defaultValue;
      case ParameterImpl.DESCRIPTION:
        return this.description;
      case ParameterImpl.CONSTRAINTS:
        return this.constraints;
      case ParameterImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ParameterImpl.INDEX:
        this.index = newValue as number;
        super.eSet(feature, newValue);
        break;
      case ParameterImpl.TYPE:
        this.type = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ParameterImpl.OPTIONAL:
        this.optional = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case ParameterImpl.DEFAULT_VALUE:
        this.defaultValue = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ParameterImpl.DESCRIPTION:
        this.description = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ParameterImpl.CONSTRAINTS:
        this.constraints = newValue as ParameterConstraint[];
        super.eSet(feature, newValue);
        break;
      case ParameterImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ParameterImpl.INDEX:
        return this._index !== 0;
      case ParameterImpl.TYPE:
        return this._type !== "";
      case ParameterImpl.OPTIONAL:
        return this._optional !== false;
      case ParameterImpl.DEFAULT_VALUE:
        return this._defaultValue !== undefined;
      case ParameterImpl.DESCRIPTION:
        return this._description !== undefined;
      case ParameterImpl.CONSTRAINTS:
        return this._constraints !== undefined && this._constraints.length > 0;
      case ParameterImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ParameterImpl.INDEX:
        this._index = 0;
        return;
      case ParameterImpl.TYPE:
        this._type = "";
        return;
      case ParameterImpl.OPTIONAL:
        this._optional = false;
        return;
      case ParameterImpl.DEFAULT_VALUE:
        this._defaultValue = undefined;
        return;
      case ParameterImpl.DESCRIPTION:
        this._description = undefined;
        return;
      case ParameterImpl.CONSTRAINTS:
        this._constraints = [];
        return;
      case ParameterImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
