/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ParameterBinding
 * @generated
 */
export const ParameterBinding = {
  BODY: 'BODY',
  QUERY: 'QUERY',
  HEADER: 'HEADER',
  PATH: 'PATH'
} as const;

export type ParameterBinding = typeof ParameterBinding[keyof typeof ParameterBinding];

/**
 * Get enum value by name
 */
export function getParameterBinding(name: string): ParameterBinding | undefined {
  return (ParameterBinding as Record<string, string>)[name] as ParameterBinding | undefined;
}

/**
 * Get enum value by literal
 */
export function getParameterBindingByLiteral(literal: string): ParameterBinding | undefined {
  if (literal === 'BODY') return ParameterBinding.BODY;
  if (literal === 'QUERY') return ParameterBinding.QUERY;
  if (literal === 'HEADER') return ParameterBinding.HEADER;
  if (literal === 'PATH') return ParameterBinding.PATH;
  return undefined;
}
