/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { Property } from './Property';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of Property
 * @generated
 */
export abstract class PropertyImpl extends BasicEObject implements Property {
  // Feature ID Constants (eLiterals)
  static readonly NAME: number = 0;

  // Private fields
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.PROPERTY;
  }

  // Getters and Setters
  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PropertyImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PropertyImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PropertyImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case PropertyImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
