/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Diagnostic } from './Diagnostic';
import type { ServiceProvider } from './ServiceProvider';
import type { ServiceImplementation } from './ServiceImplementation';

/**
 * PublishHook
 * @generated
 */
export interface PublishHook extends EObject {

  onPublish(provider: ServiceProvider, implementation: ServiceImplementation): Diagnostic;
  onWithdraw(provider: ServiceProvider, implementation: ServiceImplementation): Diagnostic;
}
