/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { LanguageBinding } from './LanguageBinding';

/**
 * PythonBinding
 * @generated
 */
export interface PythonBinding extends LanguageBinding {

}
