/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { ReferenceBindingKind } from './ReferenceBindingKind';
import type { FieldOption } from './FieldOption';

/**
 * ReferenceBinding
 * @generated
 */
export interface ReferenceBinding extends NamedElement {
  kind: ReferenceBindingKind;
  fieldOption?: FieldOption;

}
