/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ReferenceBindingKind
 * @generated
 */
export const ReferenceBindingKind = {
  BIND: 'BIND',
  UNBIND: 'UNBIND',
  UPDATED: 'UPDATED',
  FIELD: 'FIELD'
} as const;

export type ReferenceBindingKind = typeof ReferenceBindingKind[keyof typeof ReferenceBindingKind];

/**
 * Get enum value by name
 */
export function getReferenceBindingKind(name: string): ReferenceBindingKind | undefined {
  return (ReferenceBindingKind as Record<string, string>)[name] as ReferenceBindingKind | undefined;
}

/**
 * Get enum value by literal
 */
export function getReferenceBindingKindByLiteral(literal: string): ReferenceBindingKind | undefined {
  if (literal === 'BIND') return ReferenceBindingKind.BIND;
  if (literal === 'UNBIND') return ReferenceBindingKind.UNBIND;
  if (literal === 'UPDATED') return ReferenceBindingKind.UPDATED;
  if (literal === 'FIELD') return ReferenceBindingKind.FIELD;
  return undefined;
}
