/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ReferencePolicy
 * @generated
 */
export const ReferencePolicy = {
  STATIC: 'STATIC',
  DYNAMIC: 'DYNAMIC'
} as const;

export type ReferencePolicy = typeof ReferencePolicy[keyof typeof ReferencePolicy];

/**
 * Get enum value by name
 */
export function getReferencePolicy(name: string): ReferencePolicy | undefined {
  return (ReferencePolicy as Record<string, string>)[name] as ReferencePolicy | undefined;
}

/**
 * Get enum value by literal
 */
export function getReferencePolicyByLiteral(literal: string): ReferencePolicy | undefined {
  if (literal === 'STATIC') return ReferencePolicy.STATIC;
  if (literal === 'DYNAMIC') return ReferencePolicy.DYNAMIC;
  return undefined;
}
