/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ReferenceCardinality
 * @generated
 */
export const ReferenceCardinality = {
  ZERO_OR_ONE: 'ZERO_OR_ONE',
  ONE: 'ONE',
  ZERO_OR_MANY: 'ZERO_OR_MANY',
  ONE_OR_MANY: 'ONE_OR_MANY'
} as const;

export type ReferenceCardinality = typeof ReferenceCardinality[keyof typeof ReferenceCardinality];

/**
 * Get enum value by name
 */
export function getReferenceCardinality(name: string): ReferenceCardinality | undefined {
  return (ReferenceCardinality as Record<string, string>)[name] as ReferenceCardinality | undefined;
}

/**
 * Get enum value by literal
 */
export function getReferenceCardinalityByLiteral(literal: string): ReferenceCardinality | undefined {
  if (literal === 'ZERO_OR_ONE') return ReferenceCardinality.ZERO_OR_ONE;
  if (literal === 'ONE') return ReferenceCardinality.ONE;
  if (literal === 'ZERO_OR_MANY') return ReferenceCardinality.ZERO_OR_MANY;
  if (literal === 'ONE_OR_MANY') return ReferenceCardinality.ONE_OR_MANY;
  return undefined;
}
