/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ReferencePolicyOption
 * @generated
 */
export const ReferencePolicyOption = {
  RELUCTANT: 'RELUCTANT',
  GREEDY: 'GREEDY'
} as const;

export type ReferencePolicyOption = typeof ReferencePolicyOption[keyof typeof ReferencePolicyOption];

/**
 * Get enum value by name
 */
export function getReferencePolicyOption(name: string): ReferencePolicyOption | undefined {
  return (ReferencePolicyOption as Record<string, string>)[name] as ReferencePolicyOption | undefined;
}

/**
 * Get enum value by literal
 */
export function getReferencePolicyOptionByLiteral(literal: string): ReferencePolicyOption | undefined {
  if (literal === 'RELUCTANT') return ReferencePolicyOption.RELUCTANT;
  if (literal === 'GREEDY') return ReferencePolicyOption.GREEDY;
  return undefined;
}
