/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceRegistry } from './ServiceRegistry';
import type { ServiceInterface } from './ServiceInterface';
import type { ServiceImplementation } from './ServiceImplementation';
import type { ServiceProvider } from './ServiceProvider';
import type { Diagnostic } from './Diagnostic';

/**
 * RemoteServiceRegistry
 * @generated
 */
export interface RemoteServiceRegistry extends ServiceRegistry {
  endpoint?: string;
  catalog: ServiceInterface[];
  implementations: ServiceImplementation[];
  providers: ServiceProvider[];

  publishImplementation(provider: ServiceProvider, implementation: ServiceImplementation): Diagnostic;
  withdrawImplementation(provider: ServiceProvider, implementation: ServiceImplementation): Diagnostic;
  addCatalogEntry(serviceInterface: ServiceInterface, requestor: string): Diagnostic;
  deprecateCatalogEntry(serviceInterface: ServiceInterface, requestor: string): Diagnostic;
  removeCatalogEntry(serviceInterface: ServiceInterface, requestor: string): Diagnostic;
}
