/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { createContainmentEList, createEObjectEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { ServiceRegistry } from './ServiceRegistry.js';
import type { ServiceInterface } from './ServiceInterface.js';
import type { ServiceImplementation } from './ServiceImplementation.js';
import type { ServiceProvider } from './ServiceProvider.js';
import type { Diagnostic } from './Diagnostic.js';
import { ServiceRegistryImpl } from './ServiceRegistryImpl.js';
import type { RemoteServiceRegistry } from './RemoteServiceRegistry.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of RemoteServiceRegistry
 * @generated
 */
export class RemoteServiceRegistryImpl extends ServiceRegistryImpl implements RemoteServiceRegistry {
  // Feature ID Constants (eLiterals)
  static readonly ENDPOINT: number = 5;
  static readonly CATALOG: number = 6;
  static readonly IMPLEMENTATIONS: number = 7;
  static readonly PROVIDERS: number = 8;

  // Private fields
  private _endpoint?: string;
  private _catalog!: EList<ServiceInterface>;
  private _implementations!: EList<ServiceImplementation>;
  private _providers!: EList<ServiceProvider>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.REMOTE_SERVICE_REGISTRY;
  }

  // Getters and Setters
  get endpoint(): string {
    return this._endpoint!;
  }

  set endpoint(value: string) {
    const oldValue = this._endpoint;
    this._endpoint = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RemoteServiceRegistryImpl.ENDPOINT),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RemoteServiceRegistryImpl.ENDPOINT,
        merge: () => false
      });
    }
  }

  get catalog(): EList<ServiceInterface> {
    if (!this._catalog) {
      this._catalog = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('catalog') as EReference);
    }
    return this._catalog;
  }

  get implementations(): EList<ServiceImplementation> {
    if (!this._implementations) {
      this._implementations = createEObjectEList(this, this.eClass().getEStructuralFeature('implementations') as EReference) as unknown as EList<ServiceImplementation>;
    }
    return this._implementations;
  }

  get providers(): EList<ServiceProvider> {
    if (!this._providers) {
      this._providers = createEObjectEList(this, this.eClass().getEStructuralFeature('providers') as EReference) as unknown as EList<ServiceProvider>;
    }
    return this._providers;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RemoteServiceRegistryImpl.ENDPOINT:
        return this.endpoint;
      case RemoteServiceRegistryImpl.CATALOG:
        return this.catalog;
      case RemoteServiceRegistryImpl.IMPLEMENTATIONS:
        return this.implementations;
      case RemoteServiceRegistryImpl.PROVIDERS:
        return this.providers;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RemoteServiceRegistryImpl.ENDPOINT:
        this.endpoint = newValue as string;
        super.eSet(feature, newValue);
        break;
      case RemoteServiceRegistryImpl.CATALOG:
        this.catalog.clear();
        this.catalog.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case RemoteServiceRegistryImpl.IMPLEMENTATIONS:
        this.implementations.clear();
        this.implementations.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case RemoteServiceRegistryImpl.PROVIDERS:
        this.providers.clear();
        this.providers.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RemoteServiceRegistryImpl.ENDPOINT:
        return this._endpoint !== undefined;
      case RemoteServiceRegistryImpl.CATALOG:
        return this._catalog !== undefined && !this._catalog.isEmpty();
      case RemoteServiceRegistryImpl.IMPLEMENTATIONS:
        return this._implementations !== undefined && !this._implementations.isEmpty();
      case RemoteServiceRegistryImpl.PROVIDERS:
        return this._providers !== undefined && !this._providers.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RemoteServiceRegistryImpl.ENDPOINT:
        this._endpoint = undefined;
        return;
      case RemoteServiceRegistryImpl.CATALOG:
        if (this._catalog) this._catalog.clear();
        return;
      case RemoteServiceRegistryImpl.IMPLEMENTATIONS:
        if (this._implementations) this._implementations.clear();
        return;
      case RemoteServiceRegistryImpl.PROVIDERS:
        if (this._providers) this._providers.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

  publishImplementation(provider: ServiceProvider, implementation: ServiceImplementation): Diagnostic {
    throw new Error('publishImplementation not implemented');
  }

  withdrawImplementation(provider: ServiceProvider, implementation: ServiceImplementation): Diagnostic {
    throw new Error('withdrawImplementation not implemented');
  }

  addCatalogEntry(serviceInterface: ServiceInterface, requestor: string): Diagnostic {
    throw new Error('addCatalogEntry not implemented');
  }

  deprecateCatalogEntry(serviceInterface: ServiceInterface, requestor: string): Diagnostic {
    throw new Error('deprecateCatalogEntry not implemented');
  }

  removeCatalogEntry(serviceInterface: ServiceInterface, requestor: string): Diagnostic {
    throw new Error('removeCatalogEntry not implemented');
  }

}
