/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';

/**
 * Requirement
 * @generated
 */
export interface Requirement extends EObject {
  namespace: string;
  filter?: string;
  optional?: boolean;

}
