/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { Parameter } from './Parameter';
import type { ParameterBinding } from './ParameterBinding';
import type { RestParameterBinding } from './RestParameterBinding';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of RestParameterBinding
 * @generated
 */
export class RestParameterBindingImpl extends BasicEObject implements RestParameterBinding {
  // Feature ID Constants (eLiterals)
  static readonly PARAMETER: number = 0;
  static readonly BINDING: number = 1;
  static readonly WIRE_NAME: number = 2;

  // Private fields
  private _parameter?: Parameter;
  private _binding?: ParameterBinding;
  private _wireName?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.REST_PARAMETER_BINDING;
  }

  // Getters and Setters
  get parameter(): Parameter {
    return this._parameter!;
  }

  set parameter(value: Parameter) {
    const oldValue = this._parameter;
    this._parameter = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestParameterBindingImpl.PARAMETER),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestParameterBindingImpl.PARAMETER,
        merge: () => false
      });
    }
  }

  get binding(): ParameterBinding {
    return this._binding!;
  }

  set binding(value: ParameterBinding) {
    const oldValue = this._binding;
    this._binding = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestParameterBindingImpl.BINDING),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestParameterBindingImpl.BINDING,
        merge: () => false
      });
    }
  }

  get wireName(): string {
    return this._wireName!;
  }

  set wireName(value: string) {
    const oldValue = this._wireName;
    this._wireName = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestParameterBindingImpl.WIRE_NAME),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestParameterBindingImpl.WIRE_NAME,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestParameterBindingImpl.PARAMETER:
        return this.parameter;
      case RestParameterBindingImpl.BINDING:
        return this.binding;
      case RestParameterBindingImpl.WIRE_NAME:
        return this.wireName;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestParameterBindingImpl.PARAMETER:
        this.parameter = newValue as Parameter;
        super.eSet(feature, newValue);
        break;
      case RestParameterBindingImpl.BINDING:
        this.binding = newValue as ParameterBinding;
        super.eSet(feature, newValue);
        break;
      case RestParameterBindingImpl.WIRE_NAME:
        this.wireName = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestParameterBindingImpl.PARAMETER:
        return this._parameter !== undefined;
      case RestParameterBindingImpl.BINDING:
        return this._binding !== undefined;
      case RestParameterBindingImpl.WIRE_NAME:
        return this._wireName !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestParameterBindingImpl.PARAMETER:
        this._parameter = undefined;
        return;
      case RestParameterBindingImpl.BINDING:
        this._binding = undefined;
        return;
      case RestParameterBindingImpl.WIRE_NAME:
        this._wireName = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
