/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceFlavor } from './ServiceFlavor.js';

/**
 * RestFlavor
 * @generated
 */
export interface RestFlavor extends ServiceFlavor {
  host?: string;
  basePath: string;
  contentTypes: EList<string>;

}
