/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { createContainmentEList, createBasicEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { ServiceOperationFlavor } from './ServiceOperationFlavor.js';
import type { RestParameterBinding } from './RestParameterBinding.js';
import type { RestExceptionBinding } from './RestExceptionBinding.js';
import { HttpMethod } from './HttpMethod.js';
import { ServiceOperationFlavorImpl } from './ServiceOperationFlavorImpl.js';
import type { RestOperationFlavor } from './RestOperationFlavor.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of RestOperationFlavor
 * @generated
 */
export class RestOperationFlavorImpl extends ServiceOperationFlavorImpl implements RestOperationFlavor {
  // Feature ID Constants (eLiterals)
  static readonly METHOD: number = 4;
  static readonly PATH: number = 5;
  static readonly RETURN_CODES: number = 6;
  static readonly PARAMETER_BINDINGS: number = 7;
  static readonly EXCEPTION_BINDINGS: number = 8;

  // Private fields
  private _method: HttpMethod = HttpMethod.GET;
  private _path?: string;
  private _returnCodes!: EList<number>;
  private _parameterBindings!: EList<RestParameterBinding>;
  private _exceptionBindings!: EList<RestExceptionBinding>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.REST_OPERATION_FLAVOR;
  }

  // Getters and Setters
  get method(): HttpMethod {
    return this._method!;
  }

  set method(value: HttpMethod) {
    const oldValue = this._method;
    this._method = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestOperationFlavorImpl.METHOD),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestOperationFlavorImpl.METHOD,
        merge: () => false
      });
    }
  }

  get path(): string {
    return this._path!;
  }

  set path(value: string) {
    const oldValue = this._path;
    this._path = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestOperationFlavorImpl.PATH),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestOperationFlavorImpl.PATH,
        merge: () => false
      });
    }
  }

  get returnCodes(): EList<number> {
    if (!this._returnCodes) {
      this._returnCodes = createBasicEList<any>(this, this.eClass().getEStructuralFeature('returnCodes')!);
    }
    return this._returnCodes;
  }

  get parameterBindings(): EList<RestParameterBinding> {
    if (!this._parameterBindings) {
      this._parameterBindings = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('parameterBindings') as EReference);
    }
    return this._parameterBindings;
  }

  get exceptionBindings(): EList<RestExceptionBinding> {
    if (!this._exceptionBindings) {
      this._exceptionBindings = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('exceptionBindings') as EReference);
    }
    return this._exceptionBindings;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestOperationFlavorImpl.METHOD:
        return this.method;
      case RestOperationFlavorImpl.PATH:
        return this.path;
      case RestOperationFlavorImpl.RETURN_CODES:
        return this.returnCodes;
      case RestOperationFlavorImpl.PARAMETER_BINDINGS:
        return this.parameterBindings;
      case RestOperationFlavorImpl.EXCEPTION_BINDINGS:
        return this.exceptionBindings;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestOperationFlavorImpl.METHOD:
        this.method = newValue as HttpMethod;
        super.eSet(feature, newValue);
        break;
      case RestOperationFlavorImpl.PATH:
        this.path = newValue as string;
        super.eSet(feature, newValue);
        break;
      case RestOperationFlavorImpl.RETURN_CODES:
        this.returnCodes.clear();
        this.returnCodes.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case RestOperationFlavorImpl.PARAMETER_BINDINGS:
        this.parameterBindings.clear();
        this.parameterBindings.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case RestOperationFlavorImpl.EXCEPTION_BINDINGS:
        this.exceptionBindings.clear();
        this.exceptionBindings.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestOperationFlavorImpl.METHOD:
        return this._method !== HttpMethod.GET;
      case RestOperationFlavorImpl.PATH:
        return this._path !== undefined;
      case RestOperationFlavorImpl.RETURN_CODES:
        return this._returnCodes !== undefined && !this._returnCodes.isEmpty();
      case RestOperationFlavorImpl.PARAMETER_BINDINGS:
        return this._parameterBindings !== undefined && !this._parameterBindings.isEmpty();
      case RestOperationFlavorImpl.EXCEPTION_BINDINGS:
        return this._exceptionBindings !== undefined && !this._exceptionBindings.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestOperationFlavorImpl.METHOD:
        this._method = HttpMethod.GET;
        return;
      case RestOperationFlavorImpl.PATH:
        this._path = undefined;
        return;
      case RestOperationFlavorImpl.RETURN_CODES:
        if (this._returnCodes) this._returnCodes.clear();
        return;
      case RestOperationFlavorImpl.PARAMETER_BINDINGS:
        if (this._parameterBindings) this._parameterBindings.clear();
        return;
      case RestOperationFlavorImpl.EXCEPTION_BINDINGS:
        if (this._exceptionBindings) this._exceptionBindings.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

}
