/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceFlavor } from './ServiceFlavor';
import { ServiceFlavorImpl } from './ServiceFlavorImpl';
import type { RestFlavor } from './RestFlavor';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of RestFlavor
 * @generated
 */
export class RestFlavorImpl extends ServiceFlavorImpl implements RestFlavor {
  // Feature ID Constants (eLiterals)
  static readonly HOST: number = 3;
  static readonly BASE_PATH: number = 4;
  static readonly CONTENT_TYPES: number = 5;

  // Private fields
  private _host?: string;
  private _basePath: string = "";
  private _contentTypes: string[] = [];

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.REST_FLAVOR;
  }

  // Getters and Setters
  get host(): string {
    return this._host!;
  }

  set host(value: string) {
    const oldValue = this._host;
    this._host = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestFlavorImpl.HOST),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestFlavorImpl.HOST,
        merge: () => false
      });
    }
  }

  get basePath(): string {
    return this._basePath!;
  }

  set basePath(value: string) {
    const oldValue = this._basePath;
    this._basePath = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestFlavorImpl.BASE_PATH),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestFlavorImpl.BASE_PATH,
        merge: () => false
      });
    }
  }

  get contentTypes(): string[] {
    return this._contentTypes;
  }

  set contentTypes(value: string[]) {
    const oldValue = this._contentTypes;
    this._contentTypes = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestFlavorImpl.CONTENT_TYPES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestFlavorImpl.CONTENT_TYPES,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestFlavorImpl.HOST:
        return this.host;
      case RestFlavorImpl.BASE_PATH:
        return this.basePath;
      case RestFlavorImpl.CONTENT_TYPES:
        return this.contentTypes;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestFlavorImpl.HOST:
        this.host = newValue as string;
        super.eSet(feature, newValue);
        break;
      case RestFlavorImpl.BASE_PATH:
        this.basePath = newValue as string;
        super.eSet(feature, newValue);
        break;
      case RestFlavorImpl.CONTENT_TYPES:
        this.contentTypes = newValue as string[];
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestFlavorImpl.HOST:
        return this._host !== undefined;
      case RestFlavorImpl.BASE_PATH:
        return this._basePath !== "";
      case RestFlavorImpl.CONTENT_TYPES:
        return this._contentTypes !== undefined && this._contentTypes.length > 0;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestFlavorImpl.HOST:
        this._host = undefined;
        return;
      case RestFlavorImpl.BASE_PATH:
        this._basePath = "";
        return;
      case RestFlavorImpl.CONTENT_TYPES:
        this._contentTypes = [];
        return;
      default:
        super.eUnset(feature);
    }
  }

}
