/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Parameter } from './Parameter.js';
import type { ParameterBinding } from './ParameterBinding.js';

/**
 * RestParameterBinding
 * @generated
 */
export interface RestParameterBinding extends EObject {
  parameter: Parameter;
  binding: ParameterBinding;
  wireName?: string;

}
