/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceException } from './ServiceException.js';
import type { RestExceptionBinding } from './RestExceptionBinding.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of RestExceptionBinding
 * @generated
 */
export class RestExceptionBindingImpl extends BasicEObject implements RestExceptionBinding {
  // Feature ID Constants (eLiterals)
  static readonly EXCEPTION: number = 0;
  static readonly STATUS: number = 1;

  // Private fields
  private _exception?: ServiceException;
  private _status: number = 500;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.REST_EXCEPTION_BINDING;
  }

  // Getters and Setters
  get exception(): ServiceException {
    return this._exception!;
  }

  set exception(value: ServiceException) {
    const oldValue = this._exception;
    this._exception = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestExceptionBindingImpl.EXCEPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestExceptionBindingImpl.EXCEPTION,
        merge: () => false
      });
    }
  }

  get status(): number {
    return this._status!;
  }

  set status(value: number) {
    const oldValue = this._status;
    this._status = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(RestExceptionBindingImpl.STATUS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => RestExceptionBindingImpl.STATUS,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestExceptionBindingImpl.EXCEPTION:
        return this.exception;
      case RestExceptionBindingImpl.STATUS:
        return this.status;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestExceptionBindingImpl.EXCEPTION:
        this.exception = newValue as ServiceException;
        super.eSet(feature, newValue);
        break;
      case RestExceptionBindingImpl.STATUS:
        this.status = newValue as number;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestExceptionBindingImpl.EXCEPTION:
        return this._exception !== undefined;
      case RestExceptionBindingImpl.STATUS:
        return this._status !== 500;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case RestExceptionBindingImpl.EXCEPTION:
        this._exception = undefined;
        return;
      case RestExceptionBindingImpl.STATUS:
        this._status = 500;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
