/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Property } from './Property';
import type { ServiceProvider } from './ServiceProvider';
import type { ServiceRegistration } from './ServiceRegistration';

/**
 * ServiceReference
 * @generated
 */
export interface ServiceReference extends EObject {
  id: string;
  properties: Property[];
  provider: ServiceProvider;
  registration?: ServiceRegistration;

  getProperty(key: string): unknown;
  getPropertyKeys(): string;
}
