/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceEventType } from './ServiceEventType';
import type { ServiceReference } from './ServiceReference';

/**
 * ServiceEvent
 * @generated
 */
export interface ServiceEvent extends EObject {
  type: ServiceEventType;
  reference: ServiceReference;
  timestamp?: Date;

}
