/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { ServiceOperation } from './ServiceOperation';
import type { ServiceOperationFlavor } from './ServiceOperationFlavor';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ServiceOperationFlavor
 * @generated
 */
export abstract class ServiceOperationFlavorImpl extends BasicEObject implements ServiceOperationFlavor {
  // Feature ID Constants (eLiterals)
  static readonly OPERATION: number = 1;
  static readonly CONSUMES: number = 2;
  static readonly PRODUCES: number = 3;
  static readonly NAME: number = 0;

  // Private fields
  private _operation?: ServiceOperation;
  private _consumes: string[] = [];
  private _produces: string[] = [];
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_OPERATION_FLAVOR;
  }

  // Getters and Setters
  get operation(): ServiceOperation {
    return this._operation!;
  }

  set operation(value: ServiceOperation) {
    const oldValue = this._operation;
    this._operation = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationFlavorImpl.OPERATION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationFlavorImpl.OPERATION,
        merge: () => false
      });
    }
  }

  get consumes(): string[] {
    return this._consumes;
  }

  set consumes(value: string[]) {
    const oldValue = this._consumes;
    this._consumes = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationFlavorImpl.CONSUMES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationFlavorImpl.CONSUMES,
        merge: () => false
      });
    }
  }

  get produces(): string[] {
    return this._produces;
  }

  set produces(value: string[]) {
    const oldValue = this._produces;
    this._produces = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationFlavorImpl.PRODUCES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationFlavorImpl.PRODUCES,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationFlavorImpl.OPERATION:
        return this.operation;
      case ServiceOperationFlavorImpl.CONSUMES:
        return this.consumes;
      case ServiceOperationFlavorImpl.PRODUCES:
        return this.produces;
      case ServiceOperationFlavorImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationFlavorImpl.OPERATION:
        this.operation = newValue as ServiceOperation;
        super.eSet(feature, newValue);
        break;
      case ServiceOperationFlavorImpl.CONSUMES:
        this.consumes = newValue as string[];
        super.eSet(feature, newValue);
        break;
      case ServiceOperationFlavorImpl.PRODUCES:
        this.produces = newValue as string[];
        super.eSet(feature, newValue);
        break;
      case ServiceOperationFlavorImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationFlavorImpl.OPERATION:
        return this._operation !== undefined;
      case ServiceOperationFlavorImpl.CONSUMES:
        return this._consumes !== undefined && this._consumes.length > 0;
      case ServiceOperationFlavorImpl.PRODUCES:
        return this._produces !== undefined && this._produces.length > 0;
      case ServiceOperationFlavorImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationFlavorImpl.OPERATION:
        this._operation = undefined;
        return;
      case ServiceOperationFlavorImpl.CONSUMES:
        this._consumes = [];
        return;
      case ServiceOperationFlavorImpl.PRODUCES:
        this._produces = [];
        return;
      case ServiceOperationFlavorImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
