/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { FlavorKind } from './FlavorKind';
import type { ServiceOperationFlavor } from './ServiceOperationFlavor';
import type { Capability } from './Capability';

/**
 * ServiceFlavor
 * @generated
 */
export interface ServiceFlavor extends NamedElement {
  kind: FlavorKind;
  operationFlavors: ServiceOperationFlavor[];
  capabilities: Capability[];

}
