/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { RegistryKind } from './RegistryKind';
import type { PublishHook } from './PublishHook';
import type { DiscoveryHook } from './DiscoveryHook';
import type { DistributionHook } from './DistributionHook';
import type { ServiceReference } from './ServiceReference';
import type { ConsumerCapability } from './ConsumerCapability';
import type { ServiceListener } from './ServiceListener';

/**
 * ServiceRegistry
 * @generated
 */
export interface ServiceRegistry extends NamedElement {
  kind: RegistryKind;
  publishHooks: PublishHook[];
  discoveryHooks: DiscoveryHook[];
  distributionHooks: DistributionHook[];

  getServiceReference(interfaceName: string): ServiceReference;
  getServiceReferences(interfaceName: string, filter: string, capability: ConsumerCapability): ServiceReference;
  getAllServiceReferences(interfaceName: string, filter: string, capability: ConsumerCapability): ServiceReference;
  addServiceListener(listener: ServiceListener): void;
  removeServiceListener(listener: ServiceListener): void;
}
