/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ServiceEventType
 * @generated
 */
export const ServiceEventType = {
  UNSPECIFIED: 'UNSPECIFIED',
  REGISTERED: 'REGISTERED',
  MODIFIED: 'MODIFIED',
  UNREGISTERING: 'UNREGISTERING',
  MODIFIED_ENDMATCH: 'MODIFIED_ENDMATCH'
} as const;

export type ServiceEventType = typeof ServiceEventType[keyof typeof ServiceEventType];

/**
 * Get enum value by name
 */
export function getServiceEventType(name: string): ServiceEventType | undefined {
  return (ServiceEventType as Record<string, string>)[name] as ServiceEventType | undefined;
}

/**
 * Get enum value by literal
 */
export function getServiceEventTypeByLiteral(literal: string): ServiceEventType | undefined {
  if (literal === 'UNSPECIFIED') return ServiceEventType.UNSPECIFIED;
  if (literal === 'REGISTERED') return ServiceEventType.REGISTERED;
  if (literal === 'MODIFIED') return ServiceEventType.MODIFIED;
  if (literal === 'UNREGISTERING') return ServiceEventType.UNREGISTERING;
  if (literal === 'MODIFIED_ENDMATCH') return ServiceEventType.MODIFIED_ENDMATCH;
  return undefined;
}
