/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { Property } from './Property.js';
import type { Diagnostic } from './Diagnostic.js';
import type { ServiceInvocationResult } from './ServiceInvocationResult.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ServiceInvocationResult
 * @generated
 */
export class ServiceInvocationResultImpl extends BasicEObject implements ServiceInvocationResult {
  // Feature ID Constants (eLiterals)
  static readonly VALUE: number = 0;
  static readonly DIAGNOSTIC: number = 1;

  // Private fields
  private _value?: Property;
  private _diagnostic?: Diagnostic;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_INVOCATION_RESULT;
  }

  // Getters and Setters
  get value(): Property {
    return this._value!;
  }

  set value(value: Property) {
    const oldValue = this._value;
    this._value = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInvocationResultImpl.VALUE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInvocationResultImpl.VALUE,
        merge: () => false
      });
    }
  }

  get diagnostic(): Diagnostic {
    return this._diagnostic!;
  }

  set diagnostic(value: Diagnostic) {
    const oldValue = this._diagnostic;
    this._diagnostic = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInvocationResultImpl.DIAGNOSTIC),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInvocationResultImpl.DIAGNOSTIC,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInvocationResultImpl.VALUE:
        return this.value;
      case ServiceInvocationResultImpl.DIAGNOSTIC:
        return this.diagnostic;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInvocationResultImpl.VALUE:
        this.value = newValue as Property;
        super.eSet(feature, newValue);
        break;
      case ServiceInvocationResultImpl.DIAGNOSTIC:
        this.diagnostic = newValue as Diagnostic;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInvocationResultImpl.VALUE:
        return this._value !== undefined;
      case ServiceInvocationResultImpl.DIAGNOSTIC:
        return this._diagnostic !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInvocationResultImpl.VALUE:
        this._value = undefined;
        return;
      case ServiceInvocationResultImpl.DIAGNOSTIC:
        this._diagnostic = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
