/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { VersionedElement } from './VersionedElement';
import type { Property } from './Property';
import type { ServiceException } from './ServiceException';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ServiceException
 * @generated
 */
export class ServiceExceptionImpl extends BasicEObject implements ServiceException {
  // Feature ID Constants (eLiterals)
  static readonly DESCRIPTION: number = 2;
  static readonly TYPE: number = 3;
  static readonly PROPERTIES: number = 4;
  static readonly NAME: number = 0;
  static readonly VERSION: number = 1;

  // Private fields
  private _description?: string;
  private _type: string = "";
  private _properties: Property[] = [];
  private _name: string = "";
  private _version?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_EXCEPTION;
  }

  // Getters and Setters
  get description(): string {
    return this._description!;
  }

  set description(value: string) {
    const oldValue = this._description;
    this._description = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceExceptionImpl.DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceExceptionImpl.DESCRIPTION,
        merge: () => false
      });
    }
  }

  get type(): string {
    return this._type!;
  }

  set type(value: string) {
    const oldValue = this._type;
    this._type = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceExceptionImpl.TYPE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceExceptionImpl.TYPE,
        merge: () => false
      });
    }
  }

  get properties(): Property[] {
    return this._properties;
  }

  set properties(value: Property[]) {
    const oldValue = this._properties;
    this._properties = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceExceptionImpl.PROPERTIES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceExceptionImpl.PROPERTIES,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  get version(): string {
    return this._version!;
  }

  set version(value: string) {
    this._version = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceExceptionImpl.DESCRIPTION:
        return this.description;
      case ServiceExceptionImpl.TYPE:
        return this.type;
      case ServiceExceptionImpl.PROPERTIES:
        return this.properties;
      case ServiceExceptionImpl.NAME:
        return this.name;
      case ServiceExceptionImpl.VERSION:
        return this.version;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceExceptionImpl.DESCRIPTION:
        this.description = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceExceptionImpl.TYPE:
        this.type = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceExceptionImpl.PROPERTIES:
        this.properties = newValue as Property[];
        super.eSet(feature, newValue);
        break;
      case ServiceExceptionImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceExceptionImpl.VERSION:
        this.version = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceExceptionImpl.DESCRIPTION:
        return this._description !== undefined;
      case ServiceExceptionImpl.TYPE:
        return this._type !== "";
      case ServiceExceptionImpl.PROPERTIES:
        return this._properties !== undefined && this._properties.length > 0;
      case ServiceExceptionImpl.NAME:
        return this._name !== "";
      case ServiceExceptionImpl.VERSION:
        return this._version !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceExceptionImpl.DESCRIPTION:
        this._description = undefined;
        return;
      case ServiceExceptionImpl.TYPE:
        this._type = "";
        return;
      case ServiceExceptionImpl.PROPERTIES:
        this._properties = [];
        return;
      case ServiceExceptionImpl.NAME:
        this._name = "";
        return;
      case ServiceExceptionImpl.VERSION:
        this._version = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
