/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

/**
 * ServiceScope
 * @generated
 */
export const ServiceScope = {
  SINGLETON: 'SINGLETON',
  BUNDLE: 'BUNDLE',
  PROTOTYPE: 'PROTOTYPE'
} as const;

export type ServiceScope = typeof ServiceScope[keyof typeof ServiceScope];

/**
 * Get enum value by name
 */
export function getServiceScope(name: string): ServiceScope | undefined {
  return (ServiceScope as Record<string, string>)[name] as ServiceScope | undefined;
}

/**
 * Get enum value by literal
 */
export function getServiceScopeByLiteral(literal: string): ServiceScope | undefined {
  if (literal === 'SINGLETON') return ServiceScope.SINGLETON;
  if (literal === 'BUNDLE') return ServiceScope.BUNDLE;
  if (literal === 'PROTOTYPE') return ServiceScope.PROTOTYPE;
  return undefined;
}
