/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { VersionedElement } from './VersionedElement';
import type { ServiceOperation } from './ServiceOperation';
import type { ServiceException } from './ServiceException';
import type { Invariant } from './Invariant';
import { CatalogStatus } from './CatalogStatus';
import type { ServiceInterface } from './ServiceInterface';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ServiceInterface
 * @generated
 */
export class ServiceInterfaceImpl extends BasicEObject implements ServiceInterface {
  // Feature ID Constants (eLiterals)
  static readonly DESCRIPTION: number = 2;
  static readonly OPERATIONS: number = 3;
  static readonly EXCEPTIONS: number = 4;
  static readonly INVARIANTS: number = 5;
  static readonly STATUS: number = 6;
  static readonly DEPRECATION_REASON: number = 7;
  static readonly REPLACED_BY: number = 8;
  static readonly NAME: number = 0;
  static readonly VERSION: number = 1;

  // Private fields
  private _description?: string;
  private _operations: ServiceOperation[] = [];
  private _exceptions: ServiceException[] = [];
  private _invariants: Invariant[] = [];
  private _status: CatalogStatus = CatalogStatus.ACTIVE;
  private _deprecationReason?: string;
  private _replacedBy?: ServiceInterface;
  private _name: string = "";
  private _version?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_INTERFACE;
  }

  // Getters and Setters
  get description(): string {
    return this._description!;
  }

  set description(value: string) {
    const oldValue = this._description;
    this._description = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.DESCRIPTION,
        merge: () => false
      });
    }
  }

  get operations(): ServiceOperation[] {
    return this._operations;
  }

  set operations(value: ServiceOperation[]) {
    const oldValue = this._operations;
    this._operations = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.OPERATIONS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.OPERATIONS,
        merge: () => false
      });
    }
  }

  get exceptions(): ServiceException[] {
    return this._exceptions;
  }

  set exceptions(value: ServiceException[]) {
    const oldValue = this._exceptions;
    this._exceptions = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.EXCEPTIONS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.EXCEPTIONS,
        merge: () => false
      });
    }
  }

  get invariants(): Invariant[] {
    return this._invariants;
  }

  set invariants(value: Invariant[]) {
    const oldValue = this._invariants;
    this._invariants = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.INVARIANTS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.INVARIANTS,
        merge: () => false
      });
    }
  }

  get status(): CatalogStatus {
    return this._status!;
  }

  set status(value: CatalogStatus) {
    const oldValue = this._status;
    this._status = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.STATUS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.STATUS,
        merge: () => false
      });
    }
  }

  get deprecationReason(): string {
    return this._deprecationReason!;
  }

  set deprecationReason(value: string) {
    const oldValue = this._deprecationReason;
    this._deprecationReason = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.DEPRECATION_REASON),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.DEPRECATION_REASON,
        merge: () => false
      });
    }
  }

  get replacedBy(): ServiceInterface {
    return this._replacedBy!;
  }

  set replacedBy(value: ServiceInterface) {
    const oldValue = this._replacedBy;
    this._replacedBy = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.REPLACED_BY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.REPLACED_BY,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  get version(): string {
    return this._version!;
  }

  set version(value: string) {
    this._version = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInterfaceImpl.DESCRIPTION:
        return this.description;
      case ServiceInterfaceImpl.OPERATIONS:
        return this.operations;
      case ServiceInterfaceImpl.EXCEPTIONS:
        return this.exceptions;
      case ServiceInterfaceImpl.INVARIANTS:
        return this.invariants;
      case ServiceInterfaceImpl.STATUS:
        return this.status;
      case ServiceInterfaceImpl.DEPRECATION_REASON:
        return this.deprecationReason;
      case ServiceInterfaceImpl.REPLACED_BY:
        return this.replacedBy;
      case ServiceInterfaceImpl.NAME:
        return this.name;
      case ServiceInterfaceImpl.VERSION:
        return this.version;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInterfaceImpl.DESCRIPTION:
        this.description = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.OPERATIONS:
        this.operations = newValue as ServiceOperation[];
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.EXCEPTIONS:
        this.exceptions = newValue as ServiceException[];
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.INVARIANTS:
        this.invariants = newValue as Invariant[];
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.STATUS:
        this.status = newValue as CatalogStatus;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.DEPRECATION_REASON:
        this.deprecationReason = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.REPLACED_BY:
        this.replacedBy = newValue as ServiceInterface;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.VERSION:
        this.version = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInterfaceImpl.DESCRIPTION:
        return this._description !== undefined;
      case ServiceInterfaceImpl.OPERATIONS:
        return this._operations !== undefined && this._operations.length > 0;
      case ServiceInterfaceImpl.EXCEPTIONS:
        return this._exceptions !== undefined && this._exceptions.length > 0;
      case ServiceInterfaceImpl.INVARIANTS:
        return this._invariants !== undefined && this._invariants.length > 0;
      case ServiceInterfaceImpl.STATUS:
        return this._status !== CatalogStatus.ACTIVE;
      case ServiceInterfaceImpl.DEPRECATION_REASON:
        return this._deprecationReason !== undefined;
      case ServiceInterfaceImpl.REPLACED_BY:
        return this._replacedBy !== undefined;
      case ServiceInterfaceImpl.NAME:
        return this._name !== "";
      case ServiceInterfaceImpl.VERSION:
        return this._version !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInterfaceImpl.DESCRIPTION:
        this._description = undefined;
        return;
      case ServiceInterfaceImpl.OPERATIONS:
        this._operations = [];
        return;
      case ServiceInterfaceImpl.EXCEPTIONS:
        this._exceptions = [];
        return;
      case ServiceInterfaceImpl.INVARIANTS:
        this._invariants = [];
        return;
      case ServiceInterfaceImpl.STATUS:
        this._status = CatalogStatus.ACTIVE;
        return;
      case ServiceInterfaceImpl.DEPRECATION_REASON:
        this._deprecationReason = undefined;
        return;
      case ServiceInterfaceImpl.REPLACED_BY:
        this._replacedBy = undefined;
        return;
      case ServiceInterfaceImpl.NAME:
        this._name = "";
        return;
      case ServiceInterfaceImpl.VERSION:
        this._version = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
