/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { VersionedElement } from './VersionedElement.js';
import type { ServiceInterface } from './ServiceInterface.js';
import type { ServiceFlavor } from './ServiceFlavor.js';
import type { Property } from './Property.js';
import type { ComponentDescription } from './ComponentDescription.js';
import type { UpdatePolicy } from './UpdatePolicy.js';
import type { Capability } from './Capability.js';

/**
 * ServiceImplementation
 * @generated
 */
export interface ServiceImplementation extends NamedElement, VersionedElement {
  description?: string;
  implementationId: string;
  serviceInterfaces: EList<ServiceInterface>;
  flavors: EList<ServiceFlavor>;
  properties: EList<Property>;
  componentDescription?: ComponentDescription;
  updatePolicy: UpdatePolicy;
  replaces?: ServiceImplementation;
  cutoverGraceMillis?: number;
  capabilities: EList<Capability>;

}
