/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createEObjectEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { ServiceReference } from './ServiceReference.js';
import type { ServiceProvider } from './ServiceProvider.js';
import type { ServiceImplementation } from './ServiceImplementation.js';
import type { ConsumerSession } from './ConsumerSession.js';
import type { Property } from './Property.js';
import type { ServiceRegistration } from './ServiceRegistration.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ServiceRegistration
 * @generated
 */
export class ServiceRegistrationImpl extends BasicEObject implements ServiceRegistration {
  // Feature ID Constants (eLiterals)
  static readonly REFERENCE: number = 0;
  static readonly UNREGISTERED: number = 1;
  static readonly PROVIDER: number = 2;
  static readonly IMPLEMENTATION: number = 3;
  static readonly USING_SESSIONS: number = 4;
  static readonly PUBLISHED_BY: number = 5;
  static readonly CONSUMER_COUNT: number = 6;

  // Private fields
  private _reference?: ServiceReference;
  private _unregistered: boolean = false;
  private _provider?: ServiceProvider;
  private _implementation?: ServiceImplementation;
  private _usingSessions!: EList<ConsumerSession>;
  private _publishedBy?: string;
  private _consumerCount?: number;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_REGISTRATION;
  }

  // Getters and Setters
  get reference(): ServiceReference {
    return this._reference!;
  }

  set reference(value: ServiceReference) {
    const oldValue = this._reference;
    this._reference = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistrationImpl.REFERENCE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistrationImpl.REFERENCE,
        merge: () => false
      });
    }
  }

  get unregistered(): boolean {
    return this._unregistered!;
  }

  set unregistered(value: boolean) {
    const oldValue = this._unregistered;
    this._unregistered = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistrationImpl.UNREGISTERED),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistrationImpl.UNREGISTERED,
        merge: () => false
      });
    }
  }

  get provider(): ServiceProvider {
    return this._provider!;
  }

  set provider(value: ServiceProvider) {
    const oldValue = this._provider;
    this._provider = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistrationImpl.PROVIDER),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistrationImpl.PROVIDER,
        merge: () => false
      });
    }
  }

  get implementation(): ServiceImplementation {
    return this._implementation!;
  }

  set implementation(value: ServiceImplementation) {
    const oldValue = this._implementation;
    this._implementation = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistrationImpl.IMPLEMENTATION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistrationImpl.IMPLEMENTATION,
        merge: () => false
      });
    }
  }

  get usingSessions(): EList<ConsumerSession> {
    if (!this._usingSessions) {
      this._usingSessions = createEObjectEList(this, this.eClass().getEStructuralFeature('usingSessions') as EReference) as unknown as EList<ConsumerSession>;
    }
    return this._usingSessions;
  }

  get publishedBy(): string {
    return this._publishedBy!;
  }

  set publishedBy(value: string) {
    const oldValue = this._publishedBy;
    this._publishedBy = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistrationImpl.PUBLISHED_BY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistrationImpl.PUBLISHED_BY,
        merge: () => false
      });
    }
  }

  get consumerCount(): number {
    return this._consumerCount!;
  }

  set consumerCount(value: number) {
    const oldValue = this._consumerCount;
    this._consumerCount = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistrationImpl.CONSUMER_COUNT),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistrationImpl.CONSUMER_COUNT,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceRegistrationImpl.REFERENCE:
        return this.reference;
      case ServiceRegistrationImpl.UNREGISTERED:
        return this.unregistered;
      case ServiceRegistrationImpl.PROVIDER:
        return this.provider;
      case ServiceRegistrationImpl.IMPLEMENTATION:
        return this.implementation;
      case ServiceRegistrationImpl.USING_SESSIONS:
        return this.usingSessions;
      case ServiceRegistrationImpl.PUBLISHED_BY:
        return this.publishedBy;
      case ServiceRegistrationImpl.CONSUMER_COUNT:
        return this.consumerCount;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceRegistrationImpl.REFERENCE:
        this.reference = newValue as ServiceReference;
        super.eSet(feature, newValue);
        break;
      case ServiceRegistrationImpl.UNREGISTERED:
        this.unregistered = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      case ServiceRegistrationImpl.PROVIDER:
        this.provider = newValue as ServiceProvider;
        super.eSet(feature, newValue);
        break;
      case ServiceRegistrationImpl.IMPLEMENTATION:
        this.implementation = newValue as ServiceImplementation;
        super.eSet(feature, newValue);
        break;
      case ServiceRegistrationImpl.USING_SESSIONS:
        this.usingSessions.clear();
        this.usingSessions.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceRegistrationImpl.PUBLISHED_BY:
        this.publishedBy = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceRegistrationImpl.CONSUMER_COUNT:
        this.consumerCount = newValue as number;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceRegistrationImpl.REFERENCE:
        return this._reference !== undefined;
      case ServiceRegistrationImpl.UNREGISTERED:
        return this._unregistered !== false;
      case ServiceRegistrationImpl.PROVIDER:
        return this._provider !== undefined;
      case ServiceRegistrationImpl.IMPLEMENTATION:
        return this._implementation !== undefined;
      case ServiceRegistrationImpl.USING_SESSIONS:
        return this._usingSessions !== undefined && !this._usingSessions.isEmpty();
      case ServiceRegistrationImpl.PUBLISHED_BY:
        return this._publishedBy !== undefined;
      case ServiceRegistrationImpl.CONSUMER_COUNT:
        return this._consumerCount !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceRegistrationImpl.REFERENCE:
        this._reference = undefined;
        return;
      case ServiceRegistrationImpl.UNREGISTERED:
        this._unregistered = false;
        return;
      case ServiceRegistrationImpl.PROVIDER:
        this._provider = undefined;
        return;
      case ServiceRegistrationImpl.IMPLEMENTATION:
        this._implementation = undefined;
        return;
      case ServiceRegistrationImpl.USING_SESSIONS:
        if (this._usingSessions) this._usingSessions.clear();
        return;
      case ServiceRegistrationImpl.PUBLISHED_BY:
        this._publishedBy = undefined;
        return;
      case ServiceRegistrationImpl.CONSUMER_COUNT:
        this._consumerCount = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

  unregister(): void {
    throw new Error('unregister not implemented');
  }

  setProperties(props: Property): void {
    throw new Error('setProperties not implemented');
  }

}
