/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { FlavorKind } from './FlavorKind';
import type { ServiceOperationFlavor } from './ServiceOperationFlavor';
import type { ServiceFlavor } from './ServiceFlavor';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ServiceFlavor
 * @generated
 */
export abstract class ServiceFlavorImpl extends BasicEObject implements ServiceFlavor {
  // Feature ID Constants (eLiterals)
  static readonly KIND: number = 1;
  static readonly OPERATION_FLAVORS: number = 2;
  static readonly NAME: number = 0;

  // Private fields
  private _kind?: FlavorKind;
  private _operationFlavors: ServiceOperationFlavor[] = [];
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_FLAVOR;
  }

  // Getters and Setters
  get kind(): FlavorKind {
    return this._kind!;
  }

  set kind(value: FlavorKind) {
    const oldValue = this._kind;
    this._kind = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceFlavorImpl.KIND),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceFlavorImpl.KIND,
        merge: () => false
      });
    }
  }

  get operationFlavors(): ServiceOperationFlavor[] {
    return this._operationFlavors;
  }

  set operationFlavors(value: ServiceOperationFlavor[]) {
    const oldValue = this._operationFlavors;
    this._operationFlavors = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceFlavorImpl.OPERATION_FLAVORS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceFlavorImpl.OPERATION_FLAVORS,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceFlavorImpl.KIND:
        return this.kind;
      case ServiceFlavorImpl.OPERATION_FLAVORS:
        return this.operationFlavors;
      case ServiceFlavorImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceFlavorImpl.KIND:
        this.kind = newValue as FlavorKind;
        super.eSet(feature, newValue);
        break;
      case ServiceFlavorImpl.OPERATION_FLAVORS:
        this.operationFlavors = newValue as ServiceOperationFlavor[];
        super.eSet(feature, newValue);
        break;
      case ServiceFlavorImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceFlavorImpl.KIND:
        return this._kind !== undefined;
      case ServiceFlavorImpl.OPERATION_FLAVORS:
        return this._operationFlavors !== undefined && this._operationFlavors.length > 0;
      case ServiceFlavorImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceFlavorImpl.KIND:
        this._kind = undefined;
        return;
      case ServiceFlavorImpl.OPERATION_FLAVORS:
        this._operationFlavors = [];
        return;
      case ServiceFlavorImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
