/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { VersionedElement } from './VersionedElement';
import type { Property } from './Property';

/**
 * ServiceException
 * @generated
 */
export interface ServiceException extends NamedElement, VersionedElement {
  description?: string;
  type: string;
  properties: Property[];

}
