/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { ServiceOperation } from './ServiceOperation';

/**
 * ServiceOperationFlavor
 * @generated
 */
export interface ServiceOperationFlavor extends NamedElement {
  operation: ServiceOperation;
  consumes: string[];
  produces: string[];

}
