/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { VersionedElement } from './VersionedElement';
import type { ServiceInterface } from './ServiceInterface';
import type { ServiceFlavor } from './ServiceFlavor';
import type { Property } from './Property';
import type { ComponentDescription } from './ComponentDescription';

/**
 * ServiceImplementation
 * @generated
 */
export interface ServiceImplementation extends NamedElement, VersionedElement {
  description?: string;
  implementationId: string;
  serviceInterfaces: ServiceInterface[];
  flavors: ServiceFlavor[];
  properties: Property[];
  componentDescription?: ComponentDescription;

}
