/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { VersionedElement } from './VersionedElement.js';
import type { ComponentDescription } from './ComponentDescription.js';
import type { ServiceImplementation } from './ServiceImplementation.js';

/**
 * ServiceProvider
 * @generated
 */
export interface ServiceProvider extends NamedElement, VersionedElement {
  symbolicName: string;
  descriptions: EList<ComponentDescription>;
  implementations: EList<ServiceImplementation>;

}
