/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { Parameter } from './Parameter.js';
import type { ServiceException } from './ServiceException.js';
import type { Invariant } from './Invariant.js';

/**
 * ServiceOperation
 * @generated
 */
export interface ServiceOperation extends NamedElement {
  description?: string;
  parameters: EList<Parameter>;
  returnValue?: Parameter;
  exceptions: EList<ServiceException>;
  preconditions: EList<Invariant>;
  postconditions: EList<Invariant>;

}
