/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { Parameter } from './Parameter';
import type { ParameterConstraint } from './ParameterConstraint';
import type { ServiceException } from './ServiceException';
import type { Invariant } from './Invariant';
import type { ServiceOperation } from './ServiceOperation';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ServiceOperation
 * @generated
 */
export class ServiceOperationImpl extends BasicEObject implements ServiceOperation {
  // Feature ID Constants (eLiterals)
  static readonly DESCRIPTION: number = 1;
  static readonly PARAMETERS: number = 2;
  static readonly RETURN_TYPE: number = 3;
  static readonly RETURN_CONSTRAINTS: number = 4;
  static readonly EXCEPTIONS: number = 5;
  static readonly PRECONDITIONS: number = 6;
  static readonly POSTCONDITIONS: number = 7;
  static readonly NAME: number = 0;

  // Private fields
  private _description?: string;
  private _parameters: Parameter[] = [];
  private _returnType?: string;
  private _returnConstraints: ParameterConstraint[] = [];
  private _exceptions: ServiceException[] = [];
  private _preconditions: Invariant[] = [];
  private _postconditions: Invariant[] = [];
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_OPERATION;
  }

  // Getters and Setters
  get description(): string {
    return this._description!;
  }

  set description(value: string) {
    const oldValue = this._description;
    this._description = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationImpl.DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationImpl.DESCRIPTION,
        merge: () => false
      });
    }
  }

  get parameters(): Parameter[] {
    return this._parameters;
  }

  set parameters(value: Parameter[]) {
    const oldValue = this._parameters;
    this._parameters = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationImpl.PARAMETERS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationImpl.PARAMETERS,
        merge: () => false
      });
    }
  }

  get returnType(): string {
    return this._returnType!;
  }

  set returnType(value: string) {
    const oldValue = this._returnType;
    this._returnType = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationImpl.RETURN_TYPE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationImpl.RETURN_TYPE,
        merge: () => false
      });
    }
  }

  get returnConstraints(): ParameterConstraint[] {
    return this._returnConstraints;
  }

  set returnConstraints(value: ParameterConstraint[]) {
    const oldValue = this._returnConstraints;
    this._returnConstraints = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationImpl.RETURN_CONSTRAINTS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationImpl.RETURN_CONSTRAINTS,
        merge: () => false
      });
    }
  }

  get exceptions(): ServiceException[] {
    return this._exceptions;
  }

  set exceptions(value: ServiceException[]) {
    const oldValue = this._exceptions;
    this._exceptions = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationImpl.EXCEPTIONS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationImpl.EXCEPTIONS,
        merge: () => false
      });
    }
  }

  get preconditions(): Invariant[] {
    return this._preconditions;
  }

  set preconditions(value: Invariant[]) {
    const oldValue = this._preconditions;
    this._preconditions = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationImpl.PRECONDITIONS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationImpl.PRECONDITIONS,
        merge: () => false
      });
    }
  }

  get postconditions(): Invariant[] {
    return this._postconditions;
  }

  set postconditions(value: Invariant[]) {
    const oldValue = this._postconditions;
    this._postconditions = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationImpl.POSTCONDITIONS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationImpl.POSTCONDITIONS,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationImpl.DESCRIPTION:
        return this.description;
      case ServiceOperationImpl.PARAMETERS:
        return this.parameters;
      case ServiceOperationImpl.RETURN_TYPE:
        return this.returnType;
      case ServiceOperationImpl.RETURN_CONSTRAINTS:
        return this.returnConstraints;
      case ServiceOperationImpl.EXCEPTIONS:
        return this.exceptions;
      case ServiceOperationImpl.PRECONDITIONS:
        return this.preconditions;
      case ServiceOperationImpl.POSTCONDITIONS:
        return this.postconditions;
      case ServiceOperationImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationImpl.DESCRIPTION:
        this.description = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceOperationImpl.PARAMETERS:
        this.parameters = newValue as Parameter[];
        super.eSet(feature, newValue);
        break;
      case ServiceOperationImpl.RETURN_TYPE:
        this.returnType = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceOperationImpl.RETURN_CONSTRAINTS:
        this.returnConstraints = newValue as ParameterConstraint[];
        super.eSet(feature, newValue);
        break;
      case ServiceOperationImpl.EXCEPTIONS:
        this.exceptions = newValue as ServiceException[];
        super.eSet(feature, newValue);
        break;
      case ServiceOperationImpl.PRECONDITIONS:
        this.preconditions = newValue as Invariant[];
        super.eSet(feature, newValue);
        break;
      case ServiceOperationImpl.POSTCONDITIONS:
        this.postconditions = newValue as Invariant[];
        super.eSet(feature, newValue);
        break;
      case ServiceOperationImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationImpl.DESCRIPTION:
        return this._description !== undefined;
      case ServiceOperationImpl.PARAMETERS:
        return this._parameters !== undefined && this._parameters.length > 0;
      case ServiceOperationImpl.RETURN_TYPE:
        return this._returnType !== undefined;
      case ServiceOperationImpl.RETURN_CONSTRAINTS:
        return this._returnConstraints !== undefined && this._returnConstraints.length > 0;
      case ServiceOperationImpl.EXCEPTIONS:
        return this._exceptions !== undefined && this._exceptions.length > 0;
      case ServiceOperationImpl.PRECONDITIONS:
        return this._preconditions !== undefined && this._preconditions.length > 0;
      case ServiceOperationImpl.POSTCONDITIONS:
        return this._postconditions !== undefined && this._postconditions.length > 0;
      case ServiceOperationImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationImpl.DESCRIPTION:
        this._description = undefined;
        return;
      case ServiceOperationImpl.PARAMETERS:
        this._parameters = [];
        return;
      case ServiceOperationImpl.RETURN_TYPE:
        this._returnType = undefined;
        return;
      case ServiceOperationImpl.RETURN_CONSTRAINTS:
        this._returnConstraints = [];
        return;
      case ServiceOperationImpl.EXCEPTIONS:
        this._exceptions = [];
        return;
      case ServiceOperationImpl.PRECONDITIONS:
        this._preconditions = [];
        return;
      case ServiceOperationImpl.POSTCONDITIONS:
        this._postconditions = [];
        return;
      case ServiceOperationImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
