/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { VersionedElement } from './VersionedElement.js';
import type { ServiceOperation } from './ServiceOperation.js';
import type { ServiceException } from './ServiceException.js';
import type { Invariant } from './Invariant.js';
import { CatalogStatus } from './CatalogStatus.js';
import { UpdatePolicy } from './UpdatePolicy.js';
import type { ServiceInterface } from './ServiceInterface.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ServiceInterface
 * @generated
 */
export class ServiceInterfaceImpl extends BasicEObject implements ServiceInterface {
  // Feature ID Constants (eLiterals)
  static readonly DESCRIPTION: number = 2;
  static readonly OPERATIONS: number = 3;
  static readonly EXCEPTIONS: number = 4;
  static readonly INVARIANTS: number = 5;
  static readonly STATUS: number = 6;
  static readonly DEPRECATION_REASON: number = 7;
  static readonly ADDED_BY: number = 8;
  static readonly DEPRECATED_BY: number = 9;
  static readonly REPLACED_BY: number = 10;
  static readonly UPDATE_POLICY: number = 11;
  static readonly NAME: number = 0;
  static readonly VERSION: number = 1;

  // Private fields
  private _description?: string;
  private _operations!: EList<ServiceOperation>;
  private _exceptions!: EList<ServiceException>;
  private _invariants!: EList<Invariant>;
  private _status: CatalogStatus = CatalogStatus.ACTIVE;
  private _deprecationReason?: string;
  private _addedBy?: string;
  private _deprecatedBy?: string;
  private _replacedBy?: ServiceInterface;
  private _updatePolicy: UpdatePolicy = UpdatePolicy.UNSPECIFIED;
  private _name: string = "";
  private _version?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_INTERFACE;
  }

  // Getters and Setters
  get description(): string {
    return this._description!;
  }

  set description(value: string) {
    const oldValue = this._description;
    this._description = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.DESCRIPTION,
        merge: () => false
      });
    }
  }

  get operations(): EList<ServiceOperation> {
    if (!this._operations) {
      this._operations = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('operations') as EReference);
    }
    return this._operations;
  }

  get exceptions(): EList<ServiceException> {
    if (!this._exceptions) {
      this._exceptions = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('exceptions') as EReference);
    }
    return this._exceptions;
  }

  get invariants(): EList<Invariant> {
    if (!this._invariants) {
      this._invariants = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('invariants') as EReference);
    }
    return this._invariants;
  }

  get status(): CatalogStatus {
    return this._status!;
  }

  set status(value: CatalogStatus) {
    const oldValue = this._status;
    this._status = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.STATUS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.STATUS,
        merge: () => false
      });
    }
  }

  get deprecationReason(): string {
    return this._deprecationReason!;
  }

  set deprecationReason(value: string) {
    const oldValue = this._deprecationReason;
    this._deprecationReason = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.DEPRECATION_REASON),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.DEPRECATION_REASON,
        merge: () => false
      });
    }
  }

  get addedBy(): string {
    return this._addedBy!;
  }

  set addedBy(value: string) {
    const oldValue = this._addedBy;
    this._addedBy = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.ADDED_BY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.ADDED_BY,
        merge: () => false
      });
    }
  }

  get deprecatedBy(): string {
    return this._deprecatedBy!;
  }

  set deprecatedBy(value: string) {
    const oldValue = this._deprecatedBy;
    this._deprecatedBy = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.DEPRECATED_BY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.DEPRECATED_BY,
        merge: () => false
      });
    }
  }

  get replacedBy(): ServiceInterface {
    return this._replacedBy!;
  }

  set replacedBy(value: ServiceInterface) {
    const oldValue = this._replacedBy;
    this._replacedBy = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.REPLACED_BY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.REPLACED_BY,
        merge: () => false
      });
    }
  }

  get updatePolicy(): UpdatePolicy {
    return this._updatePolicy!;
  }

  set updatePolicy(value: UpdatePolicy) {
    const oldValue = this._updatePolicy;
    this._updatePolicy = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInterfaceImpl.UPDATE_POLICY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInterfaceImpl.UPDATE_POLICY,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  get version(): string {
    return this._version!;
  }

  set version(value: string) {
    this._version = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInterfaceImpl.DESCRIPTION:
        return this.description;
      case ServiceInterfaceImpl.OPERATIONS:
        return this.operations;
      case ServiceInterfaceImpl.EXCEPTIONS:
        return this.exceptions;
      case ServiceInterfaceImpl.INVARIANTS:
        return this.invariants;
      case ServiceInterfaceImpl.STATUS:
        return this.status;
      case ServiceInterfaceImpl.DEPRECATION_REASON:
        return this.deprecationReason;
      case ServiceInterfaceImpl.ADDED_BY:
        return this.addedBy;
      case ServiceInterfaceImpl.DEPRECATED_BY:
        return this.deprecatedBy;
      case ServiceInterfaceImpl.REPLACED_BY:
        return this.replacedBy;
      case ServiceInterfaceImpl.UPDATE_POLICY:
        return this.updatePolicy;
      case ServiceInterfaceImpl.NAME:
        return this.name;
      case ServiceInterfaceImpl.VERSION:
        return this.version;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInterfaceImpl.DESCRIPTION:
        this.description = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.OPERATIONS:
        this.operations.clear();
        this.operations.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.EXCEPTIONS:
        this.exceptions.clear();
        this.exceptions.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.INVARIANTS:
        this.invariants.clear();
        this.invariants.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.STATUS:
        this.status = newValue as CatalogStatus;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.DEPRECATION_REASON:
        this.deprecationReason = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.ADDED_BY:
        this.addedBy = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.DEPRECATED_BY:
        this.deprecatedBy = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.REPLACED_BY:
        this.replacedBy = newValue as ServiceInterface;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.UPDATE_POLICY:
        this.updatePolicy = newValue as UpdatePolicy;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceInterfaceImpl.VERSION:
        this.version = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInterfaceImpl.DESCRIPTION:
        return this._description !== undefined;
      case ServiceInterfaceImpl.OPERATIONS:
        return this._operations !== undefined && !this._operations.isEmpty();
      case ServiceInterfaceImpl.EXCEPTIONS:
        return this._exceptions !== undefined && !this._exceptions.isEmpty();
      case ServiceInterfaceImpl.INVARIANTS:
        return this._invariants !== undefined && !this._invariants.isEmpty();
      case ServiceInterfaceImpl.STATUS:
        return this._status !== CatalogStatus.ACTIVE;
      case ServiceInterfaceImpl.DEPRECATION_REASON:
        return this._deprecationReason !== undefined;
      case ServiceInterfaceImpl.ADDED_BY:
        return this._addedBy !== undefined;
      case ServiceInterfaceImpl.DEPRECATED_BY:
        return this._deprecatedBy !== undefined;
      case ServiceInterfaceImpl.REPLACED_BY:
        return this._replacedBy !== undefined;
      case ServiceInterfaceImpl.UPDATE_POLICY:
        return this._updatePolicy !== UpdatePolicy.UNSPECIFIED;
      case ServiceInterfaceImpl.NAME:
        return this._name !== "";
      case ServiceInterfaceImpl.VERSION:
        return this._version !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInterfaceImpl.DESCRIPTION:
        this._description = undefined;
        return;
      case ServiceInterfaceImpl.OPERATIONS:
        if (this._operations) this._operations.clear();
        return;
      case ServiceInterfaceImpl.EXCEPTIONS:
        if (this._exceptions) this._exceptions.clear();
        return;
      case ServiceInterfaceImpl.INVARIANTS:
        if (this._invariants) this._invariants.clear();
        return;
      case ServiceInterfaceImpl.STATUS:
        this._status = CatalogStatus.ACTIVE;
        return;
      case ServiceInterfaceImpl.DEPRECATION_REASON:
        this._deprecationReason = undefined;
        return;
      case ServiceInterfaceImpl.ADDED_BY:
        this._addedBy = undefined;
        return;
      case ServiceInterfaceImpl.DEPRECATED_BY:
        this._deprecatedBy = undefined;
        return;
      case ServiceInterfaceImpl.REPLACED_BY:
        this._replacedBy = undefined;
        return;
      case ServiceInterfaceImpl.UPDATE_POLICY:
        this._updatePolicy = UpdatePolicy.UNSPECIFIED;
        return;
      case ServiceInterfaceImpl.NAME:
        this._name = "";
        return;
      case ServiceInterfaceImpl.VERSION:
        this._version = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
