/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceEventType } from './ServiceEventType';
import type { ServiceReference } from './ServiceReference';
import type { ServiceEvent } from './ServiceEvent';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ServiceEvent
 * @generated
 */
export class ServiceEventImpl extends BasicEObject implements ServiceEvent {
  // Feature ID Constants (eLiterals)
  static readonly TYPE: number = 0;
  static readonly REFERENCE: number = 1;
  static readonly TIMESTAMP: number = 2;
  static readonly REASON_CODE: number = 3;

  // Private fields
  private _type?: ServiceEventType;
  private _reference?: ServiceReference;
  private _timestamp?: Date;
  private _reasonCode?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_EVENT;
  }

  // Getters and Setters
  get type(): ServiceEventType {
    return this._type!;
  }

  set type(value: ServiceEventType) {
    const oldValue = this._type;
    this._type = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceEventImpl.TYPE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceEventImpl.TYPE,
        merge: () => false
      });
    }
  }

  get reference(): ServiceReference {
    return this._reference!;
  }

  set reference(value: ServiceReference) {
    const oldValue = this._reference;
    this._reference = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceEventImpl.REFERENCE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceEventImpl.REFERENCE,
        merge: () => false
      });
    }
  }

  get timestamp(): Date {
    return this._timestamp!;
  }

  set timestamp(value: Date) {
    const oldValue = this._timestamp;
    this._timestamp = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceEventImpl.TIMESTAMP),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceEventImpl.TIMESTAMP,
        merge: () => false
      });
    }
  }

  get reasonCode(): string {
    return this._reasonCode!;
  }

  set reasonCode(value: string) {
    const oldValue = this._reasonCode;
    this._reasonCode = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceEventImpl.REASON_CODE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceEventImpl.REASON_CODE,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceEventImpl.TYPE:
        return this.type;
      case ServiceEventImpl.REFERENCE:
        return this.reference;
      case ServiceEventImpl.TIMESTAMP:
        return this.timestamp;
      case ServiceEventImpl.REASON_CODE:
        return this.reasonCode;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceEventImpl.TYPE:
        this.type = newValue as ServiceEventType;
        super.eSet(feature, newValue);
        break;
      case ServiceEventImpl.REFERENCE:
        this.reference = newValue as ServiceReference;
        super.eSet(feature, newValue);
        break;
      case ServiceEventImpl.TIMESTAMP:
        this.timestamp = newValue as Date;
        super.eSet(feature, newValue);
        break;
      case ServiceEventImpl.REASON_CODE:
        this.reasonCode = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceEventImpl.TYPE:
        return this._type !== undefined;
      case ServiceEventImpl.REFERENCE:
        return this._reference !== undefined;
      case ServiceEventImpl.TIMESTAMP:
        return this._timestamp !== undefined;
      case ServiceEventImpl.REASON_CODE:
        return this._reasonCode !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceEventImpl.TYPE:
        this._type = undefined;
        return;
      case ServiceEventImpl.REFERENCE:
        this._reference = undefined;
        return;
      case ServiceEventImpl.TIMESTAMP:
        this._timestamp = undefined;
        return;
      case ServiceEventImpl.REASON_CODE:
        this._reasonCode = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
