/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { ServiceOperationFlavor } from './ServiceOperationFlavor.js';
import type { Capability } from './Capability.js';
import { FlavorKind } from './FlavorKind.js';
import type { ServiceFlavor } from './ServiceFlavor.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ServiceFlavor
 * @generated
 */
export abstract class ServiceFlavorImpl extends BasicEObject implements ServiceFlavor {
  // Feature ID Constants (eLiterals)
  static readonly KIND: number = 1;
  static readonly OPERATION_FLAVORS: number = 2;
  static readonly CAPABILITIES: number = 3;
  static readonly NAME: number = 0;

  // Private fields
  private _kind: FlavorKind = FlavorKind.REST;
  private _operationFlavors!: EList<ServiceOperationFlavor>;
  private _capabilities!: EList<Capability>;
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_FLAVOR;
  }

  // Getters and Setters
  get kind(): FlavorKind {
    return this._kind!;
  }

  set kind(value: FlavorKind) {
    const oldValue = this._kind;
    this._kind = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceFlavorImpl.KIND),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceFlavorImpl.KIND,
        merge: () => false
      });
    }
  }

  get operationFlavors(): EList<ServiceOperationFlavor> {
    if (!this._operationFlavors) {
      this._operationFlavors = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('operationFlavors') as EReference);
    }
    return this._operationFlavors;
  }

  get capabilities(): EList<Capability> {
    if (!this._capabilities) {
      this._capabilities = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('capabilities') as EReference);
    }
    return this._capabilities;
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceFlavorImpl.KIND:
        return this.kind;
      case ServiceFlavorImpl.OPERATION_FLAVORS:
        return this.operationFlavors;
      case ServiceFlavorImpl.CAPABILITIES:
        return this.capabilities;
      case ServiceFlavorImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceFlavorImpl.KIND:
        this.kind = newValue as FlavorKind;
        super.eSet(feature, newValue);
        break;
      case ServiceFlavorImpl.OPERATION_FLAVORS:
        this.operationFlavors.clear();
        this.operationFlavors.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceFlavorImpl.CAPABILITIES:
        this.capabilities.clear();
        this.capabilities.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceFlavorImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceFlavorImpl.KIND:
        return this._kind !== FlavorKind.REST;
      case ServiceFlavorImpl.OPERATION_FLAVORS:
        return this._operationFlavors !== undefined && !this._operationFlavors.isEmpty();
      case ServiceFlavorImpl.CAPABILITIES:
        return this._capabilities !== undefined && !this._capabilities.isEmpty();
      case ServiceFlavorImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceFlavorImpl.KIND:
        this._kind = FlavorKind.REST;
        return;
      case ServiceFlavorImpl.OPERATION_FLAVORS:
        if (this._operationFlavors) this._operationFlavors.clear();
        return;
      case ServiceFlavorImpl.CAPABILITIES:
        if (this._capabilities) this._capabilities.clear();
        return;
      case ServiceFlavorImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
