/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Property } from './Property.js';
import type { Diagnostic } from './Diagnostic.js';

/**
 * ServiceInvocationResult
 * @generated
 */
export interface ServiceInvocationResult extends EObject {
  value?: Property;
  diagnostic?: Diagnostic;

}
