/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { VersionedElement } from './VersionedElement';
import type { ServiceInterface } from './ServiceInterface';
import type { ServiceFlavor } from './ServiceFlavor';
import type { Property } from './Property';
import type { ComponentDescription } from './ComponentDescription';
import type { ServiceImplementation } from './ServiceImplementation';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ServiceImplementation
 * @generated
 */
export class ServiceImplementationImpl extends BasicEObject implements ServiceImplementation {
  // Feature ID Constants (eLiterals)
  static readonly DESCRIPTION: number = 2;
  static readonly IMPLEMENTATION_ID: number = 3;
  static readonly SERVICE_INTERFACES: number = 4;
  static readonly FLAVORS: number = 5;
  static readonly PROPERTIES: number = 6;
  static readonly COMPONENT_DESCRIPTION: number = 7;
  static readonly NAME: number = 0;
  static readonly VERSION: number = 1;

  // Private fields
  private _description?: string;
  private _implementationId: string = "";
  private _serviceInterfaces: ServiceInterface[] = [];
  private _flavors: ServiceFlavor[] = [];
  private _properties: Property[] = [];
  private _componentDescription?: ComponentDescription;
  private _name: string = "";
  private _version?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_IMPLEMENTATION;
  }

  // Getters and Setters
  get description(): string {
    return this._description!;
  }

  set description(value: string) {
    const oldValue = this._description;
    this._description = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.DESCRIPTION,
        merge: () => false
      });
    }
  }

  get implementationId(): string {
    return this._implementationId!;
  }

  set implementationId(value: string) {
    const oldValue = this._implementationId;
    this._implementationId = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.IMPLEMENTATION_ID),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.IMPLEMENTATION_ID,
        merge: () => false
      });
    }
  }

  get serviceInterfaces(): ServiceInterface[] {
    return this._serviceInterfaces;
  }

  set serviceInterfaces(value: ServiceInterface[]) {
    const oldValue = this._serviceInterfaces;
    this._serviceInterfaces = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.SERVICE_INTERFACES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.SERVICE_INTERFACES,
        merge: () => false
      });
    }
  }

  get flavors(): ServiceFlavor[] {
    return this._flavors;
  }

  set flavors(value: ServiceFlavor[]) {
    const oldValue = this._flavors;
    this._flavors = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.FLAVORS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.FLAVORS,
        merge: () => false
      });
    }
  }

  get properties(): Property[] {
    return this._properties;
  }

  set properties(value: Property[]) {
    const oldValue = this._properties;
    this._properties = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.PROPERTIES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.PROPERTIES,
        merge: () => false
      });
    }
  }

  get componentDescription(): ComponentDescription {
    return this._componentDescription!;
  }

  set componentDescription(value: ComponentDescription) {
    const oldValue = this._componentDescription;
    this._componentDescription = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.COMPONENT_DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.COMPONENT_DESCRIPTION,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  get version(): string {
    return this._version!;
  }

  set version(value: string) {
    this._version = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceImplementationImpl.DESCRIPTION:
        return this.description;
      case ServiceImplementationImpl.IMPLEMENTATION_ID:
        return this.implementationId;
      case ServiceImplementationImpl.SERVICE_INTERFACES:
        return this.serviceInterfaces;
      case ServiceImplementationImpl.FLAVORS:
        return this.flavors;
      case ServiceImplementationImpl.PROPERTIES:
        return this.properties;
      case ServiceImplementationImpl.COMPONENT_DESCRIPTION:
        return this.componentDescription;
      case ServiceImplementationImpl.NAME:
        return this.name;
      case ServiceImplementationImpl.VERSION:
        return this.version;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceImplementationImpl.DESCRIPTION:
        this.description = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.IMPLEMENTATION_ID:
        this.implementationId = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.SERVICE_INTERFACES:
        this.serviceInterfaces = newValue as ServiceInterface[];
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.FLAVORS:
        this.flavors = newValue as ServiceFlavor[];
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.PROPERTIES:
        this.properties = newValue as Property[];
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.COMPONENT_DESCRIPTION:
        this.componentDescription = newValue as ComponentDescription;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.VERSION:
        this.version = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceImplementationImpl.DESCRIPTION:
        return this._description !== undefined;
      case ServiceImplementationImpl.IMPLEMENTATION_ID:
        return this._implementationId !== "";
      case ServiceImplementationImpl.SERVICE_INTERFACES:
        return this._serviceInterfaces !== undefined && this._serviceInterfaces.length > 0;
      case ServiceImplementationImpl.FLAVORS:
        return this._flavors !== undefined && this._flavors.length > 0;
      case ServiceImplementationImpl.PROPERTIES:
        return this._properties !== undefined && this._properties.length > 0;
      case ServiceImplementationImpl.COMPONENT_DESCRIPTION:
        return this._componentDescription !== undefined;
      case ServiceImplementationImpl.NAME:
        return this._name !== "";
      case ServiceImplementationImpl.VERSION:
        return this._version !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceImplementationImpl.DESCRIPTION:
        this._description = undefined;
        return;
      case ServiceImplementationImpl.IMPLEMENTATION_ID:
        this._implementationId = "";
        return;
      case ServiceImplementationImpl.SERVICE_INTERFACES:
        this._serviceInterfaces = [];
        return;
      case ServiceImplementationImpl.FLAVORS:
        this._flavors = [];
        return;
      case ServiceImplementationImpl.PROPERTIES:
        this._properties = [];
        return;
      case ServiceImplementationImpl.COMPONENT_DESCRIPTION:
        this._componentDescription = undefined;
        return;
      case ServiceImplementationImpl.NAME:
        this._name = "";
        return;
      case ServiceImplementationImpl.VERSION:
        this._version = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
