/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList, createEObjectEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { VersionedElement } from './VersionedElement.js';
import type { ServiceInterface } from './ServiceInterface.js';
import type { ServiceFlavor } from './ServiceFlavor.js';
import type { Property } from './Property.js';
import type { ComponentDescription } from './ComponentDescription.js';
import type { Capability } from './Capability.js';
import { UpdatePolicy } from './UpdatePolicy.js';
import type { ServiceImplementation } from './ServiceImplementation.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ServiceImplementation
 * @generated
 */
export class ServiceImplementationImpl extends BasicEObject implements ServiceImplementation {
  // Feature ID Constants (eLiterals)
  static readonly DESCRIPTION: number = 2;
  static readonly IMPLEMENTATION_ID: number = 3;
  static readonly SERVICE_INTERFACES: number = 4;
  static readonly FLAVORS: number = 5;
  static readonly PROPERTIES: number = 6;
  static readonly COMPONENT_DESCRIPTION: number = 7;
  static readonly UPDATE_POLICY: number = 8;
  static readonly REPLACES: number = 9;
  static readonly CUTOVER_GRACE_MILLIS: number = 10;
  static readonly CAPABILITIES: number = 11;
  static readonly NAME: number = 0;
  static readonly VERSION: number = 1;

  // Private fields
  private _description?: string;
  private _implementationId: string = "";
  private _serviceInterfaces!: EList<ServiceInterface>;
  private _flavors!: EList<ServiceFlavor>;
  private _properties!: EList<Property>;
  private _componentDescription?: ComponentDescription;
  private _updatePolicy: UpdatePolicy = UpdatePolicy.UNSPECIFIED;
  private _replaces?: ServiceImplementation;
  private _cutoverGraceMillis?: number;
  private _capabilities!: EList<Capability>;
  private _name: string = "";
  private _version?: string;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_IMPLEMENTATION;
  }

  // Getters and Setters
  get description(): string {
    return this._description!;
  }

  set description(value: string) {
    const oldValue = this._description;
    this._description = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.DESCRIPTION,
        merge: () => false
      });
    }
  }

  get implementationId(): string {
    return this._implementationId!;
  }

  set implementationId(value: string) {
    const oldValue = this._implementationId;
    this._implementationId = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.IMPLEMENTATION_ID),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.IMPLEMENTATION_ID,
        merge: () => false
      });
    }
  }

  get serviceInterfaces(): EList<ServiceInterface> {
    if (!this._serviceInterfaces) {
      this._serviceInterfaces = createEObjectEList(this, this.eClass().getEStructuralFeature('serviceInterfaces') as EReference) as unknown as EList<ServiceInterface>;
    }
    return this._serviceInterfaces;
  }

  get flavors(): EList<ServiceFlavor> {
    if (!this._flavors) {
      this._flavors = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('flavors') as EReference);
    }
    return this._flavors;
  }

  get properties(): EList<Property> {
    if (!this._properties) {
      this._properties = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('properties') as EReference);
    }
    return this._properties;
  }

  get componentDescription(): ComponentDescription {
    return this._componentDescription!;
  }

  set componentDescription(value: ComponentDescription) {
    const oldValue = this._componentDescription;
    this._componentDescription = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.COMPONENT_DESCRIPTION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.COMPONENT_DESCRIPTION,
        merge: () => false
      });
    }
  }

  get updatePolicy(): UpdatePolicy {
    return this._updatePolicy!;
  }

  set updatePolicy(value: UpdatePolicy) {
    const oldValue = this._updatePolicy;
    this._updatePolicy = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.UPDATE_POLICY),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.UPDATE_POLICY,
        merge: () => false
      });
    }
  }

  get replaces(): ServiceImplementation {
    return this._replaces!;
  }

  set replaces(value: ServiceImplementation) {
    const oldValue = this._replaces;
    this._replaces = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.REPLACES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.REPLACES,
        merge: () => false
      });
    }
  }

  get cutoverGraceMillis(): number {
    return this._cutoverGraceMillis!;
  }

  set cutoverGraceMillis(value: number) {
    const oldValue = this._cutoverGraceMillis;
    this._cutoverGraceMillis = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceImplementationImpl.CUTOVER_GRACE_MILLIS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceImplementationImpl.CUTOVER_GRACE_MILLIS,
        merge: () => false
      });
    }
  }

  get capabilities(): EList<Capability> {
    if (!this._capabilities) {
      this._capabilities = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('capabilities') as EReference);
    }
    return this._capabilities;
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  get version(): string {
    return this._version!;
  }

  set version(value: string) {
    this._version = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceImplementationImpl.DESCRIPTION:
        return this.description;
      case ServiceImplementationImpl.IMPLEMENTATION_ID:
        return this.implementationId;
      case ServiceImplementationImpl.SERVICE_INTERFACES:
        return this.serviceInterfaces;
      case ServiceImplementationImpl.FLAVORS:
        return this.flavors;
      case ServiceImplementationImpl.PROPERTIES:
        return this.properties;
      case ServiceImplementationImpl.COMPONENT_DESCRIPTION:
        return this.componentDescription;
      case ServiceImplementationImpl.UPDATE_POLICY:
        return this.updatePolicy;
      case ServiceImplementationImpl.REPLACES:
        return this.replaces;
      case ServiceImplementationImpl.CUTOVER_GRACE_MILLIS:
        return this.cutoverGraceMillis;
      case ServiceImplementationImpl.CAPABILITIES:
        return this.capabilities;
      case ServiceImplementationImpl.NAME:
        return this.name;
      case ServiceImplementationImpl.VERSION:
        return this.version;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceImplementationImpl.DESCRIPTION:
        this.description = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.IMPLEMENTATION_ID:
        this.implementationId = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.SERVICE_INTERFACES:
        this.serviceInterfaces.clear();
        this.serviceInterfaces.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.FLAVORS:
        this.flavors.clear();
        this.flavors.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.PROPERTIES:
        this.properties.clear();
        this.properties.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.COMPONENT_DESCRIPTION:
        this.componentDescription = newValue as ComponentDescription;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.UPDATE_POLICY:
        this.updatePolicy = newValue as UpdatePolicy;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.REPLACES:
        this.replaces = newValue as ServiceImplementation;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.CUTOVER_GRACE_MILLIS:
        this.cutoverGraceMillis = newValue as number;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.CAPABILITIES:
        this.capabilities.clear();
        this.capabilities.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      case ServiceImplementationImpl.VERSION:
        this.version = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceImplementationImpl.DESCRIPTION:
        return this._description !== undefined;
      case ServiceImplementationImpl.IMPLEMENTATION_ID:
        return this._implementationId !== "";
      case ServiceImplementationImpl.SERVICE_INTERFACES:
        return this._serviceInterfaces !== undefined && !this._serviceInterfaces.isEmpty();
      case ServiceImplementationImpl.FLAVORS:
        return this._flavors !== undefined && !this._flavors.isEmpty();
      case ServiceImplementationImpl.PROPERTIES:
        return this._properties !== undefined && !this._properties.isEmpty();
      case ServiceImplementationImpl.COMPONENT_DESCRIPTION:
        return this._componentDescription !== undefined;
      case ServiceImplementationImpl.UPDATE_POLICY:
        return this._updatePolicy !== UpdatePolicy.UNSPECIFIED;
      case ServiceImplementationImpl.REPLACES:
        return this._replaces !== undefined;
      case ServiceImplementationImpl.CUTOVER_GRACE_MILLIS:
        return this._cutoverGraceMillis !== undefined;
      case ServiceImplementationImpl.CAPABILITIES:
        return this._capabilities !== undefined && !this._capabilities.isEmpty();
      case ServiceImplementationImpl.NAME:
        return this._name !== "";
      case ServiceImplementationImpl.VERSION:
        return this._version !== undefined;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceImplementationImpl.DESCRIPTION:
        this._description = undefined;
        return;
      case ServiceImplementationImpl.IMPLEMENTATION_ID:
        this._implementationId = "";
        return;
      case ServiceImplementationImpl.SERVICE_INTERFACES:
        if (this._serviceInterfaces) this._serviceInterfaces.clear();
        return;
      case ServiceImplementationImpl.FLAVORS:
        if (this._flavors) this._flavors.clear();
        return;
      case ServiceImplementationImpl.PROPERTIES:
        if (this._properties) this._properties.clear();
        return;
      case ServiceImplementationImpl.COMPONENT_DESCRIPTION:
        this._componentDescription = undefined;
        return;
      case ServiceImplementationImpl.UPDATE_POLICY:
        this._updatePolicy = UpdatePolicy.UNSPECIFIED;
        return;
      case ServiceImplementationImpl.REPLACES:
        this._replaces = undefined;
        return;
      case ServiceImplementationImpl.CUTOVER_GRACE_MILLIS:
        this._cutoverGraceMillis = undefined;
        return;
      case ServiceImplementationImpl.CAPABILITIES:
        if (this._capabilities) this._capabilities.clear();
        return;
      case ServiceImplementationImpl.NAME:
        this._name = "";
        return;
      case ServiceImplementationImpl.VERSION:
        this._version = undefined;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
