/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createContainmentEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { ServiceOperation } from './ServiceOperation.js';
import type { Argument } from './Argument.js';
import type { ServiceInvocation } from './ServiceInvocation.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ServiceInvocation
 * @generated
 */
export class ServiceInvocationImpl extends BasicEObject implements ServiceInvocation {
  // Feature ID Constants (eLiterals)
  static readonly OPERATION: number = 0;
  static readonly ARGUMENTS: number = 1;

  // Private fields
  private _operation?: ServiceOperation;
  private _arguments!: EList<Argument>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_INVOCATION;
  }

  // Getters and Setters
  get operation(): ServiceOperation {
    return this._operation!;
  }

  set operation(value: ServiceOperation) {
    const oldValue = this._operation;
    this._operation = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceInvocationImpl.OPERATION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceInvocationImpl.OPERATION,
        merge: () => false
      });
    }
  }

  get arguments(): EList<Argument> {
    if (!this._arguments) {
      this._arguments = createContainmentEList<any>(this, this.eClass().getEStructuralFeature('arguments') as EReference);
    }
    return this._arguments;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInvocationImpl.OPERATION:
        return this.operation;
      case ServiceInvocationImpl.ARGUMENTS:
        return this.arguments;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInvocationImpl.OPERATION:
        this.operation = newValue as ServiceOperation;
        super.eSet(feature, newValue);
        break;
      case ServiceInvocationImpl.ARGUMENTS:
        this.arguments.clear();
        this.arguments.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInvocationImpl.OPERATION:
        return this._operation !== undefined;
      case ServiceInvocationImpl.ARGUMENTS:
        return this._arguments !== undefined && !this._arguments.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceInvocationImpl.OPERATION:
        this._operation = undefined;
        return;
      case ServiceInvocationImpl.ARGUMENTS:
        if (this._arguments) this._arguments.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

}
