/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { RegistryKind } from './RegistryKind';
import type { PublishHook } from './PublishHook';
import type { DiscoveryHook } from './DiscoveryHook';
import type { DistributionHook } from './DistributionHook';
import type { ServiceReference } from './ServiceReference';
import type { ConsumerCapability } from './ConsumerCapability';
import type { ServiceListener } from './ServiceListener';
import type { ServiceRegistry } from './ServiceRegistry';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of ServiceRegistry
 * @generated
 */
export abstract class ServiceRegistryImpl extends BasicEObject implements ServiceRegistry {
  // Feature ID Constants (eLiterals)
  static readonly KIND: number = 1;
  static readonly PUBLISH_HOOKS: number = 2;
  static readonly DISCOVERY_HOOKS: number = 3;
  static readonly DISTRIBUTION_HOOKS: number = 4;
  static readonly NAME: number = 0;

  // Private fields
  private _kind?: RegistryKind;
  private _publishHooks: PublishHook[] = [];
  private _discoveryHooks: DiscoveryHook[] = [];
  private _distributionHooks: DistributionHook[] = [];
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_REGISTRY;
  }

  // Getters and Setters
  get kind(): RegistryKind {
    return this._kind!;
  }

  set kind(value: RegistryKind) {
    const oldValue = this._kind;
    this._kind = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistryImpl.KIND),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistryImpl.KIND,
        merge: () => false
      });
    }
  }

  get publishHooks(): PublishHook[] {
    return this._publishHooks;
  }

  set publishHooks(value: PublishHook[]) {
    const oldValue = this._publishHooks;
    this._publishHooks = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistryImpl.PUBLISH_HOOKS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistryImpl.PUBLISH_HOOKS,
        merge: () => false
      });
    }
  }

  get discoveryHooks(): DiscoveryHook[] {
    return this._discoveryHooks;
  }

  set discoveryHooks(value: DiscoveryHook[]) {
    const oldValue = this._discoveryHooks;
    this._discoveryHooks = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistryImpl.DISCOVERY_HOOKS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistryImpl.DISCOVERY_HOOKS,
        merge: () => false
      });
    }
  }

  get distributionHooks(): DistributionHook[] {
    return this._distributionHooks;
  }

  set distributionHooks(value: DistributionHook[]) {
    const oldValue = this._distributionHooks;
    this._distributionHooks = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceRegistryImpl.DISTRIBUTION_HOOKS),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceRegistryImpl.DISTRIBUTION_HOOKS,
        merge: () => false
      });
    }
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceRegistryImpl.KIND:
        return this.kind;
      case ServiceRegistryImpl.PUBLISH_HOOKS:
        return this.publishHooks;
      case ServiceRegistryImpl.DISCOVERY_HOOKS:
        return this.discoveryHooks;
      case ServiceRegistryImpl.DISTRIBUTION_HOOKS:
        return this.distributionHooks;
      case ServiceRegistryImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceRegistryImpl.KIND:
        this.kind = newValue as RegistryKind;
        super.eSet(feature, newValue);
        break;
      case ServiceRegistryImpl.PUBLISH_HOOKS:
        this.publishHooks = newValue as PublishHook[];
        super.eSet(feature, newValue);
        break;
      case ServiceRegistryImpl.DISCOVERY_HOOKS:
        this.discoveryHooks = newValue as DiscoveryHook[];
        super.eSet(feature, newValue);
        break;
      case ServiceRegistryImpl.DISTRIBUTION_HOOKS:
        this.distributionHooks = newValue as DistributionHook[];
        super.eSet(feature, newValue);
        break;
      case ServiceRegistryImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceRegistryImpl.KIND:
        return this._kind !== undefined;
      case ServiceRegistryImpl.PUBLISH_HOOKS:
        return this._publishHooks !== undefined && this._publishHooks.length > 0;
      case ServiceRegistryImpl.DISCOVERY_HOOKS:
        return this._discoveryHooks !== undefined && this._discoveryHooks.length > 0;
      case ServiceRegistryImpl.DISTRIBUTION_HOOKS:
        return this._distributionHooks !== undefined && this._distributionHooks.length > 0;
      case ServiceRegistryImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceRegistryImpl.KIND:
        this._kind = undefined;
        return;
      case ServiceRegistryImpl.PUBLISH_HOOKS:
        this._publishHooks = [];
        return;
      case ServiceRegistryImpl.DISCOVERY_HOOKS:
        this._discoveryHooks = [];
        return;
      case ServiceRegistryImpl.DISTRIBUTION_HOOKS:
        this._distributionHooks = [];
        return;
      case ServiceRegistryImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

  getServiceReference(interfaceName: string): ServiceReference {
    throw new Error('getServiceReference not implemented');
  }

  getServiceReferences(interfaceName: string, filter: string, capability: ConsumerCapability): ServiceReference {
    throw new Error('getServiceReferences not implemented');
  }

  getAllServiceReferences(interfaceName: string, filter: string, capability: ConsumerCapability): ServiceReference {
    throw new Error('getAllServiceReferences not implemented');
  }

  addServiceListener(listener: ServiceListener): void {
    throw new Error('addServiceListener not implemented');
  }

  removeServiceListener(listener: ServiceListener): void {
    throw new Error('removeServiceListener not implemented');
  }

}
