/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement';
import type { VersionedElement } from './VersionedElement';
import type { ServiceOperation } from './ServiceOperation';
import type { ServiceException } from './ServiceException';
import type { Invariant } from './Invariant';
import type { CatalogStatus } from './CatalogStatus';

/**
 * ServiceInterface
 * @generated
 */
export interface ServiceInterface extends NamedElement, VersionedElement {
  description?: string;
  operations: ServiceOperation[];
  exceptions: ServiceException[];
  invariants: Invariant[];
  status: CatalogStatus;
  deprecationReason?: string;
  replacedBy?: ServiceInterface;

}
