/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { ServiceOperation } from './ServiceOperation.js';

/**
 * ServiceOperationFlavor
 * @generated
 */
export interface ServiceOperationFlavor extends NamedElement {
  operation: ServiceOperation;
  consumes: EList<string>;
  produces: EList<string>;

}
