/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceReference } from './ServiceReference.js';
import type { ServiceProvider } from './ServiceProvider.js';
import type { ServiceImplementation } from './ServiceImplementation.js';
import type { ConsumerSession } from './ConsumerSession.js';
import type { Property } from './Property.js';

/**
 * ServiceRegistration
 * @generated
 */
export interface ServiceRegistration extends EObject {
  reference: ServiceReference;
  unregistered: boolean;
  provider: ServiceProvider;
  implementation: ServiceImplementation;
  usingSessions: EList<ConsumerSession>;
  publishedBy?: string;
  consumerCount?: number;

  unregister(): void;
  setProperties(props: Property): void;
}
