/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import { createBasicEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { NamedElement } from './NamedElement.js';
import type { ServiceOperation } from './ServiceOperation.js';
import type { ServiceOperationFlavor } from './ServiceOperationFlavor.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of ServiceOperationFlavor
 * @generated
 */
export abstract class ServiceOperationFlavorImpl extends BasicEObject implements ServiceOperationFlavor {
  // Feature ID Constants (eLiterals)
  static readonly OPERATION: number = 1;
  static readonly CONSUMES: number = 2;
  static readonly PRODUCES: number = 3;
  static readonly NAME: number = 0;

  // Private fields
  private _operation?: ServiceOperation;
  private _consumes!: EList<string>;
  private _produces!: EList<string>;
  private _name: string = "";

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.SERVICE_OPERATION_FLAVOR;
  }

  // Getters and Setters
  get operation(): ServiceOperation {
    return this._operation!;
  }

  set operation(value: ServiceOperation) {
    const oldValue = this._operation;
    this._operation = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(ServiceOperationFlavorImpl.OPERATION),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => ServiceOperationFlavorImpl.OPERATION,
        merge: () => false
      });
    }
  }

  get consumes(): EList<string> {
    if (!this._consumes) {
      this._consumes = createBasicEList<any>(this, this.eClass().getEStructuralFeature('consumes')!);
    }
    return this._consumes;
  }

  get produces(): EList<string> {
    if (!this._produces) {
      this._produces = createBasicEList<any>(this, this.eClass().getEStructuralFeature('produces')!);
    }
    return this._produces;
  }

  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    this._name = value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationFlavorImpl.OPERATION:
        return this.operation;
      case ServiceOperationFlavorImpl.CONSUMES:
        return this.consumes;
      case ServiceOperationFlavorImpl.PRODUCES:
        return this.produces;
      case ServiceOperationFlavorImpl.NAME:
        return this.name;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationFlavorImpl.OPERATION:
        this.operation = newValue as ServiceOperation;
        super.eSet(feature, newValue);
        break;
      case ServiceOperationFlavorImpl.CONSUMES:
        this.consumes.clear();
        this.consumes.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceOperationFlavorImpl.PRODUCES:
        this.produces.clear();
        this.produces.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      case ServiceOperationFlavorImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationFlavorImpl.OPERATION:
        return this._operation !== undefined;
      case ServiceOperationFlavorImpl.CONSUMES:
        return this._consumes !== undefined && !this._consumes.isEmpty();
      case ServiceOperationFlavorImpl.PRODUCES:
        return this._produces !== undefined && !this._produces.isEmpty();
      case ServiceOperationFlavorImpl.NAME:
        return this._name !== "";
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case ServiceOperationFlavorImpl.OPERATION:
        this._operation = undefined;
        return;
      case ServiceOperationFlavorImpl.CONSUMES:
        if (this._consumes) this._consumes.clear();
        return;
      case ServiceOperationFlavorImpl.PRODUCES:
        if (this._produces) this._produces.clear();
        return;
      case ServiceOperationFlavorImpl.NAME:
        this._name = "";
        return;
      default:
        super.eUnset(feature);
    }
  }

}
