/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Property } from './Property';

/**
 * ShortProperty
 * @generated
 */
export interface ShortProperty extends Property {
  value?: number;

}
