/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { createBasicEList } from '@emfts/core';
import type { EClass, EStructuralFeature, EList, EReference } from '@emfts/core';
import type { Property } from './Property.js';
import { PropertyImpl } from './PropertyImpl.js';
import type { StringListProperty } from './StringListProperty.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of StringListProperty
 * @generated
 */
export class StringListPropertyImpl extends PropertyImpl implements StringListProperty {
  // Feature ID Constants (eLiterals)
  static readonly VALUE: number = 1;

  // Private fields
  private _value!: EList<string>;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.STRING_LIST_PROPERTY;
  }

  // Getters and Setters
  get value(): EList<string> {
    if (!this._value) {
      this._value = createBasicEList<any>(this, this.eClass().getEStructuralFeature('value')!);
    }
    return this._value;
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case StringListPropertyImpl.VALUE:
        return this.value;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case StringListPropertyImpl.VALUE:
        this.value.clear();
        this.value.addAll(newValue as any[]);
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case StringListPropertyImpl.VALUE:
        return this._value !== undefined && !this._value.isEmpty();
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case StringListPropertyImpl.VALUE:
        if (this._value) this._value.clear();
        return;
      default:
        super.eUnset(feature);
    }
  }

}
