/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, EList, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { Property } from './Property.js';

/**
 * StringListProperty
 * @generated
 */
export interface StringListProperty extends Property {
  value: EList<string>;

}
