/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EClass, EStructuralFeature } from '@emfts/core';
import type { Property } from './Property';
import { PropertyImpl } from './PropertyImpl';
import type { StringListProperty } from './StringListProperty';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of StringListProperty
 * @generated
 */
export class StringListPropertyImpl extends PropertyImpl implements StringListProperty {
  // Feature ID Constants (eLiterals)
  static readonly VALUE: number = 1;

  // Private fields
  private _value: string[] = [];

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.STRING_LIST_PROPERTY;
  }

  // Getters and Setters
  get value(): string[] {
    return this._value;
  }

  set value(value: string[]) {
    const oldValue = this._value;
    this._value = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(StringListPropertyImpl.VALUE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => StringListPropertyImpl.VALUE,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case StringListPropertyImpl.VALUE:
        return this.value;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case StringListPropertyImpl.VALUE:
        this.value = newValue as string[];
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case StringListPropertyImpl.VALUE:
        return this._value !== undefined && this._value.length > 0;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case StringListPropertyImpl.VALUE:
        this._value = [];
        return;
      default:
        super.eUnset(feature);
    }
  }

}
