/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ParameterConstraint } from './ParameterConstraint';

/**
 * StringPatternConstraint
 * @generated
 */
export interface StringPatternConstraint extends ParameterConstraint {
  pattern: string;
  minLength?: number;
  maxLength?: number;

}
