/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EClass, EStructuralFeature } from '@emfts/core';
import type { LanguageBinding } from './LanguageBinding.js';
import { LanguageBindingImpl } from './LanguageBindingImpl.js';
import type { TypeScriptBinding } from './TypeScriptBinding.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of TypeScriptBinding
 * @generated
 */
export class TypeScriptBindingImpl extends LanguageBindingImpl implements TypeScriptBinding {
  // Feature ID Constants (eLiterals)

  // Private fields

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.TYPE_SCRIPT_BINDING;
  }

  // Getters and Setters
  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      default:
        super.eUnset(feature);
    }
  }

}
