/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { TypeMapping } from './TypeMapping.js';
import { DDSRPackage } from './DDSRPackage.js';

/**
 * Implementation of TypeMapping
 * @generated
 */
export class TypeMappingImpl extends BasicEObject implements TypeMapping {
  // Feature ID Constants (eLiterals)
  static readonly NEUTRAL_TYPE: number = 0;
  static readonly TARGET: number = 1;
  static readonly GENERATED: number = 2;

  // Private fields
  private _neutralType: string = "";
  private _target: string = "";
  private _generated: boolean = false;

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.TYPE_MAPPING;
  }

  // Getters and Setters
  get neutralType(): string {
    return this._neutralType!;
  }

  set neutralType(value: string) {
    const oldValue = this._neutralType;
    this._neutralType = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(TypeMappingImpl.NEUTRAL_TYPE),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => TypeMappingImpl.NEUTRAL_TYPE,
        merge: () => false
      });
    }
  }

  get target(): string {
    return this._target!;
  }

  set target(value: string) {
    const oldValue = this._target;
    this._target = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(TypeMappingImpl.TARGET),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => TypeMappingImpl.TARGET,
        merge: () => false
      });
    }
  }

  get generated(): boolean {
    return this._generated!;
  }

  set generated(value: boolean) {
    const oldValue = this._generated;
    this._generated = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(TypeMappingImpl.GENERATED),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => TypeMappingImpl.GENERATED,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case TypeMappingImpl.NEUTRAL_TYPE:
        return this.neutralType;
      case TypeMappingImpl.TARGET:
        return this.target;
      case TypeMappingImpl.GENERATED:
        return this.generated;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case TypeMappingImpl.NEUTRAL_TYPE:
        this.neutralType = newValue as string;
        super.eSet(feature, newValue);
        break;
      case TypeMappingImpl.TARGET:
        this.target = newValue as string;
        super.eSet(feature, newValue);
        break;
      case TypeMappingImpl.GENERATED:
        this.generated = newValue as boolean;
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case TypeMappingImpl.NEUTRAL_TYPE:
        return this._neutralType !== "";
      case TypeMappingImpl.TARGET:
        return this._target !== "";
      case TypeMappingImpl.GENERATED:
        return this._generated !== false;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case TypeMappingImpl.NEUTRAL_TYPE:
        this._neutralType = "";
        return;
      case TypeMappingImpl.TARGET:
        this._target = "";
        return;
      case TypeMappingImpl.GENERATED:
        this._generated = false;
        return;
      default:
        super.eUnset(feature);
    }
  }

}
