/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';

/**
 * TypeMapping
 * @generated
 */
export interface TypeMapping extends EObject {
  neutralType: string;
  target: string;
  generated: boolean;

}
