/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { LanguageBinding } from './LanguageBinding.js';

/**
 * TypeScriptBinding
 * @generated
 */
export interface TypeScriptBinding extends LanguageBinding {

}
