/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import { BasicEObject } from '@emfts/core';
import type { EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceReference } from './ServiceReference';
import type { UnsatisfiedReference } from './UnsatisfiedReference';
import { DDSRPackage } from './DDSRPackage';

/**
 * Implementation of UnsatisfiedReference
 * @generated
 */
export class UnsatisfiedReferenceImpl extends BasicEObject implements UnsatisfiedReference {
  // Feature ID Constants (eLiterals)
  static readonly NAME: number = 0;
  static readonly TARGET: number = 1;
  static readonly TARGET_SERVICES: number = 2;

  // Private fields
  private _name: string = "";
  private _target?: string;
  private _targetServices: ServiceReference[] = [];

  /**
   * Returns the EClass of this object
   */
  override eClass(): EClass {
    return DDSRPackage.Literals.UNSATISFIED_REFERENCE;
  }

  // Getters and Setters
  get name(): string {
    return this._name!;
  }

  set name(value: string) {
    const oldValue = this._name;
    this._name = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(UnsatisfiedReferenceImpl.NAME),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => UnsatisfiedReferenceImpl.NAME,
        merge: () => false
      });
    }
  }

  get target(): string {
    return this._target!;
  }

  set target(value: string) {
    const oldValue = this._target;
    this._target = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(UnsatisfiedReferenceImpl.TARGET),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => UnsatisfiedReferenceImpl.TARGET,
        merge: () => false
      });
    }
  }

  get targetServices(): ServiceReference[] {
    return this._targetServices;
  }

  set targetServices(value: ServiceReference[]) {
    const oldValue = this._targetServices;
    this._targetServices = value;
    if (this.eDeliver()) {
      this.eNotify({
        getNotifier: () => this,
        getEventType: () => 1, // SET
        getFeature: () => this.eClass().getEStructuralFeature(UnsatisfiedReferenceImpl.TARGET_SERVICES),
        getOldValue: () => oldValue,
        getNewValue: () => value,
        getPosition: () => -1,
        wasSet: () => true,
        isTouch: () => false,
        isReset: () => false,
        getFeatureID: () => UnsatisfiedReferenceImpl.TARGET_SERVICES,
        merge: () => false
      });
    }
  }

  // Reflective API

  /**
   * Returns the value of the given feature
   */
  override eGet(feature: EStructuralFeature): unknown {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case UnsatisfiedReferenceImpl.NAME:
        return this.name;
      case UnsatisfiedReferenceImpl.TARGET:
        return this.target;
      case UnsatisfiedReferenceImpl.TARGET_SERVICES:
        return this.targetServices;
      default:
        return super.eGet(feature);
    }
  }

  /**
   * Sets the value of the given feature
   */
  override eSet(feature: EStructuralFeature, newValue: unknown): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case UnsatisfiedReferenceImpl.NAME:
        this.name = newValue as string;
        super.eSet(feature, newValue);
        break;
      case UnsatisfiedReferenceImpl.TARGET:
        this.target = newValue as string;
        super.eSet(feature, newValue);
        break;
      case UnsatisfiedReferenceImpl.TARGET_SERVICES:
        this.targetServices = newValue as ServiceReference[];
        super.eSet(feature, newValue);
        break;
      default:
        super.eSet(feature, newValue);
    }
  }

  /**
   * Returns whether the feature has been set
   */
  override eIsSet(feature: EStructuralFeature): boolean {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case UnsatisfiedReferenceImpl.NAME:
        return this._name !== "";
      case UnsatisfiedReferenceImpl.TARGET:
        return this._target !== undefined;
      case UnsatisfiedReferenceImpl.TARGET_SERVICES:
        return this._targetServices !== undefined && this._targetServices.length > 0;
      default:
        return super.eIsSet(feature);
    }
  }

  /**
   * Unsets the given feature
   */
  override eUnset(feature: EStructuralFeature): void {
    const featureID = this.eClass().getFeatureID(feature);
    switch (featureID) {
      case UnsatisfiedReferenceImpl.NAME:
        this._name = "";
        return;
      case UnsatisfiedReferenceImpl.TARGET:
        this._target = undefined;
        return;
      case UnsatisfiedReferenceImpl.TARGET_SERVICES:
        this._targetServices = [];
        return;
      default:
        super.eUnset(feature);
    }
  }

}
