/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';
import type { ServiceReference } from './ServiceReference';

/**
 * UnsatisfiedReference
 * @generated
 */
export interface UnsatisfiedReference extends EObject {
  name: string;
  target?: string;
  targetServices: ServiceReference[];

}
