/*
 * This file was generated by emfts-codegen.
 * DO NOT EDIT - changes will be overwritten.
 *
 * @generated
 */

import type { EObject, BasicEObject, EClass, EStructuralFeature } from '@emfts/core';

/**
 * VersionedElement
 * @generated
 */
export interface VersionedElement extends EObject {
  version?: string;

}
