/********************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 ********************************************************************/

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * The two language tracks share one model, and nothing was making sure
 * of it.
 *
 * `org.eclipse.fennec.services.model/model/services.ecore` is the
 * canonical source; `packages/ddsr-model/model/ddsr.ecore` is a synced
 * copy that keeps its own FILE NAME only (the namespace, the classes
 * and every feature are the same model, see CLAUDE.md). The copy is
 * synced by hand and regenerated by hand, which worked exactly as well
 * as that sounds: the four audit attributes of #125 sat in the Java
 * model for a whole wave before anyone noticed the TypeScript side had
 * never been updated.
 *
 * A byte comparison is the whole check. It is deliberately not
 * structural or tolerant: the point is that the copy is a copy, and
 * "close enough" is how a cross-language contract drifts. When this
 * fails, copy the file across and regenerate:
 *
 *     cp ../../org.eclipse.fennec.services.model/model/services.ecore \
 *        packages/ddsr-model/model/ddsr.ecore
 *     pnpm --filter @ddsr/model generate
 */
describe('the TypeScript model is the Java model', () => {
  const here = fileURLToPath(new URL('.', import.meta.url));
  const canonical = `${here}../../../../org.eclipse.fennec.services.model/model/services.ecore`;
  const copy = `${here}../model/ddsr.ecore`;

  it('is byte-identical to the canonical ecore', () => {
    const expected = readFileSync(canonical, 'utf8');
    const actual = readFileSync(copy, 'utf8');

    if (actual !== expected) {
      // A full diff of a 1200-line file helps nobody. Name the first
      // line that differs and the features that are missing, which is
      // what a drift actually looks like.
      const missing = featureNames(expected).filter((name) => !featureNames(actual).includes(name));
      const extra = featureNames(actual).filter((name) => !featureNames(expected).includes(name));
      const firstDifference = firstDifferingLine(expected, actual);
      expect.fail(
        [
          'packages/ddsr-model/model/ddsr.ecore has drifted from the Java model.',
          missing.length ? `  missing here: ${missing.join(', ')}` : '',
          extra.length ? `  only here: ${extra.join(', ')}` : '',
          `  first differing line: ${firstDifference}`,
          '  fix: copy services.ecore over ddsr.ecore, then pnpm --filter @ddsr/model generate',
        ]
          .filter(Boolean)
          .join('\n'),
      );
    }
  });
});

/** Every `name="…"` of a structural feature, in document order. */
function featureNames(ecore: string): string[] {
  return [...ecore.matchAll(/<eStructuralFeatures[^>]*?name="([^"]+)"/g)].map((match) => match[1]);
}

function firstDifferingLine(expected: string, actual: string): string {
  const expectedLines = expected.split('\n');
  const actualLines = actual.split('\n');
  for (let i = 0; i < Math.max(expectedLines.length, actualLines.length); i++) {
    if (expectedLines[i] !== actualLines[i]) {
      return `${i + 1}\n    java: ${truncate(expectedLines[i])}\n    here: ${truncate(actualLines[i])}`;
    }
  }
  return '(none — the files differ only in length)';
}

function truncate(line: string | undefined): string {
  if (line === undefined) return '<end of file>';
  return line.length > 120 ? `${line.slice(0, 120)}…` : line;
}
